### ISSUE TITLE
Incorporar elements de l'Entitat a capçalera i peu de pàgina

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#106]
(1) Incorporar els elements de l'Entitat a capçalera i peu de pàgina del back en al cas de ser Administradors d'Entitat, com per exemple nom, icones, adreces, ...

(2) Gestionar el botar entre dues entitats si se és Administrador d'Entitat

**Comment by jagarcia-fundaciobit** [comment]
S'ha inserit els logos de l'entitat al cap i peu de página del back. 
Si l'usuari té més d'una entitat, es llisten totes al desplegable del menú de configuració i es permet canviar d'entitat.
