### ISSUE TITLE
Configuració de KEYCLOAK-DEV (Donar d'alta persones via NIF)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#110]
Depèn de PROJECT

En el tiquet "Gestió dels Usuaris #83 " es bva implementar codi per donar d'alta persones a partir del seu USERNAME.

Queda pendent poder donar d'alta persones a partir del NIF. El problema està en que des de DEV, keycloak no està enllaçat amb cap LDAP i no es torna informació de NIF ni es pot fer consultes a partir d'aquest camp.

**Comment by scalafat-dgtic** [comment]
S'està a l'espera de encetar amb Sistemes i aclarir com replicar el model de Keycloak-PRE a Keycloak-DEV sense fer servir l'LDAP de Seycon.

**Comment by scalafat-dgtic** [comment]
La idea és la de replicar el model existent a PRE actualment.

Al Govern, el Keycloak compta amb dos clients molt importants (en pot haver algun més, segons els [estàndards](http://dgtic.caib.es/estandards)):
- goib-default: permet autenticació d'usuaris als backoffices de les aplicacions
- goib-ws: permet l'autenticació d'aplicacions per a les APIs REST

A PRE, actualment, el client goib-default té els següents "mappers"

![M5](https://user-images.githubusercontent.com/44995350/99225434-595b8c80-27e8-11eb-9afc-75210187a94b.png)

I l'usuari-persona creat dins Keycloak i/o obtingut via Seycon ha de comptar amb els següents atributs, que es podran aconseguir des del valor **otherClaims** del KeycloakPrincipal.

![M4](https://user-images.githubusercontent.com/44995350/99225653-ae979e00-27e8-11eb-896a-ca529cf149bf.png)

**Comment by anadal-fundaciobit** [comment]
S'ha llegit a pinyo fix el KeyCloakPrincipal en cas d'estar en una Entitat CAIB.
