### ISSUE TITLE
Implementar sistema per obtenir contrasenyes de plugin a traves de Propietats de Sistema

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#112]
Actualment les contrasenyes es veuen en clar dins de les propietats dels Plugins. S'hauria de implementar un sistema per poder referenciar valors de system properties dins de les propietats del plugin.
Una idea seria utilitzar freemarker per fer substitució d'expressions tipus ${props['es.caib.carpeta.pluginfront.sistra.contrasenya']} que els valor es trobi dins de le propietats de sistema (Aquest canvis s'han de realitzar al mètode getInstanceByPluginID de la classe AbstractPluginLogicaEJB (de logic):

(1) Llegir les properties del plugin en format String (ja està fet)
(2) Crear un map i afegir un element amb clau "props" i valor System.getProperties()
(3) Cridar a TemplateEngine per fer la substitució
(4) Instanciar el plugin amb les noves propietats(ja està fet)

![imatge](https://user-images.githubusercontent.com/17084256/91267827-7433dd00-e774-11ea-93ef-f83f33e02748.png)

**Comment by anadal-fundaciobit** [comment]
Configuration cfg; // ... cfg.setInterpolationSyntax(SQUARE_BRACKET_INTERPOLATION_SYNTAX);
--

**Comment by anadal-fundaciobit** [comment]
Part està ja implementat a TemplateEngine: https://github.com/GovernIB/portafib/issues/328

**Comment by jagarcia-fundaciobit** [comment]
Amb el desenvolupament d'aquesta issue, certes propietats definides dins la pestanya de configuració del plugin al back són "amagades" als usuaris superadministradors perqué es defineixen només al properties del projecte al qual no hi té accès. És útil per guardar usuaris i contrasenyes. 

Un exemple, a la configuració del plugin es posaria d'aquesta forma: 
es.caib.carpeta.pluginsib.carpetafront.sistra1.url=**[=SP["es.caib.carpeta.sistra1.url"]]** 

On es.caib.carpeta.sistra1.url es la propietat que es definirá dins el carpeta.properties guardat dins el jboss.
