### ISSUE TITLE
Adaptar fitxers de Propietats al que diuen els estandards

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#120]
Abans de res s'ha de demanar a en Simo com tenen configurat el JBos 7 la gent de Sistemes per a que automàticament carregui el fitxers de Propietats.

(0) Revisar el document Propietats.pdf
(1) Adaptar el codi per a llegir les propietats dels dos fitxers (revisar si es pot fer des de Logic emprant la classe StartUpServiceEJB)
(2) Les propietats generals carrergar-les dins de System.properties
(3) Les propietats de es.caib.carpeta.system.properties guardar-les dins d'Utils (Commons)
(4) Moure la propietat "es.caib.carpeta.filesdirectory" a "es.caib.carpeta.fitxers" i fer que es gestioni des de StartUpServiceEJB
(5)  Documentar-ho al manual de Instal·lació
(6) Enviar un correu als companys de desenvolupament explicant el que han de fer.

[StartupServiceEJB.java.log](https://github.com/GovernIB/carpeta/files/5188219/StartupServiceEJB.java.log)

[Propietats.pdf](https://github.com/GovernIB/carpeta/files/5188156/Propietats.pdf)

**Comment by mgonzalez-fundaciobit** [comment]
De moment a la CAIB només fan feina amb un únic document de propietats, més envant si acaben d'implantar lo dels dos fitxer, s'haurà de mirar d'adaptar novament.

**Comment by mgonzalez-fundaciobit** [comment]
Solventat que funcioni també el front.

**Comment by anadal-fundaciobit** [comment]
Al final en Simo s'ha decidit pels dos fitxers. Un solució simple és que  Configuracio de Commons-Utils carregui els dos fitxers de properties en una sola instància de la classe  Properties.  Torna a revisar els @Value.

**Comment by anadal-fundaciobit** [comment]
Marile, revisa si es gestiona bé la propietat: es.caib.carpeta.filesystemmanagerclass

**Comment by mgonzalez-fundaciobit** [comment]
Ok.

**Comment by mgonzalez-fundaciobit** [comment]
Revisat i moguda la propietat  "es.caib.carpeta.filesystemmanagerclass" al fitxer carpeta.system.properties.
