### ISSUE TITLE
Personalitzar els plugins al front

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#122]
**Com a** desenvolupador de l'aplicació **vull** poder personalitzar cada un dels plugins al front de Carpeta 0.0.1 **per** poder saber de quin tipus són, afegir una icona, etc.

**Comment by anadal-fundaciobit** [comment]
Aquest issue depend de la finalització de "Afegir icones per cada plugin #124 "

**Comment by jpernia-fundaciobit** [comment]
Es mostren les icones al front i cada plugin pot determinar si és de tipus React o si és Html.
