### ISSUE TITLE
Afegir icones per cada plugin

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#124]
Afegir un mètode a l'API de PLugin de Front del tipus  "FileInfo getIcon(String locale);". La classe Filke info contindira nom, mime i byte[].  Aquest logo o icona es llegirà dels recursos del plugin.

**Comment by mgonzalez-fundaciobit** [comment]
La url per descarregar l'icona és
http://localhost:8080/carpetafront/pluginfront/pluginicon/${pluginID}/${idioma}

**Comment by mgonzalez-fundaciobit** [comment]
S'han d'eliminar els logos de cada plugin de webresources perque en breu es migraran els plugins a react.

**Comment by mgonzalez-fundaciobit** [comment]
S'ha mogut el logo fora del webreosurces. Ara es troben a la carpeta logo.
