### ISSUE TITLE
En digitalIB tenir en compte el tema del tipus de Còpia 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#125]
Bon dia, ,
Arran de la reunió d'ahir amb l'OAE convé tenir present que la funcionalitat de digitalització massiva també ha de contemplar que únicament usuaris amb rols DIB_USER podran especificar "Còpia Autèntica" com estat de elaboració. Els que no tinguin el rol només podran indicar "Còpia"
Endmés també ha de desapareix "Original" com a valor seleccionable en el desplegable.
Només perquè ho tinguis en compte.

Salutacions,

**Comment by kitanibaladmin** [comment]
Aquesta tasca és de DigitalIB !!!!!
