### ISSUE TITLE
Actualitzar jar de WS de SISTRA 1

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#127]
En Simó ens ha passat la darrera versió del jar de Zona Personal de SISTRA v1. 
S'ha d'actualitzar la part de SISTRAv1 del plugin de SISTRA amb la nova llibreria.

[ZonaperV2.zip](https://github.com/GovernIB/carpeta/files/5290297/ZonaperV2.zip)

**Comment by jagarcia-fundaciobit** [comment]
S'ha actualitzat el pom.xml de pluginsib-carpetafront. 
També s'ha pujat el JAR al repositori maven (https://github.com/GovernIB/maven)
