### ISSUE TITLE
Controlar Tamany de icona de capçalera

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#128]
Depèn de "Millores en el codi del BACK #480"

Pareix que s'ha elegit una icona massa petita. Crec que el millor es definir un tamany de icona i validar-ho quan es dóna d'alta l'entitat.

![imatge](https://user-images.githubusercontent.com/17084256/94432594-47ba1900-0197-11eb-9711-0f749b1f487e.png)

Recomanacions:
    (1) En el postValidate mirar que el logocap no tengui errors
    (2) En aquest cas, llegir el fitxer com una imatge java i revisar l'altura.
    (3) Comprovar que estigui en un marge raonable.
    (4) En cas de no estar-hi afegir un error al camp LOGOCAP.

**Comment by jagarcia-fundaciobit** [comment]
S'ha revisat i s'està aplicant una regla CSS que posa un width de 45px. S'ha revisat per diferents tamanys i corregit.
