### ISSUE TITLE
Eliminar XtrustProvider de Plugin de Regweb3 i Sistra

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#134]
Eliminar XtrustProvider de Plugin de Regweb3 i Sistra

**Comment by jagarcia-fundaciobit** [comment]
S'ha eliminat del projecte les mencions que es feien al XTrustProvider per un tema de seguretat de les aplicacions.

Enlloc d'utilitzar el XTrust, s'han d'instal·lar els corresponents certificats a la nostra màquina virtual.

Per fer-ho fàcil, s'ha d'executar el fitxer installCerts.bat  (https://github.com/GovernIB/maven/tree/binaris/certificatsgoib), que instal·la automàticament dins la JVM els certificats més comuns que es requereixen pels entorns de la caib. Just fixat la variable JAVA_HOME i executant l'script ja s'instal·len en mode administrador. Va bé per Java 6, 7, 8 i 11. Això si, requereix tenir instal·lat l'executable "openssl" (ve per defecte amb el cygwin si el teniu).

Els servidors que hi ha ara estan a la línia 7 de l'script:

    set SERVIDORS=dev.caib.es;intranet.caib.es;afirmades.caib.es:4430;pre.firmacloud.com
