### ISSUE TITLE
Canviar Nom de Propietats Globals dins l'Administrador d'Entitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#137]
Depèn de "Millores en el codi del BACK #191"

Canviar el Nom de Propietats Globals dins l'Administrador d'Entitat per "Propietats d'Entitat".

El canvi es molt senzill, s'han de sobre carregar els mètodes    public String getEntityNameCode() i  String getEntityNameCodePlural() de la classe PropietatGlobalAdminEntitatController i fer que retornin codis de traducció nous que s'hauran definit a missatges_ca.properties, ... de back.

**Comment by jagarcia-fundaciobit** [comment]
Si l'usuari és administrador d'entitat se li canvia el nom mentre que si és superadministrador, es manté com a Propietats Globals.
