### ISSUE TITLE
Revisar els inputs de tipus File del Back

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#141]
Depèn de Millores en el codi del BACK #191

S'ha de trobar una llibreria js+css per mostrar i gestionar inputs de tipus File. L'actual no mostrar el fitxer seleccionat 

![imatge](https://user-images.githubusercontent.com/17084256/95425555-c0159c80-0944-11eb-8753-eefe361e21d4.png)

![imatge](https://user-images.githubusercontent.com/17084256/95425295-58f7e800-0944-11eb-8747-812576a6463d.png)

**Comment by jagarcia-fundaciobit** [comment]
Solucionat. S'ha modificat es template, per javascript es detecta quan es selecciona un fitxer, agafa el nom i el pinta al costat. D'aquesta forma, l'usuari veu quin fitxer s'ha seleccionat.
