### ISSUE TITLE
Revisió Gestió d'Entitats al Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#142]
Depèn de "Millores en la UI del Front #193"

S'ha de revisar si el front és multientitat.
  (1) A l'entrada al front s'ha de revisar si hi ha entitat per defecte. Si es així, configurar el front per aquesta entitat. En cas contrari, hem d'anar a una pàgina de selecció de l'entitat que volem.
  (2) S'ha de crear un request (controller) per configurar un front per una detern¡minada entitat: per exemple http://host:port/carpetafront/e/[CODI_ENTITAT]

**Comment by jpernia-fundaciobit** [comment]
Per aquesta release es tria l'entitat a través d'un jsp. Per la propera es mirarà si fer-ho com un component. Si al final queda amb el jsp, s'ha de millorar la vista. 
També s'hauran de mostrar totes les dades de cada entitat a l'apartat públic.

**Comment by jpernia-fundaciobit** [comment]
https://github.com/GovernIB/carpeta/commit/b7e3a86276d4819d495a362cb7c7f1c99403b9dc

**Comment by jpernia-fundaciobit** [comment]
De moment es deixa que no es pot canviar entre entitats una vegada s'ha triat una al front.
