### ISSUE TITLE
Configuració del logo del menú lateral segons dades de l'entitat

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#143]
Prové de #139

**Com a** desenvolupador de l'aplicació **vull** mostrar el logo del menú lateral de l'entitat activa **per** destriar entre diferents entitats

**Comment by anadal-fundaciobit** [comment]
Fet. Per obtenir informació del logo lateral cridar a la següent URL: http://localhost:8080/carpetafront/webui/infologolateral

![imatge](https://user-images.githubusercontent.com/17084256/96431184-70b45380-1203-11eb-9965-193545eac2f4.png)

**Comment by jpernia-fundaciobit** [comment]
El logo no es limita en tamany, per tant, es mostrarà el tamany original. S'haurà d'anar alerta als logos que es posin.
