### ISSUE TITLE
Gestión de avisos de mantenimiento del Back

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#144]
Como: Administrador de la aplicación
Quiero: Crear avisos temporales de incidencias en terceras aplicaciones
Para: Avisar al usuario final de posibles incidencias programadas.

Depèn de Gestión de avisos de mantenimiento #28

**Comment by jagarcia-fundaciobit** [comment]
S'ha creat un nou manteniment d'avisos al back. Els usuaris administradors només veuen els avisos de la seva entitat mentre que els superadministradors, els veuen tots.  A la opció de menú, es mostren en vermell el número d'avisos actius.

També s'ha afegit un camp de gravetat per delimitar on sortiran els avisos: 

- front abans de login
- front després de login
- plugin
- back plugin
- back general

**Comment by anadal-fundaciobit** [comment]
La gestió d'això ha d'estar a un lloc on sempre s'executi ino al principal. Aquest lloc és el base preparer. Per favor mou el codi dels avisos del back a BasePreparer:

![imatge](https://user-images.githubusercontent.com/17084256/96964359-9c3c8400-150a-11eb-8174-660590a7635f.png)

**Comment by jagarcia-fundaciobit** [comment]
S'ha mogut la funcionalitat a BasePreparer.
