### ISSUE TITLE
Canvi en la nomenclatura de la propietat que apunta al fitxer de propietats

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#151]
La propietat de sistema definida dins de l'standalone.xml que ha d'apuntar al fitxer de propietats és "es.caib.carpeta.propertiessense" el ".path" final.

**Comment by mgonzalez-fundaciobit** [comment]
S'ha de modificar l'standalone.xml del vostre jboss i llevar-li .path del final.
