### ISSUE TITLE
Mostrar Xarxes Socials al front a partir d'enllaços de tipus Xarxa Social

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#155]
Depèn de Gestió dels enllaços #84 

En la issue "Retornar informació de Enllaços de tipus "Xarxes Socials" al Front #154" s'ha implementa un mètode JSON per retorna informació de les xarxes socials que s'ha de "dibuixar" al front a la cantonada inferiro dreta del Front.

La cridada es http://localhost:8080/carpetafront/webui/socialnetworks.

![imatge](https://user-images.githubusercontent.com/17084256/95856373-3574d900-0d5a-11eb-811b-2a0d8fa31b66.png)

**Comment by jpernia-fundaciobit** [comment]
Canviat el component tipus funció per un de tipus classe.
Feta la cridada REST per obtenir els enllasos de tipus Xarxes i mostrar-los al Peu.
Abans les icones tenien format svg i l'efecte "hover" canviava el color de la icona pel vermell, estils goib. Ara, si s'utilitzen imatges png amg fons blanc, no fa aquest efecte. Per això propòs utilitzar imatges png amb fons transparent com l'adjunta.

![instagram](https://user-images.githubusercontent.com/17266896/96229237-e8ca1180-0f96-11eb-8233-c2e899b05028.png)

**Comment by anadal-fundaciobit** [comment]
Depèn de Configuració del Front segons dades de l'entitat #139
