### ISSUE TITLE
Errors en Plugin de Sistra

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#159]
Depèn de issue #71

Hi ha un parell d'errors al plugin de SISTRA:

(1) VERD: El DateChecker no funciona
(2) VERMELL: L'estat no s'ajusat amb el missatge de llista buida. Canviar-ho per "No hi ha tràmits"
(3) BLAU: No se la causa d'aquest error ...

![imatge](https://user-images.githubusercontent.com/17084256/95984910-307c5c00-0e24-11eb-9eb9-1d319b744643.png)

**Comment by jagarcia-fundaciobit** [comment]
S'han fet els canvis d'aquest correu:
- Control de l'excepció de StringIndexOutOfBoundsException que es produeix perqué el REST ens torna cadena buida.
- Canvi del missatge genèric
- Problema javascript del calendaris ( faltaba incloure la cridada al carpeta.js) 
- Problema javascript del datatables ( s'inicialitzaba dues vegades)

**Comment by jagarcia-fundaciobit** [comment]
S'han realitzat proves d'integració amb Sistra1 i está ok. 

PENDENTS: Proves amb Sistra2. Sembla que s'estan fent canvis o algo. Si no recordo malament, els trámits de Sistra 2, un dels camps retornaven una URL per accedir directament al tràmit i ara no.

**Comment by anadal-fundaciobit** [comment]
La problematica de Clave s'ha mogut a 1.1.5: https://github.com/GovernIB/carpeta/issues/197
