### ISSUE TITLE
Gestionar esborrat d'elements en cascada

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#160]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd i ejbs) #194"

L'esborrat d'elements s'ha de millorar per a que esborri els fitxers associats i elements fill. Per això es crearà una EJB-Logica per cada elements que es gestioni dins del BACK tant de SuperAdministrador com d'Administrador d'Entitat i s'implementarà un mètode deleteFull que esborrarà fitxers i d'altres dependències i retornarà una llista de ID de fitxers qeu s'han d'esborrar.
(1) Enllazos
(2) Avisos
(3) Logs
(4) Usuaries entitat
(5) Plugins-Entitat
(6) Entitat

Un cop fet el deleteFull, s'anirà a cada Controller del Back i es sobrecarregarà el mètode delete(...) per cridar al deleteFull de cada EJB-Logica.

Exemple de deleteFull:

public Set<Long> deleteFull(Long entitatID, boolean deleteFiles) {

Set<Long> files = new HashSet<Long>();
     List<Long> enllazos = enllazLogicaEjb.executeQuery(EnllazFields.ENLLAZID, EnllazFields.ENTITATID.equlas(entitatID));

   for(Long e: enllazos) {
       files.addAlll( enllazLogicaEjb.deleteFull(false));
         
   }

//  AQUI ALTRES REFERENCIES

    delete(entitatID);

    if (deleteFiles) {
        for(Long f: files) {
           if (!FileSystemManager.delete(f)) {
              log.error("Esrror esborrant fitxer amb ID " + f, new Exception());
           };
        }

   }

}

}

**Comment by jagarcia-fundaciobit** [comment]
S'ha implementat el métode de deleteFull tant a Entitat com a Enllaz, que són els únics components que están relacionats amb el maneig de fitxers seguint les pautes esmentades a aquesta issue. 
El esborrament d'una entitat, esborra tots els registres depenents de la mateixa ( avisos, propietats globals, enllaços, log, auditoria, estadística, etc.) així com els fitxers físics d'enllaços, logos i icones.

**Comment by jagarcia-fundaciobit** [comment]
He pujat una correcció. Alhora d'eliminar una enitat, no s'havien d'eliminar els registres d'auditoria, estadistica ni log.
