### ISSUE TITLE
Icona de l'entitat al Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#162]
L'entitat ara conté una icona. Aquesta s'ha d'usar quan es carregui el Front de Carpeta.

El primer serà fer des d'un controller una URL de descàrrega de la icona. has de fer algo com ENLLAZ_LOGO_PATH de CommonFrontController però dins WebUIController. Aqui hi ha el codi per afegir a carpeta-logic per obtenir el iconid d'una entitat

@Override
    public long getIcon(String codiEntitat) throws I18NException {
       return  entitatEjb.executeQueryOne(EntitatFields.ICONID, EntitatFields.CODI.equal(codiEntitat));
}

El segon serà incrustar l'element de tipus ICONA al head de l'html.

**Comment by jagarcia-fundaciobit** [comment]
Càrrga el favicon de l'entitat loguejada accesible desde la URL /webui/icona/.
