### ISSUE TITLE
Mostrar icona de l'entitat dins del Back

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#163]
Depèn de Millores en el codi del BACK #191

Ara l'entitat conté la icona per posar a la pipella del navegador. S'ha de posar quan hi hagi una Administrador d'entitat. Revisar com es fa al cap.jsp per mostrar el logo de l'entitat i fer el mateix per la icona.

**Comment by jagarcia-fundaciobit** [comment]
Si l'usuari té rol de admin, es mostra el de la entitat. Si no en té o no té rol d'entitat, es mostra l'icona que hi havia definit per defecte.
