### ISSUE TITLE
Revisar Controllers del Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#164]
Depèn de "Millores en la UI del Front #193"

S'han de revisar els Controllers del Front ja que no poden llançar errors. Cada request de cada controller ha de capturar els errors i processar-los tal i com fan el RequestMapping de WebUIController

**Comment by jpernia-fundaciobit** [comment]
S'han fet altres coses menors que s'han trobat, com el favicon del jsp per triar entitats.
