### ISSUE TITLE
Gestió de Fitxers Orfes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#168]
Depèn de Millores en el codi del BACK #191

S'ha de replicar el controlador de PortaFIb que revisa els fitxers orfes del sistema. Quasi s'ha de copiar la classe sencera ajustant les referències: https://github.com/GovernIB/portafib/blob/portafib-2.0/back/src/main/java/es/caib/portafib/back/controller/admin/FitxersOrfesController.java

**Comment by jagarcia-fundaciobit** [comment]
S'ha afegit la opció de detectar fitxers orfes al menú de superadmin.
