### ISSUE TITLE
Text informatiu de l'entitat del peu de pàgina del Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#169]
Prove de Configuració del Front segons dades de l'entitat #139

Fer mètode en la capa de lògica i en el WebUIController del Front per retornar el text informatiu de l'entitat. 

En la imatge següent és la zona encerclada en groc (al peu de pàgina)

![imatge](https://user-images.githubusercontent.com/17084256/96435705-0fda4a80-1206-11eb-9c68-6de1329c26f4.png)

**Comment by mgonzalez-fundaciobit** [comment]
Per invocar el mètode la url és 
[host]/carpetafront/webui/textinformatiuentitat

**Comment by mgonzalez-fundaciobit** [comment]
Falta invocar des del front la url i mostrar aquesta informació.

**Comment by jpernia-fundaciobit** [comment]
S'ha separat el text informatiu de Peu.js a dins un altre component. També s'ha modificat els script de base de dades que inserta el codi html del text informatiu de la CAIB, perquè desquadrava els estils del Peu.
