### ISSUE TITLE
Nou tipus d'enllaç pel centre del peu de pàgina del Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#170]
Depèn de Configuració del Front segons dades de l'entitat #139

De la imatge de baix, com que tant RSS i Avis Legal són específics de l'entitat (color vermell). S'hauria de fer un nou tipus d'enllaç i allà afegir els enllaços que aniran allà.

(1) Crear un nou tipus d'enllaç

(2) Recopilar informació dels enllaços i logos dels mateixos

(3) Crear scripts per donar d'alta aquests enllaços a la BBDD i entitat caib.

(4) Crear mètodes de recuperació d'aquests enllaços a WebUIController i lògica

(5) Adaptar component React per mostrar els lleços a partir del json retornat en el punt anterior 

![imatge](https://user-images.githubusercontent.com/17084256/96440092-c4c13700-1207-11eb-8dd5-19eb3472db2b.png)

**Comment by anadal-fundaciobit** [comment]
Fet, Per accedir a la informació dels enllaços atacar a http://localhost:8080/carpetafront/webui/centralfooterlinks.

**Comment by anadal-fundaciobit** [comment]
Falta el Punt (5)

**Comment by jagarcia-fundaciobit** [comment]
S'ha creat un nou component React per mostrar els enllaços del peu central. Agafa el contingut de 
carpetafront/webui/centralfooterlinks excepte per l'enllaç de mapa.
