### ISSUE TITLE
Nou tipus d'enllaç pel lateral de pàgina del Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#171]
Depèn de Configuració del Front segons dades de l'entitat #139

De la imatge de baix, s'han de convertir en una gestió d'enllaços els botons que es troben en el lateral esquerra del Front i que estan encerclats en blau. . S'hauria de fer un nou tipus d'enllaç i allà afegir els enllaços que aniran allà.

(1) Crear un nou tipus d'enllaç

(2) Recopilar informació dels enllaços i logos dels mateixos

(3) Crear scripts per donar d'alta aquests enllaços a la BBDD i entitat caib.

(4) Crear mètodes de recuperació d'aquests enllaços a WebUIController i lògica

(5) Adaptar component React per mostrar els lleços a partir del json retornat en el punt anterior

![imatge](https://user-images.githubusercontent.com/17084256/96441241-84fb4f00-1209-11eb-9427-44972d82b469.png)

**Comment by anadal-fundaciobit** [comment]
Bones fets els punts de (1) a (4). La url de descarrega dels enllaços és http://localhost:8080/carpetafront/webui/laterallinks.
Tenen la mateixa estructura json que els botons de socialnetwork.

Falta el punt (5)

**Comment by jpernia-fundaciobit** [comment]
Ara els links del lateral tenen una imatge associada, per tant, al  fer un hover no canvia d'aspecte.
