### ISSUE TITLE
Avisos d'Entitat pel Front quan no autenticat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#183]
Depèn de Més Avisos pel Front #182

S'ha de cercar algun lloc a la pantalla per mostrar avisos de tipus FRONT_ENTITAT_NO_AUTENTICAT

Mirar si es vol fer conjuntament amb Avisos d'Entitat pel Front quan està autenticat #184

**Comment by jpernia-fundaciobit** [comment]
Fet tant pel front com pl'obtenció de les dades de la BBDD. S'ha afegit a la part alta de la pàgina com a "alert" de bootstrap.
