### ISSUE TITLE
Avisos d'Entitat pel Front quan està autenticat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#184]
Depèn de Més Avisos pel Front #182

S'ha de cercar algun lloc a la pantalla per mostrar avisos de tipus FRONT_ENTITAT_AUTENTICAT

Mirar si es vol fer conjuntament amb la issue "https://github.com/GovernIB/carpeta/issues/183"

**Comment by jpernia-fundaciobit** [comment]
Fet tant pel front com pl'obtenció de les dades de la BBDD. S'ha afegit a la part alta de la pàgina com a "alert" de bootstrap.

**Comment by jpernia-fundaciobit** [comment]
Afegit el canvi d'idioma dins el front i el refresc dels avisos en el nou idioma.
