### ISSUE TITLE
Avisos de problemes en PLugin en el Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#185]
Depen de  "Gestión de avisos de mantenimiento #28"

En la llista informativa de la llista de plugins que retorna PluginFrontController.showAllPlugins() s'ha d'afegir dos camps: avis i gravetat, que normalment estiran buit, però quan no hi estiguin segons la gravetat han d'actuar de la següent forma:
          (1) Si gravetat ERROR: Rodejar plugin de borde vermell i quan s'espitgi mostrar missatge d'error 
          (2) Si gravetat no ERROR: Rodejar plugin de borde groc i quan s'espitgi mostrar missatge associat, quan del dialeg s'espitgi OK obrir el plugin.
 .

**Comment by jpernia-fundaciobit** [comment]
Es mostra al front, tant a la pàgina d'inici com al menú deslliçant, un requadre de color segons l'avís actiu de més gravetat que tengui un plugin. Els avisos de moment els mostra dins un alert.
