### ISSUE TITLE
Retornar Informació des de la capa de Lògica els avisos dels PLugins

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#187]
Depèn de Gestión de avisos de mantenimiento #28

(1) Demanar al responsable de la ISSUE "Avisos de problemes en PLugin en el Front #185" a veure si ja ha commitat els canvis de PluginInfo

(2) Afegir un error i gravetat a cada plugin de la llista de PluginInfo (cridada UtilitiesForFrontLogicaLocal.getFrontPlugins) fent consultes a la taula d'avisos.

**Comment by jpernia-fundaciobit** [comment]
S'ha fet però ara la llista d'avisos actius d'un plugin pot ser més de 1. Per tant, s'agafa el de gravetat més alta.
Part d'aquesta funcionalitat s'ha commitat dins l'issue 185.
