### ISSUE TITLE
No arriba l'error de LoginIB a Carpeta Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#188]
Depèn de Millores en la UI del Front #246

**Com a** desnevolupador del front
**vull** mostrar els errors que provenguin de LoginIB 
**per a que** el ciutadà els vegi al front

Per exemple, estic amb un Firefox sense certificats i la selecció de certificat dóna un error, però aquest retorna al front sense donar detall del que ha passat.

![imatge](https://user-images.githubusercontent.com/17084256/96868015-bf652600-146d-11eb-942b-1eb98324c58a.png)

**Comment by mgonzalez-fundaciobit** [comment]
Quan aquest issue s'hagi fet, s'hauran de fer les proves del 173 per veure que crea be els logs quan hi ha un error.

**Comment by anadal-fundaciobit** [comment]
Ja hi ha el issue "No es mostra cap error si falla el login al front #452" que soluciona això.
