### ISSUE TITLE
Millorar Dades Compartides de Usuari obtingudes de LoginIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#197]
Depèn de "Millores en el codi del BACK CAIB #245"

Necessitam les dades de LoginIB disn dels Plugins.
Cercar sistema generic per compartir aquestaes dades: per exemple llistat de propietats addicionals.

**Comment by jagarcia-fundaciobit** [comment]
Pendent de  "Implementar Plugin de Notificacions #270"

**Comment by anadal-fundaciobit** [comment]
Ara mitjançant un cridada a getUserData(nif) es pot obtenir la informació de lOgin del ciutada. 
IMPORTANT: EN l'entorn de BACK, les dades de Cl@ave valen null.
