### ISSUE TITLE
Opció de Configuració no funciona.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#214]
Depèn de "Millores en el codi del BACK #191"

Quan s'espitjha dins congiguració surt l'error que s'adjunta. Fer que vagi a una pàgina d'edició de l'usuari. 
(1) Estendre el Controller de Gestió d'Usuaris
(2) . Fer que només pugui editar (isNew => false, isLlist => false)
(3) Sobrecarregar el onRedirectOnchange??? i fer que vagi al menú d'inici

![imatge](https://user-images.githubusercontent.com/17084256/97708822-a980e200-1ab9-11eb-9154-33f152de879c.png)

![imatge](https://user-images.githubusercontent.com/17084256/97708848-b1d91d00-1ab9-11eb-80f6-85a882a68d30.png)

**Comment by jagarcia-fundaciobit** [comment]
El controlador ja estava fet. Simplement la ruta del enllaç era incorrecte.
