### ISSUE TITLE
Pantalla Buida al canviar de ROL

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#215]
Depèn de "Millores en el codi del BACK #287"

Canvi de menú provoca una pantalla rara. 

![imatge](https://user-images.githubusercontent.com/17084256/97709271-58252280-1aba-11eb-8ac0-82315612fa81.png)

 Fer que en lloc de buit.jsp mostri la proposta de JAGarcia:

![imatge](https://user-images.githubusercontent.com/17084256/102214247-436ce480-3ed8-11eb-8338-1d2e8b7384b9.png)

**Comment by jagarcia-fundaciobit** [comment]
S'ha creat el contenidor amb el missatge indicat i li he donat aquesta aparença: 

![imagen](https://user-images.githubusercontent.com/70194276/101780890-6cb3fc00-3af7-11eb-8eaf-f270211e74a5.png)

**Comment by scalafat-dgtic** [comment]
Proposta: redirigir directament a la primera opció del menú corresponent o llistar en aquesta pantalla totes les opcions del menú corresponent.
D'aquesta manera, s'estalvia una passa innecessària.

**Comment by anadal-fundaciobit** [comment]
Consultes a SCALAFAT

**Comment by jagarcia-fundaciobit** [comment]
S'ha creat el menu tant per superadministrador com administrador d'entitat.

![imagen](https://user-images.githubusercontent.com/70194276/103520836-1331b980-4e78-11eb-9920-f49a3daf71aa.png)
 
![imagen](https://user-images.githubusercontent.com/70194276/103520873-2775b680-4e78-11eb-9687-29a31a4c8651.png)
