### ISSUE TITLE
Obtenció del justificant de registre en tots els casos

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#217]
Depèn de Integració amb REGWEB3 #130.

Actualment, les tramitacions acabades que registren amb SISTRA1 no permeten l'obtenció fàcil del justificant de registre.

Es proposa fer ús de la crida "obtenerJustificante" de l'API de REGWEB. En cas de que la crida sigui síncrona i es prevegi que tardi més d'1 segon, mostrar un diàleg de confirmació per a l'usuari, que indiqui que l'obtenció del justificant pot tardar una estona.

**Comment by mgonzalez-fundaciobit** [comment]
El que s'ha fet es posar un botó per generar el  justificant en cas de que no estigui generat, com que la cridada és sincrona i tarda una estona, s'ha posat un feedback mentre es genera. Un pic generat mostra el botó per descarregar-s'ho.

**Comment by mgonzalez-fundaciobit** [comment]
S'ha decidit que carpeta pugui generar el justificant en el cas que no estigui generat, això suposa que s'ha d'afegir el rol RWE_WS_CIUDADANO al mètode obtenerJustificant de REGWEB3 per poder-ho invocar des de Carpeta. 
Per part de Regweb3 ja s'ha afegit pero entram en un problema de concepte i permisos a regweb3 que estan estudiant com fer-ho.
En tenir una solució, se faràn els canvis oportuns.

**Comment by mgonzalez-fundaciobit** [comment]
Al final s'ha decidit que per generar un justificant amb el mètode (obtenerJustificante) no es necessita el permís de modificar_registre i ara ja es poden generar justificants amb el ROL RWE_WS_CIUDADANO.
