### ISSUE TITLE
Mostratge de notificacions i comunicacions del ciutadà

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#220]
Es proposa la creació d'un nou apartat dins la pantalla inicial de CARPETA, com es pot veure a CARPETA 0.1 que permeti obtenir les notificacions i les comunicacions del ciutadà.

![image](https://user-images.githubusercontent.com/44995350/98084605-596c9b80-1e7c-11eb-8485-15baf9056036.png)

![image](https://user-images.githubusercontent.com/44995350/98084622-5ffb1300-1e7c-11eb-9814-f5958e3fcb0f.png)

Al subapartat de "Notificacions", es redirigirà a la Carpeta Ciudadana de l'Estat (https://sede.administracion.gob.es/carpeta/clave.htm?expired=s) i a "Altres comunicacions" s'hauran d'obtenir les notificacions i comunicacions provinents de SISTRA1 (veure "obtenerElementosExpediente" de tipus COMUNICACION i NOTIFICACION) i les provinents d'una integració amb l'API de NOTIB, actualment en procés de desenvolupament.

**Comment by scalafat-dgtic** [comment]
API de NOTIB ja disponible. Per veure més informació de la seva integració amb CARPETA: https://github.com/GovernIB/notib/blob/notib-1.1.6/doc/NOTIB_carpeta.odt

**Comment by scalafat-dgtic** [comment]
Com s'ha proposat a #221, es dividiria aquest issue en dues fases:
- 1a fase: Que l'apartat de "Altres comunicacions" només obtengui les notificacions i comunicacions de Sistra1 (veure 2.2 del #231). (per febrer de 2021)
- 2a fase: Notificacions i comunicacions de Sistra1 + les comunicacions/notificacions provinents de la integració amb API de NOTIB (a partir de febrer de 2021)

**Comment by jpernia-fundaciobit** [comment]
Té tots els issues fets.
