### ISSUE TITLE
Back: Eliminar Menú Inici.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#223]
Depèn de "Millores en el codi del BACK #287"

Eliminar el Menu d'Inici i la pàgina de presentació s'ha de moure a Configuració.

**Comment by jagarcia-fundaciobit** [comment]
S'ha eliminat el menú d'inici i s'ha mogut la opció de "Inici" que hi havia dins del menú Rols a sobre la opció de menú Configuració dins el menú dels 3 puntets. S'ha renombrat a "Sobre Carpeta".
