### ISSUE TITLE
Revisar la pèrdua de sessió del Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#226]
Depèn de Millores en la UI del Front #246
S. Calafat: Cada X temps, me treu de la sessió sense cap missatge aparent. Hi ha algun tipus de Timeout? Si és així, estaria bé tenir un missatge d'alerta o notificació de que s'ha perdut la sessió.

**Comment by jpernia-fundaciobit** [comment]
S'ha posat una sessió de 30 minuts. 30 segons abans d'expirar avisa a l'usuari si vol renovar-la. Sinó, surt de la part autenticada i expira la sessió.
