### ISSUE TITLE
Revisar Visualització Mòbil del Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#227]
Depèn de "Millores en el Front #289"

S. Calafat: També s'ha de revisar com es veu en dispositius mòbils (p.ex: redimensionar logo GOIB lateral).

Ja existeix issue: #64

**Comment by jpernia-fundaciobit** [comment]
S'han revisat capçaleres, peus i varis continguts amb "Responsinator". Quan sigui possible tenir una versió de Carpeta accessibles des de l'exterior, es comprovarà amb diversos dispositius físics.

**Comment by jpernia-fundaciobit** [comment]
S'han afegit estils per veure als dispositius mòbils. S'ha comprovat amb l'opció "Toggle dive toolbar" de Chrome.
