### ISSUE TITLE
Front: menú ràpid

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#228]
Depèn de Millores en la UI del Front #246

Incorporació d'un menú ràpid amb accés directe a totes les funcionalitats de CARPETA, com fa la CARPETA-ESTADO. Aquest menú pot/hauria de ser dinàmic, segons les integracions realitzades.

![imatge](https://user-images.githubusercontent.com/17084256/98541832-531d5b80-2290-11eb-9e7e-5fcd574d01e3.png)

![imatge](https://user-images.githubusercontent.com/17084256/98541971-82cc6380-2290-11eb-954b-c2814ca68c98.png)

**Comment by jpernia-fundaciobit** [comment]
S'ha afegit el menú ràpid només a la part autenticada del front perquè a la pública quasi no hi ha informació per mostrar.
De moment s'han creat 3 apartats al menú:
- Les meves gestions: conté els plugins
- Accessibilitat
- Les meves dades

**Comment by scalafat-dgtic** [comment]
![imagen](https://user-images.githubusercontent.com/44995350/101624703-9f3bf700-3a1a-11eb-9675-4988c2ba0a9f.png)

- Treure Accessibilitat (la informació ja estarà disponible al DIRECTORI)
- Separar "Les meves gestions" i posar cada plugin com una opció més del menú ràpid (ex: veure captura següent)

![imagen](https://user-images.githubusercontent.com/44995350/101625011-1d000280-3a1b-11eb-92d1-5404915e6ed3.png)

D'aquesta manera, posam les opcions més interessants molt visibles. Quan el nombre de funcionalitats sigui molt més elevat ja ho reorganitzarem.

**Comment by jpernia-fundaciobit** [comment]
S'ha llevat l'accés a Accessibilitat del menú ràpid.
S'ha llevat el botó que agrupa els plugins del menú ràpid.
S'han afegit directament els plugins al menú ràpid.
