### ISSUE TITLE
"Miga de pan" correcte al seleccionar Plugins

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#229]
Depèn de "Millores en el Front #289"

Al "Breadcrumb" que surti un nom descriptiu enlloc de "Plugin d'Entitat". Configurable des de Backoffice?

També que hi hagués la opció de canviar tots els textos que apareixen a dins de la pantalla del plugin. Per exemple, en aquest cas, poder eliminar "SENSE ACABAR" de l'usuari perquè es mostrarien tots els tràmits telemàtics (pendents i finalitzats)

![imatge](https://user-images.githubusercontent.com/17084256/98542092-adb6b780-2290-11eb-874d-19af3d520c9b.png)

**Comment by jpernia-fundaciobit** [comment]
S'ha solventat el primer punt, el de mostrar el nom del Plugin a la Motlla de Pa.

![image](https://user-images.githubusercontent.com/17266896/103873610-5e460980-50d0-11eb-87d1-f04899688c73.png)

Falta fer el segon punt, de poder canviar els textos dels plugins. Ara mostra els textos definits als missatges.properties del plugin, per poder modificar s'hauria de definir com poder fer-lo.

**Comment by jagarcia-fundaciobit** [comment]
Tanc la issue. He creat una de nova per la segona part que queda pendent. #341
