### ISSUE TITLE
Refactorització de  tràmits telemàtics mostrats

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#231]
Depèn de  "Millores en el codi del BACK #245 "
Depèn de  "Millorar Dades Compartides de Usuari obtingudes de LoginIB #197"

S. Calafat: Dins del llistat de tràmits telemàtics mostrats:

   1 No es reprenen els tràmits de SISTRA2 (#197)
   2 No han d'aparèixer els tràmits de SISTRA1 de:
       2.1  REGISTRO (perquè són registres que han d'aparèixer dins el plugin de REGWEB)
       2.2 COMUNICACION i NOTIFICACION (perquè han d'aparèixer a l'apartat de "Les meves notificacions", integració futura amb NOTIB - #220 )
   3 El tràmit de PREREGISTRO y PREENVIO haurien d'aparèixer com a "Pendents" perquè els hi falta una passa presencial i, per tant, no estan finalitzats. A Carpeta 0.1 tenim el següent modal, quan es clicka a damunt un d'ells

![imatge](https://user-images.githubusercontent.com/17084256/98543869-6847b980-2293-11eb-916c-384ae64bf456.png)

**Comment by jagarcia-fundaciobit** [comment]
El punt 1 no es pot fer fins que no acabem aquesta: 
Millorar Dades Compartides de Usuari obtingudes de LoginIB #197

**Comment by jagarcia-fundaciobit** [comment]
S'han fet els següents canvis: 
- Filtratge dels tipus de tràmits que mostra el plugin per tal de que no es mostrin els tràmits de tipus: REGISTRO, COMUNICACION i NOTIFICACION
- Creació d'un modal que apareix als tràmits pendents o no finalitzats. Veure imatge adjunta.

![imagen](https://user-images.githubusercontent.com/70194276/101782443-498a4c00-3af9-11eb-8394-fc1540fb93c9.png)

**Comment by jagarcia-fundaciobit** [comment]
Només queda pendent la resolució del punt 1 que alhora està pendent de la resolució de la issue "Millorar Dades Compartides de Usuari obtingudes de LoginIB #197"

**Comment by jagarcia-fundaciobit** [comment]
Fet el punt 1. Ja surten els tràmits de Sistra 2 i si están pendents es poden reprendre.

**Comment by jagarcia-fundaciobit** [comment]
Correcció: el modal nomès ha de sortir pels tràmits pendents de Sistra1. No pels de Sistra2.
