### ISSUE TITLE
Problemes amb persistence.xml i Hibernate

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#232]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, ...) #194 "

Pareix ser que amb els canvis dels fitxers de propietats algunes característiques del fitxer persistence.xml han deixat de funcionar:
(1) el jpa-datasource: revisar com realment els estandards defineixen com ha de ser
(2)"hibernate.dialect": revisar el ProjecteBase d'on obté i assigna el valor d'aquesta propietat
(3) També  revisar com convertir es.caib.carpeta.hibernate.show_sql=false i es.caib.carpeta.hibernate.format_sql=false a propietats HIBERNATE (Revisar el initservlet de PortaFIB back com ho fa)

En el persistence.xml:

----------------------------------------------------------------------------------
<persistence-unit name="carpetaPU" transaction-type="JTA">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>

        <jta-data-source>**java:/es.caib.carpeta.db**</jta-data-source>
[...]
    <properties>
         **<property name="hibernate.dialect" value="org.hibernate.dialect.Oracle12cDialect" />**
	Es veu que no agafava el valor de la propietat correctament i vaig d'haver de posar el valor a pinyó fix
          
          <property name="hibernate.query.substitutions" value="${es.caib.carpeta.hibernate.query.substitutions}"/>
    </properties>
</persistence-unit>
----------------------------------------------------------------------------------
Hauríem de poder incloure, també, les següents propietats dins CARPETA:

es.caib.carpeta.hibernate.show_sql=false
es.caib.carpeta.hibernate.format_sql=false

Salutacions,

Simó Calafat Garcés

-----------------------------

EL problema que hibernate-dialect no s'obtengui bé per Oracle és un bug que es soluciona posant el darrer  patch al JBoss 7.2.

**Comment by jagarcia-fundaciobit** [comment]
Solucionat. S'ha definit una clase CustomHibernatePersistenceProvider que exten de HibernatePersistenceProvider, l'anterior provider definit al fitxer de persistence.xml. 

Aquesta nova clase, llegueix el fitxer de propietats carpeta.properties i carpeta.system.properties i agafa aquelles propietats que comencen per es.caib.carpeta.hibernate i les passa a Hibernate. 

D'aquesta forma, es poden definir qualsevol propietat de configuració d'hibernate al fitxer de carpeta.properties.

Hem creat dins el fitxer carpeta.properties aquestes dues propietats: 
es.caib.carpeta.hibernate.show_sql=false
es.caib.carpeta.hibernate.format_sql=false
