### ISSUE TITLE
Revisió de propietats duplicades als fitxers de properties

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/carpeta#236]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, ...) #194"

Els fitxers de "carpeta.properties" i "carpeta.system.properties" tenen propietats que es repeteixen. Per exemple, totes les de "carpeta.system.properties" es troben a "carpeta.properties".

    https://github.com/GovernIB/carpeta/blob/carpeta-1.1/scripts/config/carpeta.properties
    https://github.com/GovernIB/carpeta/blob/carpeta-1.1/scripts/config/carpeta.system.properties

**Comment by anadal-fundaciobit** [comment]
Ja s'ha arreglat lo de carpeta.properties i carpeta.system.properties i s'ha commitat aquí: https://github.com/GovernIB/carpeta/commit/d19a2d9e2fb25f27d6b0f9111879abca807e349c
