### ISSUE TITLE
URL, password i username de login s'ha de moure a  carpeta.system.properties

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#237]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, ...) #194"

Dins "carpeta.system.properties" li hauríem d'afegir les corresponents propietats de LoginIB, en teoria:

es.caib.carpeta.loginib.url=
es.caib.carpeta.loginib.user=
es.caib.carpeta.loginib.pass=

Això farà que allà on es consulten aquestes propietats, s'hauran de mesclar les de carpeta.properties i les de carpeta.system.properties

**Comment by jagarcia-fundaciobit** [comment]
S'han canviat les propietats al fitxer de carpeta.system.properties. 
El merge ja estava fet d'una altra issue (https://github.com/GovernIB/carpeta/issues/120). 
S'ha comprovat que el funcionament i que el plugin agafa correctament les dades.
