### ISSUE TITLE
Dialeg d'Ajuda amb informació de l'Entitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#240]
Depèn de Millores en el codi del BACK #245

L'enllaç de "Necessitau Ajuda?" del peu de la pàgina a la dreta només ha de contenir 2 punts: 
                * Suport Tècnic: goverdigital.carpeta@fundaciobit.org
                * Suport Front i Back: scalafat@fundaciobit.org

A més estaria bé que Necessitau Ajuda, estigui davall del Logo del Peu.

![imatge](https://user-images.githubusercontent.com/17084256/100093718-366c5080-2e58-11eb-8236-1a1cea3d6f64.png)

**Comment by mgonzalez-fundaciobit** [comment]
Fet, s'ha reorganitzat l'enllaç i s'ha modificat l'info del modal.
