### ISSUE TITLE
Usuari sense rols  CAR_ADMIN ni CAR_SUPER

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#241]
Depèn de "Millores en el codi del BACK #338"

Pareix ser que JBoss 7.2 es menja els usuaris que s'autentiquen però no tenen cap ROL dels esperats: CAR_ADMIN i CAR_SUPER.
Revisar la pantalla de redirecció quan això passa. Enviar-ho a una pantalla "Full View " (de tiles) i mostrar un avis.

**Comment by jagarcia-fundaciobit** [comment]
Solucionat. Quan l'usuari que es conecta no té cap rol asignat, se li mostra el següent avis:

![imagen](https://user-images.githubusercontent.com/70194276/108485969-d3932580-729d-11eb-9ab7-e2b9a3e09c3a.png)
