### ISSUE TITLE
Centralitzar totes les Cridades a EJBs de AuthenticationSuccessListener

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#249]
Depèn de  "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #288"

Actualment es creen 6 EJB durant el post procés d'autenticació(AuthenticationSuccessListener). El millor seria que totes les cridades necessàries es centralitzessin en un AuthenticationLogicaEJB i evitar tanta cridada a EjBmanager.

![imatge](https://user-images.githubusercontent.com/17084256/100101298-586ad080-2e62-11eb-9d18-c015c0926ac8.png)

![imatge](https://user-images.githubusercontent.com/17084256/100101335-67ea1980-2e62-11eb-9731-d7486289bb08.png)

**Comment by mgonzalez-fundaciobit** [comment]
Com indica l'ssue s'ha creat un ùnic EJB(AuthenticationLogicaEJB) que referencia als altres EJBs.
