### ISSUE TITLE
Fer que I18NException estengui de Exception

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#250]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, ...) #244"

Fer que I18NException estengui de Exception enlloc de Throwable ja que els EJBs aquest darrer tipus d'excepció no la gestionen correctament.

**Comment by jagarcia-fundaciobit** [comment]
Corregit. Hem provocat una excepció a un EJB i hem comparat els resultats. Amb Throwable sortia un error del tipus: 
java.lang.reflect.UndeclaredThrowableException: INV000001: Undeclared Throwable thrown

mentre que amb Exception es visualitza el missatge del codi d'excepció indicat.
org.fundaciobit.genapp.common.i18n.I18NException: Exception TEST 

Veure commit: 
https://github.com/GovernIB/genapp/commit/e4cd6c1abeac31dafa9e1fecad751d686869a28a
