### ISSUE TITLE
Apareix parentesis en capçalera del back

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#251]
Depèn de "Millores en el codi del BACK #245 "

Quan l'usuari no està assignat a cap entitat, llavors apareixen uns parentesis en la capçalera de la pàgina (Devora la paraula CARPETA)

![imatge](https://user-images.githubusercontent.com/17084256/100211126-0aaaa280-2f0c-11eb-9a92-c7aaf8dcbe8f.png)

**Comment by jagarcia-fundaciobit** [comment]
Corregit. Encara que el codi de l'entitat és obligatori, en el cas que fos buit, no sortirien els parentesis.
