### ISSUE TITLE
Moure-se entre fronts de diferents entitats 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#254]
Depèn de "Millores en la UI del Front #246"

Actualment dins del front surt una llista de les entitats disponibles i poder saltar al front d'aquestes altres entitats. 
Fer que aquest llistat surti segons el valor booleà d'una propietat global (de BBDD).

Seria alguna cosa com: es.caib.carpeta.canviardefront=true

**Comment by jpernia-fundaciobit** [comment]
S'ha afegit l'obtenció de la variable global "es.caib.carpeta.canviardefront" i, si el seu valor és 'true' i hi ha més d'una entitat creada i activa, es mostra l'opció de canviarper poder canviar d'entitat al menú.
Aquesta Propietat global està a nivell de superadministrador.
