### ISSUE TITLE
Millores de persistence.xml. Part 2.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#257]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, ...) #244"

En el issue "Problemes amb persistence.xml i Hibernate #232" es varen fer canvis al  persistence.xml: https://github.com/GovernIB/carpeta/commit/a9de896c869b348651e83551de8a8ec3030832d9#diff-c12257825793be4d7f0cc47f82a5b39af4f8a5d8108d0978ceb6198bfe1f6fd4

El problema és que aquest fitxer és generat i cada vegada que s'executa el GenApp el sobreescriu.

(1) Afegir aquesta funcionalitat de persistence.xml al GenApp així com la classe CustomHibernatePersistenceProvider
(2) Afegir comentari damunt de persistence.xml indicant que aquests fitxer és auto generat
(3) Al CustomHibernatePersistenceProvider separar les porpietats de sistema de les propietats de fitxers: De les propietats de sistema s'han de cercar properties hibernate.* i de les propietats de fitxers s'han de cercar Propietats "es.caib.carpeta.hibernate. *"

**Comment by jagarcia-fundaciobit** [comment]
S'ha inclòs les modificacions per crear la clase CustomHibernatePersistenceProvider i que es llegeixin les propietats del projecte i del sistema quan es fa el desplegament. 

D'aquesta forma, es poden definir propietats del sistema dins el fitxer de carpeta.system.properties o carpeta.properties i es tinguin en compte alhora de desplegar l'aplicació. 

Veure commits del projecte de genapp: 
https://github.com/GovernIB/genapp/commit/b3ee303194afc6295d145a43ff5d412f3604bffb
https://github.com/GovernIB/genapp/commit/52f9c84839e611a0054d6c14fc244c838ee70d1b
