### ISSUE TITLE
Cercar referències a CAIB a la pàgina del front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#259]
Depèn de "Millores en la UI del Front #246"

Cercar referències a CAIB a la pàgina del front

Per exemple de forma ràpida he trobat:
(1) Que el títol posa "Benvingut a la Carpeta Ciutadana del **Govern de les Illes Balears**"
(2) Que el boto titulat DIRECTORI va a www.caib.es

Cercar alguna forma per extreure aquest contingut a la configuració d'Entitat o d'Enllaços.

![image](https://user-images.githubusercontent.com/17084256/100322892-35a4fd00-2fc5-11eb-81a3-82cefd7bec0d.png)

**Comment by jpernia-fundaciobit** [comment]
1- Pel botó de directori a la barra del menú s'ha fet un tipus nou d'enllaç al backoffice, "Front - Menú Barra" i s'haurà de donar d'alta a l'entitat, amb la url i la icona que es vulgui. Es podrà posar el nom i icona que es vulgui mostrar. Per tant, es podrà posar qualsevol enllaç aquí.
Després, segons si està definit o no a l'entitat, es mostrarà a la barra del menú.

2- S'ha fet el mateix per la "Cerca Avançada" del Menú Deslliçant. S'ha creat el tipus d'Enllaç "Front - Menú Deslliçant". Així es podran crear enllaços al menú deslliçant de la dreta.

3- Per gestionar el nom de l'entitat que apareix a la pàgina d'inici pública, s'ha fet una cridada REST per obtenir el nom de l'entitat en l'idioma actiu. Després s'ha afegit al títol de la pàgina.

4- Segons han indicat des de la DGMAD, no es toca el text on diu el que es pot fer a dins Carpeta.
