### ISSUE TITLE
FRONT: Diàleg d'ajuda al Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#261]
Depèn de "Millores en la UI del Front #246"

S'ha de tornar a incloure al front un diàleg d'ajuda que tindrà com a màxim els següents camps, obtinguts de l'entitat:
      * suport email
      * suport web
      * suport telèfon
      * Preguntes Freqüents (FAQ)
      * Queixes i suggeriments (QSSI) 
      * Problemes amb autenticació

Tots els camp són opcionals.
(1) Els tres darrers camps s'han d'incloure a la BBDD  **(FET !!!)**
(2) S'ha de fer una consulta REST per retornar-los  **(FET !!! veure captura)**
(3) S'ha de crear un component REACT per mostrar-ho.

![imatge](https://user-images.githubusercontent.com/17084256/100730636-961faa00-33ca-11eb-9311-be346678e62c.png)

![image](https://user-images.githubusercontent.com/17084256/100448092-0f10c000-30b2-11eb-9dd2-08ee8f42294d.png)

**Comment by jpernia-fundaciobit** [comment]
(3) S'ha de crear un component REACT per mostrar-ho. (Fet!)

S'ha creat un component nou que mostra les dades de suport a la zona de contingut.

**Comment by scalafat-dgtic** [comment]
![imagen](https://user-images.githubusercontent.com/44995350/101623124-44a19b80-3a18-11eb-9d1a-621dacbcee12.png)

- Canviar títol de "DADES DE CONTACTE" per "Necessites ajuda?"
- Canviar els texts que apareixen per defecte pel que es mostra a CARPETA-0. (deixant els enllaços a les parts corresponents, com es pot veure a la imatge inferior). Les preguntes freqüents i la consulta tècnica ha de tenir format de URL; el correu de suport, format de correu; el telèfon i problemes d'autenticació han de ser telèfons.

![imagen](https://user-images.githubusercontent.com/44995350/101624344-1f159180-3a1a-11eb-8bda-3f217032e350.png)

**Comment by jpernia-fundaciobit** [comment]
S'ha passat la finestra de dades de suport a un modal.
S'han adaptat els missatges de cada tipus de dada.
S'ha canviat el títul del modal.

**Comment by jpernia-fundaciobit** [comment]
S'han creat tipus de dades de suport. 
S'han millorat els missatges d'ajuda, personalitzant-los segons el tipus de dada de suport que és.
