### ISSUE TITLE
NullPointer  al editar alguns Logs

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#262]
Depèn de "Millores en el codi del BACK #245"

Segons Simó apareixen NullPointers al veure alguns Logs

![imatge](https://user-images.githubusercontent.com/17084256/100590494-c6951480-32f4-11eb-8e4b-4d2ff0b31a6f.png)

**Comment by mgonzalez-fundaciobit** [comment]
Corregit.
