### ISSUE TITLE
Represa de tramitació anònima

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#263]
Depèn de "Integració amb SISTRA1 #129"

A Sistra1 existeix l'opció de realitzar tramitacions de manera anònima. Es demana incloure l'opció de reprendre tramitacions anònimes, tal i com fa Carpeta 0. La represa de tramitació es fa a través d'una clau de tramitació proporcionat per S1.

![image](https://user-images.githubusercontent.com/44995350/100609609-9490ac00-330e-11eb-9e42-eaa8f9be831f.png)

![image](https://user-images.githubusercontent.com/44995350/100609644-9eb2aa80-330e-11eb-89c4-6b9b5e40d621.png)

El mètode per obtenir la url de represa del tràmit anònim es troba a l'API de Sistra1

![image](https://user-images.githubusercontent.com/44995350/100609790-e0dbec00-330e-11eb-9599-d133f7ca57d6.png)

Aquesta funcionalitat es pot inserir a la pantalla inicial de CARPETA, només en el cas de CAIB, en el mateix lloc de CARPETA 0.

![image](https://user-images.githubusercontent.com/44995350/100609936-200a3d00-330f-11eb-83e4-968dcdbe738c.png)

**Comment by jagarcia-fundaciobit** [comment]
S'ha afegit el missatge a la página principal.

![imagen](https://user-images.githubusercontent.com/70194276/105013268-5d519800-5a3f-11eb-9e1e-a21ab852a73d.png)

Quan es clica s'obri un modal per introduir el codi de tràmit: 

![imagen](https://user-images.githubusercontent.com/70194276/105013506-9db11600-5a3f-11eb-9923-89dc552a6fd9.png)

I una vegada introduit, si existeix, s'obri la continuació del tràmit a una altra pestanya. Si és incorrecte, es mostra un missatge d'error.

![imagen](https://user-images.githubusercontent.com/70194276/105016377-dacad780-5a42-11eb-8fed-6bbd4dfbcc79.png)

**Comment by jagarcia-fundaciobit** [comment]
S'ha indicat al Document de migració que es necessari tenir configurades les dades de connexió a SISTRA1 al fitxer de carpeta.system.properties.
