### ISSUE TITLE
Revisar que retorna LoginInfo.getEntitat() quan s'autentica un usuari amb els Rols CAR_SUPER i CAR_ADMIN

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/carpeta#264]
Depèn de "Millores en el codi del BACK #480"

Quan ens autenticam al backoffice amb un usuari que té els 2 rols (CAR_SUPER i CAR_ADMIN)  i a més l'usuari està relacionat amb una entitat, el LoginInfo.getEntitat() retorna l'entitat amb la que està relacionada. Per tant, quan es crea el log i l'auditoria, pareix que l'usuari que s'ha autenticat és només un Administrador d'Entitat, quan realment es pot haver autenticat només com a Super Administrador que no te cap entitat associada. 

Es mostra el log en questió.
![image](https://user-images.githubusercontent.com/17267873/100866017-62ab5100-3498-11eb-8a07-d4ca20f15a53.png)

**Comment by jpernia-fundaciobit** [comment]
Al final, acordat amb la DGMAD, s'ha afegit una entrada a auditories cada vegada que es canvia de rol i d'entitat. Així es veuen els accessos d'un usuari amb cada rol i dins cada entitat.
Fet.
