### ISSUE TITLE
Gestió de darrera entitat si som Administrador d'Entitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#265]
Depèn de "Millores en el codi del BACK #338"

Gestió de darrera entitat si som Administrador d'Entitat

(a) Crear un nova entitat fundació tal i com s'ha creat la de CAIB: script sql i fitxers
(b)  Si som Administrador d'Entitat, guardar la darrera entitat a la que s'ha entrat dins de BBDD. 
(c) Al fer login, assignar l'entitat de Darrera Entitat

**Comment by jagarcia-fundaciobit** [comment]
S'ha programada la nova funcionalitat. Es guarda la darrera entitat que ha utilitzat l'usuari i quan es fa login de nou, s'obri amb aquesta entitat. 

També s'ha creat un script per crear l'entitat la Fundació BIT  i s'han pujat els arxius referents a logos e icones que s'utilitzen.
