### ISSUE TITLE
Reprendre tràmits de SISTRA2 segons el nivell de QAA autenticat

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#27]
Es demana que es puguin reprendre els tràmits de SISTRA2 (que s'han fet amb un nivell de QAA) només amb el nivell superior de QAA amb el qual m'he autenticat dins CARPETA. 
**Exemples**:
- Entram a CARPETA amb nivell de **QAA = 1**, puc consultar tots els tràmits pendents però puc reprendre només aquells que s'han realitzat amb nivell de **QAA <= 1**. (En aquest cas, només 1). Si vull reprendre un tràmit fet amb nivell de QAA > 1, llavors m'ha de tornar a sortir la pantalla d'autenticació de Cl@ve per autenticar-me a un nivell igual o superior (QAA >1) en el que es demana per poder reprendre el tràmit.
- Entram a CARPETA amb nivell de **QAA = 3**, puc consultar i reprendre tots els tràmits sense cap problema perquè ens trobam amb el nivell d'autenticació més alt.

Per fer-ho, s'ha d'incorporar a la cridada per obtenir tots els tràmits, obligatòriament, el nivell de QAA (potser també el mètode d'autenticació).

**Comment by earrivi-fundaciobit** [comment]
Ahora se incluye en la llamada a recuperar los tramites pendientes de Sistra2 el nivel Qaa retornado por LoginIb.
