### ISSUE TITLE
Fer els mètodes rest per retornar la informació dels accessos al portal de dades obertes

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/carpeta#275]
Depèn de "Integració amb Portal Dades Obertes #114"

Com a desenvolupador vull retornar les dades dels accessos via rest.

**Comment by jagarcia-fundaciobit** [comment]
S'ha creat la següent ruta pública al carpetafront per tal d'obtenir un JSON amb les dades referent als accesos: 
/carpetafront/dadesobertes/accesos/?inici=2020-12-19&fi=2020-12-22&entitat=caib

Els paràmetres que reb per GET són: data inici (inici) , data fi (fi) i codi entitat (entitat). 

Si no s'indiquen dates d'inici i  de fi, per defecte retorna les dades del darrer mes (30 dies). 
Si no s'indica el codi d'entitat, mira al sistema si existeix una propietat global amb la clau:  es.caib.carpeta.defaultentitycode
Si existeix defaultentitycode, agafa aquest quan no s'indica per GET. 
Si no s'indica per GET i tampoc existeix aquesta propietat global, retorna un error 400 Bad Request.

Les dades que retorn són les següents:

![imagen](https://user-images.githubusercontent.com/70194276/102877820-a534cd80-4447-11eb-9bd5-e3855ad9ac83.png)

**Comment by jagarcia-fundaciobit** [comment]
Modificat perqué retorni el codi d'entitat i el tipus d'accés en comptes de les corresponents ids.

![imagen](https://user-images.githubusercontent.com/70194276/102883468-5c354700-4450-11eb-8a8b-3658185ed5f1.png)
