### ISSUE TITLE
Gestión de avisos de mantenimiento

### ISSUE THREAD

**Issue by earrivi-fundaciobit** [GovernIB/carpeta#28]
Como: Administrador de la aplicación
Quiero: Crear avisos temporales de incidencias en terceras aplicaciones
Para: Avisar al usuario final de posibles incidencias programadas.

**Comment by anadal-fundaciobit** [comment]
Falten els avisos del FRONT:
       -  PRE LOGIN
       - POST-LOGIN
       - GLOBAL FRONT
      - Per PLUGIN

Per ara farem només el de Per Plugin, la resta es passaran a 1.1.5
