### ISSUE TITLE
Millorar presentació Plugin de Notificacions

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#280]
Depèn de "Millores en el Front #289"

Pareix que hi ha algun tipus de problema amb els estils, ja que com es pot observar, el que s'ha fet (imatge 1) no es correspon gràficament al que hi ha a carpeta 0.1 (imatge 2)

![imatge](https://user-images.githubusercontent.com/17084256/102065334-b737c000-3df8-11eb-9628-8d527fc5faf6.png)

![imatge](https://user-images.githubusercontent.com/17084256/102065363-bf8ffb00-3df8-11eb-8433-f1e057f65bf4.png)

**Comment by jagarcia-fundaciobit** [comment]
Fet. He afegit els estils necessaris dins la fulla d'estils del plugin. 

![imagen](https://user-images.githubusercontent.com/70194276/102997869-59a52100-4526-11eb-8549-b8f10999a0cd.png)
