### ISSUE TITLE
Anexos REGWEB3: Obtener los anexos completos

### ISSUE THREAD

**Issue by earrivi-fundaciobit** [GovernIB/carpeta#29]
Depèn de Integració amb REGWEB3 #130
Como: Usuario 
Quiero: Obtener los anexos de un asiento registral
Para: Poder descargarlos

**Comment by anadal-fundaciobit** [comment]
Depen de Integració amb REGWEB3 #130

**Comment by anadal-fundaciobit** [comment]
Esta pendent de que dins de RegWeb3 es facin els mètodes per obtenir els anexes.

**Comment by anadal-fundaciobit** [comment]
N'Eduardo l'altre dia ens va comentar que ja hi havia mètodes WS implementats.
