### ISSUE TITLE
Millores en Dades Obertes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#293]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #288"

SCALAFAT
 Dos detalls de Dades Obertes.

   (1) Les dates, a la consulta, no són inclusives. Si pos "fi" el dia d'avui, no me surten els accessos d'avui. Les podem fer inclusives?
   (2) Quan es retorna un accés a CARPETA (no plugin), el camp pluginid no es retorna. Això pot causar problemes a Socrata, la plataforma de Dades Obertes. Per tant, propòs que enlloc d'enviar el camp "pluginid" s'envii "plugin" amb el valor de la descripció del mateix. En el cas d'un accés a CARPETA que sigui "Login" o "LoginIB". Pentura millor LoginIB perquè és cert que el faríem servir per autenticar-mos.

**Comment by jagarcia-fundaciobit** [comment]
S'ha realitzat els canvis proposats: 
- Dates inclusives
- En cas d'accés, retorna LoginIB si es CAIB (ho revisa de la propietat del sistema), en cas contrari, només Login.
- Canvi del camp pluginid per plugin. Per això, s'ha afegit un nou paràmetre "idioma" que pren el valor de ca, es, en. Si no es passa aquest paràmetre, agafa el defaultlanguage de l'aplicació i en cas que no estigui definit, per defecte català ("ca").  

![imagen](https://user-images.githubusercontent.com/70194276/103659064-4b1a2900-4f6c-11eb-992c-24d8f1ae90e4.png)

**Comment by mgonzalez-fundaciobit** [comment]
S'ha de canviar la nomenclatura dels camps nivellSeguretat i autenticacio

NivellSeguretat -> Mètode Autenticació
Autenticació -> QAA

**Comment by mgonzalez-fundaciobit** [comment]
Fet i committat a l'issue Refactorització d'Accesos #308
