### ISSUE TITLE
No funciona el desplegable de wrapp dels components TextArea

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#295]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #340"

No funciona el desplegable de wrapp dels components TextArea

![imatge](https://user-images.githubusercontent.com/17084256/103641412-008bb300-4f52-11eb-85c4-3aa9406a9a39.png)

**Comment by jagarcia-fundaciobit** [comment]
Solucionat.
