### ISSUE TITLE
Nou camp icona per Plugin

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#297]
Depèn de "Millores en el codi del BACK #287"

(1) Afegir en la taula Plugin un nou camp opcional de tipus fitxer que representaria la icona del Plugin (recordar que si no es defineix s'utilitza la icona per defecte del plugin i sinó es segueix la política definida a #282)
(2) Modificar la consulta de icones dels plugin en el Front per primer consultar si el plugin de bbdd té definit un logo.

**Comment by jagarcia-fundaciobit** [comment]
S'ha creat un nou camp opcional a la taula de plugins per tal de que l'usuari pugui pujar un logo. 

![imagen](https://user-images.githubusercontent.com/70194276/104465454-57c5ff00-55b4-11eb-8348-f24107e69246.png)

Si no es puja cap logo, segueix la lògica indicada a https://github.com/GovernIB/carpeta/issues/282
