### ISSUE TITLE
Millora missatge de sessió expirada

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#299]
Depèn de "Millores en el Front #289"

En el missatge de "sessió expirada"

- No s'actualitza el comptador d'expiració. Encara que estiguis fent coses, als X minuts te surt el missatge d'expiració. Hauria de ser si fa X minuts **d'inactivitat**. (Ens ha passat fent la revisió funcional)
- Quan expira la sessió es queda en un estat 'fantasma' on no apareixen molts dels elements en el frontal, especialment en el footer a l'esquerra on apareix un 'null'.

**Comment by scalafat-dgtic** [comment]
En referència a l'estat "fantasma" en què es queda. Pas imatge de com es veu quan apareix el missatge de sessió expirada i es dona l'OK per tancar el modal

![image](https://user-images.githubusercontent.com/44995350/105335994-0089e500-5bd9-11eb-8f3b-f916096f53c9.png)

**Comment by jpernia-fundaciobit** [comment]
S'ha modificat per a que es rinicien els comptadors al canviar de component.
S'ha modificat per a que, al acabar la sessió, mostri les dades de l'entitat a la que s'estava.

**Comment by jpernia-fundaciobit** [comment]
Es torna a obrir perquè segueix donant un comportament extrany a la CAIB, que a la Fundació, en local, no s'ha pogut replicar.

**Comment by jpernia-fundaciobit** [comment]
S'ha detectat un comportament que podria coincidir amb el descrit. Si el front ha expirat la sessió i se reinicia el jboss, i després es pitja sobre el quadre d'expiració de sessió, aquest intenta recarregar la pàgina d'inici i, com que s'ha perdut la sessió al iniciar el jboss, el front no carrega cap entitat.
Aquest cas no seria un error perquè hi juga un paper clau el reinici del jboss.

**Comment by jpernia-fundaciobit** [comment]
Pendent de veure si es pot reportar qualque casuística on es pugui reproduir aquest comportament.

**Comment by jpernia-fundaciobit** [comment]
Pujat el temps de sessió a 30 minuts, després de fer proves amb 1 minut i que pareix que no dóna problemes.

**Comment by jpernia-fundaciobit** [comment]
S'han fet proves amb 30 minuts i funciona correctament. L'estat "fantasma" també fa estona que no apareix.
