### ISSUE TITLE
Tancament de sessió - BACK

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#300]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #288"

En el backoffice, en voler tancar sessió, te tanca i te torna a entrar automàticament. D'aquesta manera no es permet mai deixar la sessió tancada.

![image](https://user-images.githubusercontent.com/44995350/104314358-99ce4280-54d9-11eb-97d9-9b652822cfa8.png)

**Comment by jagarcia-fundaciobit** [comment]
Solucionat. S'ha creat una classe que s'executa quan es fa logout. 

Aquesta classe implementa la interficie LogoutSuccessHandler i s'encarrega de fer un logout i invalidar la sessió actual. 

Es redirecciona automáticament a la pàgina d'entrada del back.
