### ISSUE TITLE
Millores generals a les taules del backoffice

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#301]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #288"

- Revisar que totes les taules estan ordenades per data més recent a data més antiga. (Auditories va de més antic a més recent, per exemple)
- L'agrupació d'elements de la taula només es desplega una vegada. Quan desplegues i tornes a plegar, no es pot tornar a desplegar.

**Comment by anadal-fundaciobit** [comment]
S'ha canviat la llibreria de Tree que era per Bootstrap 3 i s'han revisat els llistats per ordenar-los per data.
