### ISSUE TITLE
Administradors d'entitat han de poder veure els seus Logs, Accessos i Auditories

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#302]
Depèn de "Millores en el codi del BACK #287"

Estaria bé que l'usuari administrador d'Entitat pugués veure els seus logs, accessos i auditories filtrats per la seva entitat. D'aquesta manera, per exemple:
1. El SuperAdmin podria veure els logs, accessos i auditories de **totes** les entitats
2. El Admin d'entitat veure **només els seus**. (filtre per entitat)

**Comment by mgonzalez-fundaciobit** [comment]
Pendent d'en Simó

**Comment by mgonzalez-fundaciobit** [comment]
Fet, s'han afegit a més les noves opcions al menú d'inici.
