### ISSUE TITLE
Millores en la taula d'Accessos

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#303]
Depèn de "Millores en el codi del BACK #287"

A la taula d'Accessos es pot millorar el següent:
- Es podrien ampliar l'enregistrament amb les entrades a la HOME (login autenticat), ja que actualment només ho fa als plugins.
- Modificar el nom de les columnes "Nivell de seguretat" per "Mètode d'autenticació" i "Resultat Autenticació" per "QAA"

**Comment by mgonzalez-fundaciobit** [comment]
Tancam issue perque ja s'ha fet al issue Refactorització d'Accesos #308
