### ISSUE TITLE
Millores en la taula de Logs

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#305]
Depèn de "Millores en el codi del BACK #287"

A la taula de Logs s'han vist les següents millores:
- Permetre el filtratge per Entitat i per Plugin al desplegable de Agrupació.
- Avui dematí hem volgut inserir una entitat nova amb un logo en PNG i li ha sortit el següent error que NO ha estat enregistrat en els Logs (per si es vol valorar aquesta opció)
- Valoraria el mostratge/enregistrament **només** dels logs de tipus Error. No caldria mostrar constantment autenticació al FRONT/BACK ok, que emplena la BD amb informació redundant que ja tendríem a la taula Accessos o Auditoria.

**Comment by anadal-fundaciobit** [comment]
Solucionat:
  (1) Filtratge OK
  (2) Tots els errors d'Autenticació, de Formularis i No Controlats(els que arriben a error.jsp)  es guarden a logs.
  (3) Això ja no es feia.
