### ISSUE TITLE
Configuració d'idiomes

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#306]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #288"

Estaria bé tenir una opció per activar i desactivar els idiomes, ja sigui via properties o via BD. Per exemple, la versió en anglès no la necessitaríem, actualment, i ens obligaria a emplenar tots els camps de l'idioma. També hauríem de poder afegir-los de manera senzilla sense haver d'introduir grans canvis de codi

**Comment by anadal-fundaciobit** [comment]
Llest per la part de gestio i part web del Back. S'ha fet un issue per la part del Front.
