### ISSUE TITLE
Mostrar error al fallar autenticació de front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#309]
Depèn de "Millores en el Front #423"

(1) Quan comença el procés de Login en el Front, si es produeix un error, l'aplicació retorna al front sense donar cap avís. 
Estaria bé donar algun tipus d'avís. Joan, si vols ho parlam ja que jo no tenc molt clar com fer-ho amb ReactJS.
(2) Fer el mateix quan s'arriba a la URLCallBackError després d'intentar un login al front.
(3) també al processException del CommonFrontController.java

![imatge](https://user-images.githubusercontent.com/17084256/104579272-0a9d6800-565c-11eb-926d-5cba7013472b.png)

![imatge](https://user-images.githubusercontent.com/17084256/104563412-e769bd00-5649-11eb-90b2-28f8e48110ca.png)

**Comment by jpernia-fundaciobit** [comment]
El que es volia fer a la part de LoginController es resoldrà a l'issue "No es mostra cap error si falla el login al front #452".
El que es volia fer al processException del CommonFrontController.java, es detallarà a un nou issue.
