### ISSUE TITLE
Idiomes al front  segons BBDD

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#311]
Depèn de "Millores en el Front #289"

Els idiomes a mostrar en el front s'han de llegir de la BBDD:
`idiomaEjb.select(IdiomaFields.SUPORTAT.equal(true), new OrderBy(IdiomaFields.ORDRE))`

**Comment by jpernia-fundaciobit** [comment]
S'ha afegit un cridada REST per obtenir els idiomes suportats i es carreguen al Menú Deslliçant.
