### ISSUE TITLE
Creació d'element de feedback en temps de càrrega

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#312]
Depèn de "Millores en el Front #289"

Com a millora en la experiència d'usuari, que en els moments de càrrega es mostri algun element que doni feedback a l'usuari. 
P.ex: que s'enfosqueixi la pantalla i que mostri alguna icona i un texte de "Carregant, per favor esperi". (Com a exemple)

També passa a CARPETA 0, que l'obtenció dels registres d'entrada tarda més de l'habitual per la sobrecàrrega que pateix REGWEB a PRO.

**Comment by jpernia-fundaciobit** [comment]
S'ha afegit un element de feedback a la càrrega dels plugins html, que són els que carreguen més informació.

**Comment by scalafat-dgtic** [comment]
Incorporar també l'element en el procés d'obtenció de tràmits i en l'obtenció d'un detall de registre d'entrada.

**Comment by jagarcia-fundaciobit** [comment]
Tanco sa issue i n'he creada una altra per incorporar l'element de feedback a la part de registre en el següent sprint.
Creació d'element de feedback en temps de càrrega #343
