### ISSUE TITLE
Taula de Logs i Accessos  a un altre TableSpace

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#315]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #288"

La taula de Logs i Accessos a causa del seu gran volum s'hauria de moure a una altre tablespace. Revisar com s'ha fet a registre.

**Comment by mgonzalez-fundaciobit** [comment]
Pendent de sqlgenerator que no funciona.

**Comment by mgonzalez-fundaciobit** [comment]
- S'han creat les sentències per actualitzar les bd ja creades.
- S'han generat novament els scripts de creació de les BD de zero.
Als entorns CAIB se creen els següents TABLESPACE (CARPETA_DADES, CARPETA_LOB,CARPETA_INDEX)
