### ISSUE TITLE
Casuística tràmits SISTRA1

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#317]
Depèn de "Integració amb SISTRA1 #129"

Els tràmits de SISTRA1 provinents de la crida "obtenerElementosExpediente" requereixen un tractament diferent dels tràmits persitents (no acabats) obtinguts de "obtenerPersistentes". En concret:

La crida de "**obtenerPersistentes**" retorna tots els tràmits de SISTRA1 per reprendre. Aquests sempre han de reprendre's.

La crida "**obtenerElementosExpediente**" retorna els tràmits de PREREGISTRO, PREENVIO, ENVIO i REGISTRO. (Ignoram les COMUNICACIONS i NOTIFICACIONS):

- PENDIENTE = TRUE

1. PREREGISTRO i PREENVIO. Han de tenir MODAL.
2. La resta, són obtinguts de "obtenerPersistentes" perquè són tràmits que no s'han acabat i s'han de poder reprendre.

- PENDIENTE = FALSE

1. PREREGISTRO i PREENVIO no existeixen, perquè es converteixen en REGISTRO i ENVIO respectivament.
2. ENVIO, s'ha de mostrar a la taula, sense MODAL, perquè és un tràmit ja finalitzat.
3. REGISTRO, NO s'ha de mostrar a la taula perquè és un registre d'entrada acabat i, per tant, es veurà a la taula del plugin de Registre.

**Comment by jagarcia-fundaciobit** [comment]
Solucionat.
