### ISSUE TITLE
Moure carpeta "react" a "carpeta-front"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#318]
Depèn de "Millores en el Front #289"
Depèn de "Revisió d'estàndards #337"

Revisió d'estàndards a n'Asier. Moure carpeta "react" a "carpeta-front". Utilitzar la comanda rename de GitTortoise.

Avisar a tothom que no facin res amb react durant el renombrat.

**Comment by jpernia-fundaciobit** [comment]
Fet!
