### ISSUE TITLE
Revisar llibreries del ear que ja conté el JBoss

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#321]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #288"

Estandards Asier: "Las librerías del directorio /lib del ear no pueden colisionar con las versiones de las librerias ya incluidas en JBoss de forma nativa. Revisad librerías tipo: jaxws-api-2.3.1.jar, javax.persistence-api-2.2.0.redhat-1.jar,..."

**Comment by jagarcia-fundaciobit** [comment]
S'ha revisat l'arbre de dependencies i els distints pom.xml. S'han indicat com  a scope provided totes aquelles que estaven al JBOSS.
