### ISSUE TITLE
Indicar tablespace diferent a les taules i als indexos

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/carpeta#326]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #340"

Fer que l'sqlgenerator a partir d'un arxiu properties se li pugui indicar el tablespace a on han d'anar les taules i els indexos.

 -**CAS 1: taules amb camps tipus CLOB i voler especificar un tablespace per la taula :**

CREATE TABLE APL_TAULA
(
   camp1 tipus_camp1,
   camp2 CLOB,
   camp3 BLOB)
TABLESPACE APLICACIO_DADES
  LOB (camp2) STORE AS APL_TAULA_camp2_LOB (TABLESPACE APLICACIO_LOB  INDEX APL_TAULA_camp2_LOB_I)
  LOB (camp3) STORE AS APL_TAULA_camp3_LOB  (TABLESPACE APLICACIO_LOB  INDEX APL_TAULA_camp3_LOB_I);

 -**CAS 2: taules amb camps tipus CLOB i no voler especificar un tablespace per la taula :**

CREATE TABLE APL_TAULA
(
   camp1 tipus_camp1,
   camp2 CLOB,
   camp3 BLOB)
   LOB (camp2) STORE AS APL_TAULA_camp2_LOB (TABLESPACE APLICACIO_LOB  INDEX APL_TAULA_camp2_LOB_I)
  LOB (camp3) STORE AS APL_TAULA_camp3_LOB  (TABLESPACE APLICACIO_LOB  INDEX APL_TAULA_camp3_LOB_I);

- **CAS 3:  Indicar un tablespace a una taula sense CLOBS**

CREATE TABLE APL_TAULA
(
   camp1 tipus_camp1,
   camp2 tipus camp2)
TABLESPACE APLICACIO_DADES;

- **CAS 4: indicar tablespace als indexos:**

create index car_avis_entitatid_fk_i on car_avis (entitatid) TABLESPACE CARPETA_INDEX;

**Comment by scalafat-dgtic** [comment]
Com es va comentar, per ara, no comptarem amb els tablespaces CARPETA_DADES ni CARPETA_INDEX per dubtes de rendiment.
Només tendrem en compte CARPETA_LOB, obligatori per poder controlar la mida dels LOBs.

**Comment by jpernia-fundaciobit** [comment]
Es passa a la versió 1.1.9

**Comment by mgonzalez-fundaciobit** [comment]
Després de conversa telefònica amb en Simó, es decideix que només s'indicarà el tablespace a les taules que contenguin camps CLOB, per tant només s'ha de fer el CAS 1 taules amb camps tipus CLOB i voler especificar un tablespace per la taula.

**Comment by mgonzalez-fundaciobit** [comment]
Amb l'eina sqlgenerator s'ha d'indicar si es volen els lobs a un altre tablespace com indica el sqlgen.bat.
