### ISSUE TITLE
Revisió dels avisos

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#331]
Depèn de "Més Avisos pel Front #182" i es troba relacionat amb #144, #183, #184, #185

![image](https://user-images.githubusercontent.com/44995350/106573300-bd653580-6539-11eb-9027-38e4d1cdf192.png)

S'han creat els avisos que es mostren en la imatge i no apareix cap d'ells.

**Comment by jagarcia-fundaciobit** [comment]
No s'están mostrant els avisos perqué no s'han indicat la data d'inici ni la data de fi. 
Són camps necessaris per a qué es mostrin els missatges.

**Comment by scalafat-dgtic** [comment]
D'acord. És possible incluir la següent casuística?
- Si no s'especifiquen dates, que apareguin d'immediat i indefinidament
- Si s'especifica només data d'inici, que no aparegui fins el dia X i que es mostri indefinidament
- Si s'especifica només data de finalització que aparegui d'immediat i desaparegui quan arribi el dia X
- Si s'especifiquen les dates d'inici i finalització, que no aparegui fins el dia X i que desaparegui quan arribi el dia Y

**Comment by jagarcia-fundaciobit** [comment]
S'ha modificat la lògica perqué funcioni d'acord a aquesta casuística.
