### ISSUE TITLE
Canviar menú per hamburguesa

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#34]
Eliminar els botons del menú principal pel menú tipus hamburguesa, per totes les vistes (ordinador, tablet i mòbil). A més, fer el menú deslliçant horitzontalment, de dreta a esquerra. Falta definir bé com ha de ser el menú, abans de fer-ho.

**Comment by scalafat-dgtic** [comment]
Ja inclòs dins la refactorització del frontal #48
Tancam
