### ISSUE TITLE
Modificar títols i texts de dins dels plugins

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#341]
Depèn de "Millores en el Front #339 "

Opció de canviar tots els textos que apareixen a dins de la pantalla del plugin. Per exemple, en aquest cas, poder eliminar "SENSE ACABAR" de l'usuari perquè es mostrarien tots els tràmits telemàtics (pendents i finalitzats)

![imatge](https://user-images.githubusercontent.com/17084256/107187253-014ab580-69e6-11eb-86d3-cfba324c9ec8.png)

**Comment by anadal-fundaciobit** [comment]
Amb en Simó hem acordat que directament ens demanaran canvis d'etiquetes si fossin necessaries.
