### ISSUE TITLE
Creació d'element de feedback en temps de càrrega

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#343]
Depèn de "Millores en el Front #339"

Incorporar en el procés d'obtenció de tràmits i en l'obtenció d'un detall de registre d'entrada.

Com a millora en la experiència d'usuari, que en els moments de càrrega es mostri algun element que doni feedback a l'usuari.  P.ex: que s'enfosqueixi la pantalla i que mostri alguna icona i un texte de "Carregant, per favor esperi". (Com a exemple)

Implementació:
(1) S'ha d'eliminar la ICONA d'espera del REACT
(2) PLUGINS TIPUS REACT: En dades Personals hi ha un exemple d'espera amb un gif mentre una cridada rest s'acaba d'executar
(3) PLUGINS TIPUS HTML: Entre llistat i detalls s'ha de crear una pàgina que només contengui un gif d'espera i un codi javascript que cridi a la pagina de detall. Mentre no estigui completament disponible la pàgina de detall apareixerà el gif d'espera.

**Comment by jpernia-fundaciobit** [comment]
Està fet i pujat al plugin de Sistra. Per Regweb3 es farà en breu.

**Comment by anadal-fundaciobit** [comment]
Solucionat per registre3, notificacions i sistra. Els de dades personals ja incorporaven una espera.
