### ISSUE TITLE
Procés automàtic per esborrar els logs de forma periòdica

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/carpeta#344]
Depèn de "Gestió de logs #100"

S'ha de fer un procès autòmatic(Scheduler) que agafi la propietat global es.caib.carpeta.esborrarlogs.dies i vagi esborrant els logs amb una antiguitat dels dies indicats per la propietat.

Ex: 
es.caib.carpeta.esborrarlogs.dies = 10
 s'esborraran els logs que tenguin una antiguitat de més de 10 dies.

**Comment by jagarcia-fundaciobit** [comment]
S'ha creat un EJB que s'executa quan es desplega l'aplicació al servidor. 

Agafa les següents propietats globals: 
-  es.caib.carpeta.esborrarlogs.hora => indica l'hora d'inici de la tasca
-  es.caib.carpeta.esborrarlogs.dies => indica el número de dies que volem conservar els logs

Es crea un scheduler que s'executa diariament a l'hora indicada per "es.caib.carpeta.esborrarlogs.hora"  i esborra els registres de log més antic que el número de dies indicat a "es.caib.carpeta.esborrarlogs.dies". 

L'hora per defecte són les 4 de la matinada i guarda els logs dels darrers 90 dies.
