### ISSUE TITLE
Moure l'exposició a Dades Obertes a mòdul "carpeta-api-externa"

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#353]
Depèn de "Revisió d'estàndards #337"

A "Integració amb Portal Dades Obertes #114" es va exposar informació dels accessos de Carpeta per poder ser consultat per Socrata (plataforma de Dades Obertes de CAIB) però actualment la crida es fa a "/carpetafront/dadesobertes/accesos/?inici=2020-12-19&fi=2020-12-22&entitat=caib".

S'ha de moure a un mòdul apart, "carpeta-api-externa", en el context  "/api/externa/" enlloc de "/carpetafront/". 

(Falta actualitzar el document d'estàndards, però ja està incorporat a la documentació del [projecte base](https://www.caib.es/sites/dgtic/ca/estandards_de_desenvolupament/archivopub.do?ctrl=MCRST299ZI339658&id=339658))

IMPORTANT: Copiar modul de api-externa de ProjecteBase https://github.com/GovernIB/projectebase/tree/projectebase-1.0/projecteorigen/projectebase-api-externa

**Comment by jagarcia-fundaciobit** [comment]
S'ha refactoritzat el módul per mostrar les estadístiques de Dades Obertes a través d'un nou módul. Els paràmetres són els mateixos que estaven definits. 

La nova url per accedir-hi és:
/carpeta/api/externa/services/accessos/?entitat=caib&idioma=ca&inici=2021-01-01&fi=2021-01-31

![imagen](https://user-images.githubusercontent.com/70194276/109016236-3cbbd400-76b6-11eb-8fe3-d5a747ba81c4.png)
