### ISSUE TITLE
Separar plugin de Dades Personals en dos: de login i de Policia

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#355]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #422"
Depèn de "Obtenció i mostratge de dades del ciutadà #221" 

Com que ara es permeten seccions en Plugins( Veure Permetre Seccions en Plugins i enllaços de tipus PseudoPlugin #335)  el millor seria separar el plugin de Dades Personals en dos:
* Un plugin de dades de login
* Un plugin de dades de Policia

**Comment by jagarcia-fundaciobit** [comment]
Tanco la issue perquè això ja està solucionat a un altre issue.
