### ISSUE TITLE
Neteja de funcions reactjs obsoletes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#363]
Depèn de "Millores en el Front #339"

Dins del codi React hi ha un conjunt de funcions que s'han quedat obsoletes ja que la seva funció ja l'ocupa un plugin: newTramitsPendentsReact , newRegistresReact , newDetallRegistreReact , newNotificacionsReact, ...

Netejar aquestes funcions i d'altres relacionades que ja no s'usin.

**Comment by jpernia-fundaciobit** [comment]
S'han eliminat els Components que ja no s'utilitzen i s'han eliminat les referències a ells, així com les traduccions i motlles de pa referents a aquests.
