### ISSUE TITLE
Donar color als enllaços laterals

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#366]
Depèn de "Millores en el Front #339"

En aquesta pàgina web https://stackoverflow.com/questions/7273927/image-greyscale-with-css-re-color-on-mouse-over/21084820 es pot observar un exemple com emprant CSS converteix una imatge en escala de grisos i quan tornes a passar sobre ella torna a tenir color. Estaria bé fer-ho per Menú Lateral i alguna cosa similar pels enllaços del canto dret inferior.

**Comment by jagarcia-fundaciobit** [comment]
S'ha aplicat un filtre grayscale als logos que apareixen davall el logo lateral corporatiu... i quan pases per damunt es posen en color. Als logos de xarxes socials, s'ha aplicat un lleu filtre d'opacitat. 

![imagen](https://user-images.githubusercontent.com/70194276/109297254-01deab00-7832-11eb-93ab-2acba02cb61d.png)
