### ISSUE TITLE
Molla de Pa ha desaparegut

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#367]
Depèn de "Millores en el Front #339"

La Molla de Pa només apareix després de carregar una PLugin HTML i després ja es queda permanent. 
Revisar que esta passant i com es que no apareix des del principi. 

NOTA: LA Molla de Pa sempre serà visible en públic i en privat.

**Comment by jpernia-fundaciobit** [comment]
Es va determinar des de la DGMAD que la motlla de pà només sortís quan hi hagués 2 nivells, és a dir, si només ha de mostrar "Inici" no ha de sortir. Per tant, només ha de ser visible quan estam dins Accessibilitat, el MapaWeb, un plugin, etc. però no ha de sortir a les pàgines inicials pública i privada.

**Comment by jpernia-fundaciobit** [comment]
S'ha restaurat la Motlla de Pa a les pàgines on ha de sortir. 
Ara només falta que cada Plugin mostri el seu nom, això s'hauria de revisar a un altre issue.

**Comment by anadal-fundaciobit** [comment]
Una motlla de Pa dins cada Component no és la solució ja que hi ha plugins que són dinàmics i seccions que també són dinàmiques, a part de que un Plugin pot estar o a l'arrel o a dins alguna secció. El problema està en que el BreadCrumb de  Index.js no apareix, no és visible o està tapat per altres div's .

**Comment by anadal-fundaciobit** [comment]
Pendent de parlar amb en Joan Pernia.

**Comment by anadal-fundaciobit** [comment]
Solucionat. Ja funciona Molla de Pa per tot i també es veu el menú Ràpid

![imatge](https://user-images.githubusercontent.com/17084256/109141863-8102af00-775e-11eb-8b9a-5867e50e6bca.png)

![imatge](https://user-images.githubusercontent.com/17084256/109141886-85c76300-775e-11eb-9e4c-f2dd601c9b60.png)

**Comment by scalafat-dgtic** [comment]
Torna a haver problemes amb la motlla de pa.

Ara no apareixen als plugins de SISTRA ni REGWEB però sí a a les seccions.
![image](https://user-images.githubusercontent.com/44995350/111130391-77a77e00-8577-11eb-9ab1-24e1c5bda8d1.png)

En canvi, si entres a la secció i després vas al plugin de REGWEB, la motlla de pa segueix indicant la secció en qüestió. És a dir, no acaba d'actualitzar-se correctament (i no apareix als altres plugins abans comentats)

![image](https://user-images.githubusercontent.com/44995350/111130516-96a61000-8577-11eb-813e-0a36a46f6930.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat. Problema d'un controller que encara acceptava pluginID enlloc de PluginContext.
