### ISSUE TITLE
Relacionar Expiració de Sessió amb Routes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#372]
Depèn de "Millores en el Front #479"

Dins del front només hi ha dos events que haurien d'actualitzar la sessió: pitjar a Links de Route de ReactJS i pitjar a enllaços externs.

(1) Pel primer cas s'hauria d'utilitzar el mètode canviatRoute() de la class ReactJS Breadcrumb.js
(2) Pel segon cas, crearia una classe React per obrir un enllaç extern i la utilitzaria dins de MenuDesllissant, MenuRàpid i LlistatDePlugins. Aquesta classe a part obrir una nova finestra amb la URL haurien d'actualitzar la Sessió.

**Comment by jpernia-fundaciobit** [comment]
La sessió només s'ha d'executar quan s'estigui a la part autenticada del  front. Per tant:

- Ara el que es fa és que cada vegada que s'accedeix al contingut privat, ja sigui un plugin, Accessibilitat o Mapa Web, se reinicia la sessió. Pel que entenc, el mètode canviatRoute() s'executa cada vegada que es canvia la ruta, ja estiguis en la part pública o en la privada.

- Obrir un enllaç extern és, per exemple, obrir la pàgia de cerca del Govern o la d'Avís legal del Govern, a una altra pipella. Els enllaços externs estan disponibles a la part pública també. Es podria posar un reinici de sessió al pitjar un enllaç extern si estàs a la part privada, però tampoc ho veig imprescindible ... ho dic perquè estàs pitjant una url, no que facis cap consulta a dades teves, que és pel que entenc que hi ha d'haver una sessió.

**Comment by jpernia-fundaciobit** [comment]
Tancam perquè el sistema actual ja funciona.
