### ISSUE TITLE
MenuDeslissant duplica codi de gestió d´idiomes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#375]
Depèn de " Millores en el Front #423"

El codi per mostrar els idiomes disponibles i seleccionat dins del MenuDeslissant està duplicat. S'hauria de refactoritzar emprant if-else per centralitzar-ho en un sol tros de codi i no en tres. A més s'ha de fer independent del numero de idiomes disponibles.

![imatge](https://user-images.githubusercontent.com/17084256/108823647-02243f80-75c1-11eb-9195-15d0122fb782.png)

**Comment by jpernia-fundaciobit** [comment]
S'ha aprofitat per fer dinàmic l'idioma a la pàgina de selecció d'Entitat inicial (jsp).

**Comment by jpernia-fundaciobit** [comment]
S'ha fet dinàmica la selecció d'idiomes al menú i s'ha eliminat codi repetit.
