### ISSUE TITLE
Utilitzar  <c:url> en les rutes css, js i favicon de inici.jsp

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#377]
Depèn de "Millores en el Front #339"

Utilitzar  <c:url> en les rutes css, js i favicon de inici.jsp del Front enlloc de ${pageContext.request.contextPath}

![imatge](https://user-images.githubusercontent.com/17084256/108824818-77444480-75c2-11eb-88b1-366518700982.png)

**Comment by jagarcia-fundaciobit** [comment]
Fet.
