### ISSUE TITLE
Revisar Estils de Codi HTML de LoginText de l'Entitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#383]
Depèn de "Millores en el Front #339"

Es va implementar el issue "Informació de Login que s'obtengui de l'ENTITAT #292 " que permet posar el codi html ficat en el camp loginText de l'entitat en l'IniciPublic del front. Si no es defineix llavors es posa un codi per defecte. 

Per definir aquest text només s'ha d'executar l'script sql de /[carpeta]/scripts/BBDD/postgresql/05_sample_inici_public_caib.sql

Per desactivar-ho només s'ha d'editar l'entitat i esborrar les traduccions del camp LoginText.

En principi el codi html de reactjs i el que ofereix el camp LoginText és el mateix, però no es mostra igual. 

Una suposició es que ReactJS modifica les classes CSS dinamicacment d'aqui que es vegi diferent.

Intentar veure que li passar al codi HTML de 05_sample_inici_public_caib.sql

![imagen](https://user-images.githubusercontent.com/17084256/109148625-cb882980-7766-11eb-99fe-7d99bb7fe8e8.png)

![imagen](https://user-images.githubusercontent.com/17084256/109149092-65e86d00-7767-11eb-97e1-d9217b6f9344.png)

**Comment by jagarcia-fundaciobit** [comment]
Solucionat. Sembla que no agafa bé les etiquetes que s'obrin i es tanquen en una única etiqueta (self-closing tags).
