### ISSUE TITLE
Tamany de lletra massa gran per Nom Ciutadà i Nivel de Seguretat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#384]
Depèn de "Millores en el Front #339"

Després del Login, a la part superior apareix el nom del ciutada. En Simó comenta que és massa gran. Posar un font més petita a Nom i Nivell de Seguretat.

![imatge](https://user-images.githubusercontent.com/17084256/109150182-cd52ec80-7768-11eb-95b1-684518a4d02f.png)

**Comment by jagarcia-fundaciobit** [comment]
Canviat. S'ha pres com a referencia un tamany que estaba definit a un altre estil pel mateix element.

![imagen](https://user-images.githubusercontent.com/70194276/109159891-6ee03b00-7775-11eb-82b9-adb31c513690.png)
