### ISSUE TITLE
Error Desconegut al descarregar Justificant

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#385]
Depèn de "Millores en el Front #339"

REVISAR-HO NOMÉS PEL PLUGIN REGWEB32

SIMO CALAFAT: En generar el justificant d'un registre, no tenc manera de saber què ha fallat, des de Carpeta, i no apareix al Log d'errors del Back.

![imagen](https://user-images.githubusercontent.com/17084256/109150594-58cc7d80-7769-11eb-8fd4-b6482fe64ae7.png)

**Comment by jagarcia-fundaciobit** [comment]
S'han creat les cridades corresponents dins del plugin per enregistrar els errors alhora que es recupera un justificant o un annex. Apareixerán al log del backend.
