### ISSUE TITLE
Renombrar mòdul carpeta-api a carpeta-api-interna

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#387]
Depèn de "Revisió d'estàndards #337"

Nova revisió d'estàndards:
-El módulo carpeta-api se ha de eliminar si no es necesario. Ya existe el módulo carpeta-api-externa. Si es necesario ha de llamarse carpeta-api-interna si se trata de un API que no debe publicarse en Internet. 

NOTA ANADAL: **Aquest mòdul es pot eliminar ja que no s'utilitza ni compila.**

**Comment by anadal-fundaciobit** [comment]
Solucionat. S'ha esborrat el mòdul. No s'utilitzava
