### ISSUE TITLE
No me mostren els enllaços laterals a la part pública

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#389]
Depèn de "Millores en el Front #339"

Com a usuari
vull veure els enllaços de l'entitat on estic
per a poder accedir-hi

Es mostrava aquesta informació davall el logotip de l'entitat. Ara només es mostra a la part privada

![image](https://user-images.githubusercontent.com/17266896/109630865-af5d0180-7b45-11eb-8afd-ef9bd98d8711.png)

**Comment by jagarcia-fundaciobit** [comment]
Fet.
