### ISSUE TITLE
No s'amaga la rodeta quan descarregam el justificant del detall (Plugin Regweb 3.2)

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/carpeta#392]
Quan descarregam un justificant que no te url especificada, es devalla l'arxiu del justificant directament, normalment és quan es genera. Com és un procés que tardfa molt, es mostra una rodeta de que està fent feina, pero quan ja descarrega el fitxer, aquesta rodeta no s'amaga.

S'hauria de fer que s'amagàs. 
![image](https://user-images.githubusercontent.com/17267873/109651153-71200c00-7b5e-11eb-9fa0-0e34a76bc1a8.png)

**Comment by jagarcia-fundaciobit** [comment]
Fet, he creat una funció javascript que amaga el loader.
