### ISSUE TITLE
Espera quan es carreguen registres del plugin  registre32

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#393]
Depèn de "Millores en el Front #339"

Dins del issues "Creació d'element de feedback en temps de càrrega #343" pel plugins es va fer una rodeta d'espera quan es feien consultes a servidors.
Ara hi ha el nou plugin de registre32 que no incorpora aquesta funcionalitat.  Incorporar les millores del plugin de SISTRA:
(1) La primera cridada que envii a una pàgina d'espera
(2) Les cridades dins del llistat (paginació) que obrin un div amb un rodeta i amaguin el  llistat. AIXÔ PAREIX QUE JA ESTA FET !!!!

**Comment by jagarcia-fundaciobit** [comment]
Fet.
