### ISSUE TITLE
Modificar l'entitat on es creen els accessos

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#395]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #340"

Com a desenvolupador
vull crear a la BBDD accessos d'usuaris  
per a saber les vegades que els usuaris accedeixen a cada Entitat

A "CarpetaFrontAuthProvider" es fa això al següent codi:

PropietatGlobalService propietatGlobalEjb = EjbManager.getPropietatLogicaEJB();
String defaultEntityCode = EjbManager.getDefaultEntityCode(propietatGlobalEjb);
EntitatJPA entitat = utilsEjb.getEntitat(defaultEntityCode);
long entitatID = entitat.getEntitatID();
accesLogicaEjb.crearAcces(usuarioClave, TIPUS_ACCES_LOGIN_AUTENTICAT, entitatID, null, new Timestamp(new Date().getTime()), LocaleContextHolder.getLocale().getLanguage(), InetAddress.getLocalHost().getHostAddress(), true);

Però això pressuposa que hi ha definida una propietat global "defaultEntityCode" i sempre se faran els accessos a la mateixa entitat.
S'ha d'obtenir l'Entitat de la sessió i fer l'accés a aquesta Entitat.

**Comment by jagarcia-fundaciobit** [comment]
Fet. A partir de la informació d'usuari, cerca les entitats que té associades i registra l'accés.

**Comment by jagarcia-fundaciobit** [comment]
Hi havia un problema pel cas de multientitat que ja he solucionat. Si hi ha definida la variable de Entitat a la sessió, l'agafa d'allà mateix. Si no està definida, cerca les entitats de l'usuari i en el darrer cas, agafa l'entitat per defecte.
