### ISSUE TITLE
Redirecció a HOME en expirar sessió

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#399]
Depèn de "Millores en el Front #339"

Quan s'expira la sessió es redirigeix a la pàgina /error que no està contemplada dins CARPETA. Abans, si no record malament, aquesta redirecció es feia correctament a la HOME sense autenticar i sortia un missatge de que la sessió havia finalitzat.

Es proposa recuperar la funcionalitat anterior.

**Comment by jpernia-fundaciobit** [comment]
Es passa a la nova versió ja que s'ha detectat que això passa quan es reinicia el jboss i després expira la sessió.

**Comment by jpernia-fundaciobit** [comment]
Faltava definir la propietat global "defaultEntity". Així, quan es reiniciava el jboss, el front no trobava cap identificador d'entitat. Amb la propietat global definida, ja funciona correctament.

S'ha aprofitat per eliminar l'expiració de sessió de la part pública del front.
