### ISSUE TITLE
No coincideix idioma del LocaleContextHolder amb l'actual del front

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#400]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ...) #340"

Com a usuari
vull veure la informació de tot el front en l'idioma seleccionat
per a tenir la informació com vull

Abans funcionava. 
Ara tenim el front en un idioma, i les cerques de les cridades REST estan en un altre. 
Per exemple, podem tenir el front en castellà:

![image](https://user-images.githubusercontent.com/17266896/109814533-e9ee9900-7c2e-11eb-93d1-a4b47fd46549.png)

Però les cerques de plugins retornen els resultats en català:

![image](https://user-images.githubusercontent.com/17266896/109814738-24583600-7c2f-11eb-9bf9-f0d43b3f7ad9.png)

![image](https://user-images.githubusercontent.com/17266896/109814846-4487f500-7c2f-11eb-8266-fcdb36490373.png)

**Comment by anadal-fundaciobit** [comment]
Només he trobat el cas de la Secció:
![imagen](https://user-images.githubusercontent.com/17084256/109946033-1ad6d880-7cd8-11eb-81ab-38c2b14e8935.png)

**Comment by jpernia-fundaciobit** [comment]
Si l'idioma del front seleccionat és "castellà" a la part pública, quan entra a la part privada mostra els plugins en català.

![image](https://user-images.githubusercontent.com/17266896/109951565-23321200-7cde-11eb-9ace-8e807eae4ea7.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat: ja mostra bé pagines estatiques (mapaweb i accessibilitat, plugins, seccions, i seccions-plugins.
