### ISSUE TITLE
Eliminar mètodes no utilitzats de WebUIController

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#403]
Depèn de "Millores en el Front #423"

Arran de la implementació del issue "Centralitzar en una sola cridada REST les diverses cridades de MenuDeslissant #402", molts de mètodes rest de la classe WebUIController ja no s'utilitzen. Fer una revisió d'aquests mètodes i veure si es poden esborrar.

**Comment by anadal-fundaciobit** [comment]
Aquest mètode falla:

![imagen](https://user-images.githubusercontent.com/17084256/113665745-50435d00-96ae-11eb-83f2-6e5c44a8e815.png)

**Comment by mgonzalez-fundaciobit** [comment]
No s'han reportat més errors. Tancam.
