### ISSUE TITLE
Urls "amigables"

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#404]
Depèn de "Millores en el Front #339"

Sabem de la configuració de l'entrada del Routes de React i de la configuració mitjançant plugins del frontal, però s'hauria de trobar una solució a les urls del frontal.

https://dev.caib.es/carpetafront/#/pluginhtml/1

S'hauria de poder eliminar l'**#** i canviar el text de **pluginhtml** per un nom bàsic identificatiu.

Ho trobam important tant de cara a l'usuari, com per control d'errors, com per accessibiltat.

**Comment by jpernia-fundaciobit** [comment]
S'està en procés de Tancar versió, per tant, es passa a la 1.1.9

**Comment by anadal-fundaciobit** [comment]
Al final en Simo ha decidit el següent:
    * Afegir un camp a seccions i plugins que sigui contexte
    * Aquest contexte s'utilitzarà en les URL del front enlloc de la seccioID o pluginID
    * Les rutes a seccions i plugins s'han de modificar segons el que es diu a continuació:
- /seccio/<nom_context_a_bd>
    - /modul/<nom_context_a_bd> pels plugins react
    - /moduls/<nom_context_a_bd> pels plugins html

**Comment by anadal-fundaciobit** [comment]
Solucionat

![imagen](https://user-images.githubusercontent.com/17084256/110615079-50c20400-8193-11eb-9ade-4d57d127b471.png)

![imagen](https://user-images.githubusercontent.com/17084256/110615145-620b1080-8193-11eb-9a1a-2d5e2331131b.png)
