### ISSUE TITLE
Consistència entre elements de feedback i condició de mostratge

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#405]
Depèn de "Millores en el Front #339"

Els elements de feedback (les rodetes) no són els mateixos quan entres dins el plugin de sistra que si entres al plugin de registre. Les rodetes haurien de ser exactament les mateixes (recoman la verda per consistència visual amb l'aplicació).

A més, no haurien d'aparèixer, a la vegada, la rodeta i la resta d'informació. (la captura següent és antiga però passa en obrir el detall de registre)

![image](https://user-images.githubusercontent.com/44995350/110107229-ec75fd80-7daa-11eb-83fb-ad30cf211871.png)

**Comment by anadal-fundaciobit** [comment]
La pagina d'espera genèrica s'ha arreglat. Els llistats de Registre i Sistra s'ha fet que quan es carreguin, llavors s'oculti el llistat i només es mostri la rodeta.
