### ISSUE TITLE
No es mostren les propietats globals quan els he modificat

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#406]
Depèn de "Millores en el codi del back #338" 

He actualitzat la propietat default-entity al backoffice de CARPETA amb el valor "caib" per poder mirar el comportament de #399 i en guardar els canvis m'ha desaparegut de la llista.

![image](https://user-images.githubusercontent.com/44995350/110108882-031d5400-7dad-11eb-9ca1-a71408ebe67b.png)

Es pot veure que el valor s'ha guardat correctament:

![image](https://user-images.githubusercontent.com/44995350/110108975-26480380-7dad-11eb-88b9-df5846f0234e.png)

**Comment by scalafat-dgtic** [comment]
Ok, veig que l'he creada dins una entitat.

En aquest cas, es vol que des del menú del SuperAdministrador es pugin veure les propietats que ha definit cada Entitat.

**Comment by jagarcia-fundaciobit** [comment]
Fet. sí la propietat no té entitat asociada (columna buida), es tracta d'una propietat global del sistema.

![imagen](https://user-images.githubusercontent.com/70194276/110295636-9fd03380-7ff1-11eb-9cbd-4cc5d1f4a277.png)
