### ISSUE TITLE
Sortir de la sessió del Back amb el Logout

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#409]
Depèn de "Millores en el codi del BACK #338"

Com a usuari del Back
vull poder sortir de l login de l'aplicació
per a alliberar la sessió

Quan pitges al Logout del menú no surt de la sessió i segueix loguejat.

**Comment by jagarcia-fundaciobit** [comment]
He realitzat varies proves i el problema está quan el mètode d'autenticació és mitjançant base de dades. Pel cas de keycloak funciona correctament. 

Quan es pitja sobre l'opció de logout, s''executa correctament un métode per invalidar la sessió i es crida al método logout de Spring. El tema és que després de fer això, es redirecciona a la pàgina d'inici... i sembla que el navegador té els credencials guardats i s'autentica automàticament.

**Comment by jagarcia-fundaciobit** [comment]
Es passa la issue al backlog per realitzar els canvis necessaris a una altra sprint.

**Comment by jpernia-fundaciobit** [comment]
L'autenticació anirà sempre amb Keycloak, i funciona. Per això es tanca.
