### ISSUE TITLE
Error al formulari per crear un avís al Back

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#411]
Depèn de "Millores en el codi del BACK #338"

Com a Superadministrador del Back
vull poder crear un avís i que no surti error al formulari
per a evitar confondre l'usuari

Quan estàs amb el rol SuperAdministrador al Back, al formulari de creació d'un avís, i tens seleccionada una entitat al Desplegable "Entitat", al guardar dóna un error. Només es pot crear un avís si no es tria cap entitat, però per fdefecte en surt una seleccionada. Si és així, seria millor que per defecte no hi hagués cap entitat seleccionada i que no mostré aquest desplegable.

**Comment by anadal-fundaciobit** [comment]
Solucionat: s'ha amagat l'entitat en el cas de Avisos de Tipus BACK i se li ha posat un valor buit. 

![imagen](https://user-images.githubusercontent.com/17084256/110631177-86241d00-81a6-11eb-8b38-f87be287bc10.png)
