### ISSUE TITLE
Desapareix propietat global del Back al editar-la

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#412]
Depèn de "Millores en el codi del BACK #338"

Com a usuari del Back
vull poder editar una propietat global
per a reutilitzar-la

Quan s'edita una propietat global des del rol SuperAdministrador del Back (per tant sense entitat assignada) i guardar-la, desapareix del Back. 
El problema és que quan l'edita, el formularia apareix amb el camp Entitat, que no surt al formulari de creació de propietats globals amb aquest rol, i surt seleccionada per defecte una entitat. Al guardar, la guada amb l'entitat assoada i per això ja no apareix al back de SuperAdministrador.

**Comment by anadal-fundaciobit** [comment]
Solucionat. Pareix un bug el <form:select> que no gestiona correctament els valors null. Fins ara l'opció buida estava la primera i no ens adonavem d'aquest "bug". Ara pintam l'opció buida la darrera i el bug ha aparegut. S'ha fet comprovació manual de si el valor actual és buit.
