### ISSUE TITLE
Revisar la versió responsive del front

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#415]
Adjunto varies captures. A la primera, no es veu el nom d'usuari i  a la segona imatge, es superposen els logos del menú rápid.  

![imagen](https://user-images.githubusercontent.com/70194276/110329234-9f00c700-801c-11eb-9e84-d05e23b744cf.png)

![imagen](https://user-images.githubusercontent.com/70194276/110329425-da02fa80-801c-11eb-97e4-16444cebd978.png)

**Comment by jpernia-fundaciobit** [comment]
Millorats els tamanys de la barra de menú segons les diferents opcions

**Comment by jpernia-fundaciobit** [comment]
Es torna a obrir perquè s'ha vist que al plugin de Sistra quan està en mode mòbil, el formulari de cerca surt de l'espai que hi ha disponible. S'hauria d'augmentar el padding en aquest cas.

![image](https://user-images.githubusercontent.com/17266896/110781226-ed54d680-8265-11eb-9381-1dc7da6c3586.png)

**Comment by jpernia-fundaciobit** [comment]
També s'ha de llevar el menú ràpid del front quan estiguem  en mode "mòbil". Aquí només s'utilitzarà el menú hamburguesa. Això ens sona que ja estava fet anteriorment.

![image](https://user-images.githubusercontent.com/17266896/110781720-897edd80-8266-11eb-8a0d-531b53ccf98d.png)

**Comment by jpernia-fundaciobit** [comment]
S'han fet els canvis indicats.
