### ISSUE TITLE
Enllaços obrin a una nova pestanya

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#416]
Depèn de "Millores en el Front #339"

Com a usuari
vull que les url's externes s'obrin en pipelles noves
per a sempre tenir obert el front al navegador

Fer que els enllasos, tant de les xarxes socials com dels enllaços laterals, obrin a una nova pestanya amb el target blank. 

![imagen](https://user-images.githubusercontent.com/70194276/110438682-edfb3a80-80b6-11eb-97f2-167f70f3808f.png)

**Comment by jpernia-fundaciobit** [comment]
S'ha afegit que els enllaços que siguin externs s'obrin a una pipella nova.
