### ISSUE TITLE
Nou camp actiu a Enllaços i  Seccions

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#417]
Depèn de "Millores en el codi del BACK #424"

Com a Administrador d'entitat, 
Vull poder "activar" o "desactivar" enllaços i/o seccions
per tal de controlar si s'ha de mostrar o no al front

Afegir el nou camp al back així com als métodes que envien la informació al front.

**Comment by anadal-fundaciobit** [comment]
Solucionat.
