### ISSUE TITLE
Mostrar els plugins, enllaços i seccions en un ordre determinat

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#418]
Depèn de "Millores en el codi del BACK #424"

Com a Administrador d'entitat
Vull poder indicar l'ordre en que han d'aparèixer els plugins, enllaços i seccions al front 
Per tal de mostrar el contingut en un determinat ordre.

Actualment es mostren ordenats per ID descendent

![imagen](https://user-images.githubusercontent.com/70194276/110440838-619e4700-80b9-11eb-8692-da0bff37dc4a.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat.
