### ISSUE TITLE
Revisió codificació dels scripts SQL

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#420]
Depèn de "Revisió d'estàndards #337" 

Des de Base de Dades ens comenten el següent:

"Segons els estandards de BD no s'accepta la codificacio BOM.  D'altra banda, tambe es mescla codificacio UTF-8 amb ISO. Ho han de ser tots UTF o be ISO. ASCII va be amb qualsevol de les dues.

- 01_sequences.sql:                ASCII text, with CRLF line terminators
- 02_tables.sql:                   ASCII text, with CRLF line terminators
- 03_constraints.sql:              ASCII text, with CRLF line terminators
- 04_indexes.sql:                  ASCII text, with CRLF line terminators
- 06_grants.sql:                   ASCII text, with CRLF line terminators
- 07_initial_data.sql:             ISO-8859 text, with very long lines, with CRLF line terminators
- 08_sample_data_caib.sql:         HTML document, ISO-8859 text, with very long lines, with CRLF line terminators
- 09_sample_inici_public_caib.sql: UTF-8 Unicode (with BOM) text, with CRLF line terminators
"

Es proposa, doncs, actualitzar tots els fitxers de scripts (postgres i oracle) amb UTF-8 (sense BOM) o una codificació adequada als estàndards.

![image](https://user-images.githubusercontent.com/44995350/110606005-0720eb80-818a-11eb-8590-42841a5853eb.png)

**Comment by mgonzalez-fundaciobit** [comment]
S'han convertit tots a UTF-8 Sin BOM i s'han organitzat les sentencies molt llargues.
