### ISSUE TITLE
Avisos de tipus Back nome´s apareixen en el Role SUPER i no en el ADMINENTITAT

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#421]
Hauria de sortir també en l'Administrador d'Entitat

![imagen](https://user-images.githubusercontent.com/17084256/110634704-8d4d2a00-81aa-11eb-9e97-863ba24a5c4b.png)

![imagen](https://user-images.githubusercontent.com/17084256/110634723-92aa7480-81aa-11eb-9022-82b68fb78d5a.png)

**Comment by jagarcia-fundaciobit** [comment]
Solucionat. Quan s'autentica un admnistrador d'entitat al backend, a més de veure els avisos actius de tipus BACK ENTITAT, també veurá els de tipus BACK.
