### ISSUE TITLE
Llevar fons blanc dels plugins del front i posar #666

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#426]
Depèn de "Millores en el Front #339"

Com a desenvolupador
vull que el front tengui sempre el mateix color de fons
per a que compleixi els estils marcats per la DGMAD

Abans el fons dels plugins estava en gris, com totes les altres pàgines del front. S'ha de posar que el fons dels plugins tenguin el color #666. S'ha detectat a Registre, Tràmits i Notificacions.

**Comment by jpernia-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/17266896/110780798-63a50900-8265-11eb-8168-4f106f80bd0b.png)

**Comment by jagarcia-fundaciobit** [comment]
Fet. Modificat al fitxer de carpeta.css
