### ISSUE TITLE
PLugin RegWeb32: Gestionar errors en llistat i detalls

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#428]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #422"

S'ha de forçar un llançament d'excepció en el codi de la part servidor del plugin de Regweb32 i veure que en el Front es mostra l'error.
Aquesta excepció s'ha de provar en llistat, detall i descàrrega de fitxers.

**Comment by jagarcia-fundaciobit** [comment]
He afegit uns estils a la pàgina d'error. A més, hi havia un problema al canviar de pàgina amb l'altura del iframe que constantment estava creixent degut a un error de javascript.
