### ISSUE TITLE
Error en la pàgina de selecció d'Entitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#433]
Depèn de " Millores en el Front #423"

Quan entres en la selecció d'entitat al front si mires la consola apareix un error.

```
react-dom.development.js:4119 Uncaught Error: Target container is not a DOM element.
    at Object.render (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:4119)
    at eval (webpack:///./src/main.js?:17)
    at Module../src/main.js (reactjs_main.js:3426)
    at __webpack_require__ (reactjs_main.js:20)
    at reactjs_main.js:84
    at reactjs_main.js:87
```

A més, pareix que el menú deslissant no és funcional. Si no ha de mostrar res, llavors llevar-ho.

![imagen](https://user-images.githubusercontent.com/17084256/111271647-c74a8000-8631-11eb-8da4-340b75b14293.png)

**Comment by jpernia-fundaciobit** [comment]
Aquest error el dóna perquè entitat.jsp no és react, és un jsp.
El que s'ha fet és només mostrar aquest jsp en el cas de que no hi hagi una Entitat a la sessió i no estigui definida la variable global "defaultentity". Per tant, passarà en molt pocs casos.
S'ha creat un Component nou que es mostrarà a l'entitat on estigui l'usuari, i des d'on es podrà canviar d'entitat.

**Comment by jpernia-fundaciobit** [comment]
Reobert perquè no canvia bé d'entitat.

**Comment by jpernia-fundaciobit** [comment]
S'ha corregit el canvi d'entitat, canviant "Link" per "a" ja que sinó mantenia al context "#" i no accedia al canvia d'entitat de l'IniciController.
