### ISSUE TITLE
Crear nou camp Descripció a Entitat

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#435]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #422"

Com a usuari del front
vull poder veure una descripció de cada entitat a la vista per triar entitats
per a poder saber quina és la que vull visitar

Quan l'usuari del front accedeix a la vista del canvi d'entitat, només pot veure el nom de l'Entiat i l'icona. Faltaria una descripció per afegir a cada entitat per saber quina és la que vull visitar.

**Comment by anadal-fundaciobit** [comment]
Solucionat.
![imagen](https://user-images.githubusercontent.com/17084256/112977709-a8320f00-9156-11eb-801f-ffc816055f44.png)
