### ISSUE TITLE
Analitzar com reportar errors dels plugins al log de carpeta

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#436]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #481"

Actualment els errors que es produeixen dins dels Plugins no arriben a Carpeta a causa de la pròpia naturalesa dels Plugins. Cercar algun mecanisme de Listener en l'objecte enviat al plugin, per a que aquest pugui reportar errors a Carpeta.

Intentar aplicar la solució de l plugin de regweb.

**Comment by jagarcia-fundaciobit** [comment]
Fet. 

- S'ha creat un nou mètode al EJB de LogCarpetaLogica per tal d'enregistrar els errors dels plugins. 
- S'ha creat una nova interficie IListenerLogCarpeta a carpetafront-api.  
- S'ha afegit un nou paràmetre a les cridades de requestCarpetaFront i getStartUrl dels plugins per enregistrar els errors dins logCarpeta alhora de capturar-los.
