### ISSUE TITLE
Error al entrar per  primera vegada al Back

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#438]
Depèn de "Millores en el codi del BACK #338"

S'ha intentat entrar en el back per primera vegada i a carpeta back ens ha donat l'error adjunt

Lògicament, quan es fa l'insert del log en entrar l'usuari nou, la columna descripció (CAR_LOG/DESCRIPCIO) no pot ser nula (ho tenc com 'not null'). Entenc que a l'hora d'enregistrar el log, deu faltar la descripció.

[carpeta_error.log](https://github.com/GovernIB/carpeta/files/6188341/carpeta_error.log)

**Comment by mgonzalez-fundaciobit** [comment]
Es veu que es produeix un error desconegut i el missatge era buit. Ara si és buit, al manco el missatge dirà "Error desconegut".

**Comment by scalafat-dgtic** [comment]
Quan entra un nou usuari al backoffice de CARPETA, que té permisos, i li dona a "Guardar" a la seva informació, apareix el següent error:

java.lang.IllegalArgumentException: Could not locate ordinal parameter [1], expecting one of [2]

![image](https://user-images.githubusercontent.com/44995350/112318774-b17e3000-8cad-11eb-973f-da64173edf54.png)

**Comment by jagarcia-fundaciobit** [comment]
En Simó ha estat fent proves i li ha funcionat. De totes formes, per evitar aquest error en el cas que no es llegeix bé la informació de keycloak, el camp es mostrará sense el read-only i l'usuari podrá posar-hi el seu NIF.
