### ISSUE TITLE
Revisió Manual d'usuari (Part Administrador d'Entitat)

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#441]
Depèn de "Revisió Manual d'usuari #181"

Com a desenvolupador
vull actualitzar la part d'Administrador d'Entitat del manual d'usuari del back
per a tenir-lo actualitzat i repartir el manual en diferents apartats

Una vegada fet, s'avisarà a l'equip de que es posaran els canvis al document principal, abans de pujar-lo. S'afegirà, es farà commit i es tornarà a avisar a l'equip de que ja està.

**Comment by jagarcia-fundaciobit** [comment]
Fet i revisat per complet (estils, texts, formats, etc.)
