### ISSUE TITLE
Revisar l'ordenació dels resultats d'una llista amb les fletxes de les columnes del back

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#445]
Depèn de "Millores en el codi del BACK #513"

**Com a** usuari del back
**vull** poder ordenar els resultats d'una llista
**per a** veure la informació en ordre ascendent o descendent

Fent l'ordenació, el resultat mostrat no pareix seguir unes regles d'ordre alfabètic ascendent i descendent.

![image](https://user-images.githubusercontent.com/17266896/112475793-7e04d980-8d71-11eb-9c59-b5449ceb6830.png)

![image](https://user-images.githubusercontent.com/17266896/112475871-9543c700-8d71-11eb-898d-14242455aa7a.png)

**Comment by jpernia-fundaciobit** [comment]
He intentat fer proves per ordenar els resultats,llevant ordenació amb javascript i fer ordenacions utilitzant datatables, com s fa al front. No he estat capaç d'aconseguir-ho ... amb el codi autogenerat amb el Genapp, no ho he pogut fer.
El torn a deixar al To do.

**Comment by jagarcia-fundaciobit** [comment]
Hem vist que es un problema amb les columnes que fan referencia a traduccions. Després de xerrar amb en Toni Nadal, li pas sa incidència per a què ho revisi.

**Comment by anadal-fundaciobit** [comment]
S'ha arreglat per Plugins, PLuginsPerEntitat i per Seccions.
