### ISSUE TITLE
No es mostra cap error si falla el login al front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#452]
Depèn de " Millores en el Front #423"

(1) Fer un ROUTE REACTJS  especial que sigui /error que mostri un error.  No se si passar l'error per paràmetres o mantenir-ho al servidor i fer una crida REST per recuperar-ho.

(2) Fer que quan fas el login al front i aquest falla llavors es vagi a aquesta pàgina /error. Per provar-ho, desconectar-se de la xarxa i intentar fer un login al FRONT (desactivar el plugin MOCK). Revisar que errors de login apareixen als logs d'error.

(3) Revisar si en la instànciació de PluginsHTMl o PluginsREact del front, en haver-hi un error es pugui cridar a aquest ROUTE /error

(4) Avisar al grup d'aquesta nova pàgina /error i que diguin si lis sona de llocs en es pugui utilitzar.

**Comment by jpernia-fundaciobit** [comment]
Fet amb una variable de sessió on guarda un possible error de login i el mostra a AvisosFront.
