### ISSUE TITLE
entitat.jsp eliminar la gestió de traduccions d'idiomes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#453]
Depèn de "Millores en el Front #423"

Del jsp del Front entitat.jsp eliminar la gestió de traduccions d'idiomes a partir de traduccions fixes i utilitzar el paràmetre idiomes que conté el conjunt de idiomes disponibles .

La llista d'idiomes disponibles i les traduccions de les etiquetes han de venir del servidor, no de ReactJS.

**Comment by jpernia-fundaciobit** [comment]
S'ha eliminat la gestió amb comparacions amb idiomes fixos i s'ha fet tot dinàmic. A més, s'ha ordenat la llista d'idiomes segons el camp ordre de la BBDD.
