### ISSUE TITLE
Reanomenar el context /carpeta/api/externa per /carpetaapi/externa

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#456]
Depèn de "Revisió d'estàndards #337"

Atesa la petició de Serveis Web de reanomenar els mòduls d'API i que s'han incorporat a la nova versió dels Estàndards (veure pàgina 30 dels [estàndards](https://www.caib.es/sites/dgtic/ca/estandards_de_desenvolupament/archivopub.do?ctrl=MCRST299ZI339655&id=339655), es demana reanomenar el context **/carpeta/api/externa** per **/carpetaapi/externa**

**Comment by jagarcia-fundaciobit** [comment]
S'ha modificat el context a carpetaapi/externa tal com s'indica i s'ha actualitzat el manual d'integracions rest. 

![imagen](https://user-images.githubusercontent.com/70194276/113858413-ff159500-97a3-11eb-8bf6-06784c885a7e.png)
