### ISSUE TITLE
Revisar l'idioma que es guarda a Acessos al frontal del back

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#457]
Depèn de "Millores en el codi del BACK #424"

**Com a** Super Administrador
**vull** veure la informació d' "accessos al front" del back amb l'idioma correcte de l'usuari
**per a** tenir-ho ben guardat a la BBDD

A vegades quan registra un accés al frontal a la BBDD, no guarda l'idioma correcte.

Per exemple, estic al front en català:
![image](https://user-images.githubusercontent.com/17266896/113131723-dc243780-921d-11eb-81ab-b7646986a84c.png)

I guarda l'idioma "es":
![image](https://user-images.githubusercontent.com/17266896/113131851-0249d780-921e-11eb-8eef-e1ab3a841bc6.png)

Si es fa accés a un plugin, sí que m'ho ha guardat bé.

**Comment by jagarcia-fundaciobit** [comment]
S'ha revisat com s'obté l'idioma alhora de realitzar la autenticació i ho he modificat pel mateix mètode de com es fa a plugins. Ara s'utilitza Locale en comptes de LocaleContextHolder i ho agafa correctament.
