### ISSUE TITLE
Barra en menú desllissant despres dels idiomes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#458]
Depèn de "Millores en el Front #423"

No tenc entitat per defecte, i just despres de seleccionar-ne una, el menú deslissant abans d'Accedir amb CLAVE, m'apareix una / de més despres dels idiomes. En el moment que canvii d'idioma ja desapareix.

![imagen](https://user-images.githubusercontent.com/17084256/113132088-4806a000-921e-11eb-8797-d542b074aaf5.png)

**Comment by anadal-fundaciobit** [comment]
Surt idioma actual: null

**Comment by jpernia-fundaciobit** [comment]
Es controla al MenuDeslliçant si l'idioma actual és null, el posa per defecte a "ca".
