### ISSUE TITLE
Ordenar elements de la pàgina principal del front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#463]
Depèn de "Anàlisi de ordenar independentment del tipus d'element en el front #460"

Igual que s'ha fet a "Ordenar elements del Menú Desllissant #461" (veure classe MenuDesllisant.js) fer el mateix a LlistatDePlugins.js

**Comment by jagarcia-fundaciobit** [comment]
S'ha realitzat l'ordenació dels elements al LlistatDePlugins.js.
