### ISSUE TITLE
Canviar la configuració del datasource segons els estandars de la CAIB.

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/carpeta#464]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #422"

Segons el document  "Guia de configuració de l'entorn de desenvolupament"
https://www.caib.es/sites/dgtic/ca/estandards_de_desenvolupament/archivopub.do?ctrl=MCRST299ZI339656&id=339656

A l'apartat "4.2. Configuració dels datasources" s'ha de fer l'opció recomanada (Opcio a) diu que
Crear un fitxer XML independent (anomenat nomAplicacio-ds.xml) per a cada aplicació dins del directori JBOSS_HOME\standalone\deployments.

Actualment està configurat com diu  l'opció b.

S'adjunten uns exemples (nota: s'ha de llevar l'extensió .txt): 

[postgresql-projectebase-ds.xml.txt](https://github.com/GovernIB/carpeta/files/6277351/postgresql-projectebase-ds.xml.txt)
[oracle-projectebase-ds.xml.txt](https://github.com/GovernIB/carpeta/files/6277352/oracle-projectebase-ds.xml.txt)
[emiserv-ds.xml.txt](https://github.com/GovernIB/carpeta/files/6284139/emiserv-ds.xml.txt)

**Comment by jagarcia-fundaciobit** [comment]
S'han realitzat els canvis en els fitxers d'oracle i postgresqle de dintre de /scripts/datasources/ per a qué es pugin configurar els datasources sense haver de tocar el fitxer de configuració standalone.xml. Simplement, s'han de copiar al directori de desplegament.

**Comment by jagarcia-fundaciobit** [comment]
S'ha actualitzat també el manual d'instal·lació
