### ISSUE TITLE
Error de javascript en la pantalla de selecció d'entitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#465]
Depèn de "Millores en el Front #423"

En la pantalla de selecció d'entitat es produeix un error de Reactjs: Target container is not a DOM element.

![imagen](https://user-images.githubusercontent.com/17084256/113997990-eadf9f80-9858-11eb-9c03-bba0660ae4bc.png)

**Comment by jpernia-fundaciobit** [comment]
Aquest issue és exactament igual que el que ja es va tancar "Error en la pàgina de selecció d'Entitat #433".
L'anterior es va tancar perquè aquesta pàgina és un jsp, no és un component, i així és normal que doni aquest error. 
Després, aquesta pàgina únicament es visitarà si Carpeta no té definit una Entitat per defecte, i s'accedeix directament a "..../carpetafront/", sense indicar una entitat a la url. Per tant, se suposa que aquesta pàgina no es visitarà quasi mai.
Per tant, s'ha de mirar si és necessari fer res a aquest issue o no.

**Comment by jpernia-fundaciobit** [comment]
Fet!
