### ISSUE TITLE
Icones allargades en el menú deslissant

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#466]
Depèn de "Millores en el Front #423"

En el menú deslissant apareixen les icones allargades tal i com es veu a la captura de pantalla. També es veuen com apagades i no se si millor deixar-les amb el color original.

![imagen](https://user-images.githubusercontent.com/17084256/113998769-abfe1980-9859-11eb-853e-647fd6104fe7.png)

**Comment by jpernia-fundaciobit** [comment]
S'ha llevat l'estil per fer més opaca la icona. També s'han recuperat les proporcions de la imatge però es controla que no pugui ser una imatge massa gran.

![image](https://user-images.githubusercontent.com/17266896/114015477-043d1780-986a-11eb-896b-08619407dcc5.png)
