### ISSUE TITLE
Ordenar scripts de BBDD per versió i no per tipus update schema/data

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#467]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #422"

Actualment els scripts de BBDD estan ordenats per update-data i update-schema cosa que fa que les versions estiguin separades tal i com es veu en la captura.

Aplicar nou format als scripts: update_from_a.b.c_to_x.y.z_data.sql i  update_from_a.b.c_to_x.y.z_schema.sql

![imagen](https://user-images.githubusercontent.com/17084256/113999873-bcfb5a80-985a-11eb-94b5-c31ce8577406.png)

**Comment by jpernia-fundaciobit** [comment]
Fet!
