### ISSUE TITLE
Els errors de Plugin NOTIB no arriben al Front

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#469]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #481"
Depèn de "Mostratge de notificacions i comunicacions del ciutadà #220 "

Error en el PLugin de NOTIB no es mostra al front i deixa la pantalla en blanc. 
Com reproduir: posar un nom de servidor de notib que no existeixi.

Al POJO JSON que es retorna a NOTIB, se li ha de posar d'afegir un camp "error". En el render, si aquest camp no es buit, llavors s'ha de mostrar l'error. En la par servidora, s'ha de capturar l'error i retornar l'objecte POJO buit amb l'error dins del camp "error".

![imagen](https://user-images.githubusercontent.com/17084256/114007944-0ef3ae80-9862-11eb-9d74-732551d92cde.png)

**Comment by jpernia-fundaciobit** [comment]
Fet!
