### ISSUE TITLE
MenuRapid - Problemes amb les icones i els títols de les seccions

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#471]
Depèn de "Millores en el Front #423"

- Amb la darrera actualització, en el menú ràpid no apareixen les icones associades.

- A més, les seccions apareixen amb el camp "Descripció com a títol". Es demana canviar-ho pel nom de la secció.

![image](https://user-images.githubusercontent.com/44995350/114531433-2f4daf80-9c4c-11eb-9d58-9147d5e38471.png)

**Comment by jagarcia-fundaciobit** [comment]
Corregit el problema de la ruta de les imatges  i el alt de la imatge de la seccio que apareixia el camp descripció en comptes del nom. 

![imagen](https://user-images.githubusercontent.com/70194276/114536325-417e1c80-9c51-11eb-91fe-5fbb94767f05.png)
