### ISSUE TITLE
Millorar mètode processException()

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#473]
Depèn de "Millores en el Front #479"

Dins CommonController.java del Front existeix un mètode anomenat processException() que es crida tant des de pàgines web com des de mètodes REST. 
Aquest mètode s'ha de convertir en dos:
     * processExceptionRest(): gestionarà errors REST (farà un log i retornarà en HTML Error 200 i el missatge)
     * processExceptionHtml(): gestinarà errors de pàgines HTML i redireccionarà a una pàgina genèrica de error /error)

**Comment by jpernia-fundaciobit** [comment]
Fet!
