### ISSUE TITLE
Adaptació FRONTAL de CARPETA respecte versió 0.1

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#48]
Refactoritzar el mòdul:
- carpeta-front (actual)
en
- carpeta-front (ProjecteBase)

Cal tenir en compte que la tecnologia del frontal pot ser qualsevol Framework JS, segons els [Estàndards](https://www.caib.es/sites/dgtic/ca/estandards_de_desenvolupament/).

**Comment by jpernia-fundaciobit** [comment]
Es divideix en els següents issues:

- Actualitzar versions versions estils i javascript #52
- Refactoritzar estils i javascripts provinents de Projecte Base #53
- Refactoritzar estructura del front de Carpeta amb React #54
- Adaptar pàgina inicial del front #55
- Adaptar pàgina de tràmits pendents del front #56
- Adaptar pàgina de registres fets del front #57
- Adaptar pàgina de detall de registre del front #58
- Adaptar pàgina de notificacions del front #59
- Adaptar pàgina de dades personals del front #60
- Adaptar pàgina inicial autenticada del front #61
- Adaptar pàgina d'accessibilitat del front #62

**Comment by jpernia-fundaciobit** [comment]
Tancat perquè s'ha subdividit en issues més petits

**Comment by scalafat-dgtic** [comment]
Reobrim com a tasca CAIB per a gestió del projecte.

**Comment by scalafat-dgtic** [comment]
S'associen els següents issues en tasca CAIB:
- #72. Refactoritzar Google Analytics provinent de Projecte Base
- #73. Refactoritzar Modernizr provinent de Projecte Base
- #74. Refactoritzar Acceptar Cookies provinent de Projecte Base

**Comment by jpernia-fundaciobit** [comment]
S'ha creat un nou issue de Carpeta 1.0 i se li han assignat els issues que contenia propis de Carpeta 1.0.

Revisar funcionalitats no resoltes del front #176
