### ISSUE TITLE
Modificar temps d'expiració sessió en el frontal per Propietats

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#482]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #481"

Es demana poder modificar el temps d'expiració del frontal mitjançant una propietat, que ara està, per defecte, a 30 minuts. Mirar si es pot configurar des del backoffice dins "Propietats globals"

**Comment by jpernia-fundaciobit** [comment]
També s'ha corregit error que donava el i18n.changeLanguage d'Inici.js. S'ha canviat import per "import i18n from './i18n';"
La propietat global que s'ha de crear per utilitzar la sessí d'expiració és: es.caib.carpeta.frontsessiontime i és obligatori que hi sigui o no funcionarà l'expiració de sessió. Ho afegiré al manual.

**Comment by jpernia-fundaciobit** [comment]
Si no es crea la propietat global, el sistema té per defecte 30 minuts.
Fet!

**Comment by jpernia-fundaciobit** [comment]
Fet!
