### ISSUE TITLE
Documentar API Dades Obertes amb Swagger

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#486]
Depèn de "Revisió d'Estàndards #337" 

Tal com s'especifica als [Estàndards](https://www.caib.es/sites/dgtic/ca/estandards_de_desenvolupament/archivopub.do?ctrl=MCRST299ZI339655&id=339655), en el punt 6.4 (pàgina 30), documentar l'API Externa de Dades Obertes amb Swagger. Incorporar també, si és possible Swagger-UI.

**Comment by jagarcia-fundaciobit** [comment]
Revisió dels estàndards i s'ha canviar la ruta de consulta /carpetaapi/externa/openapi.json per/carpetaapi/externa/swagger.json. Actualització del Manual d'Integració de Serveis REST dintre la carpeta de documentació (doc).

**Comment by jagarcia-fundaciobit** [comment]
No s'estava generant la informació corresponent a schema. Fets els canvis perqué es generi. 

![imagen](https://user-images.githubusercontent.com/70194276/117443612-aec35b80-af38-11eb-928c-1fbf0faab0a4.png)
