### ISSUE TITLE
Les cridades a accesLogicaEjb.crearAcces() no poden llançar excepcio

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#490]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #528"

Les cridades a accesLogicaEjb.crearAcces() i a logs NO han de llançar excepció. Per un log o per un registre d'accés que falli no hem de deixar a l'usuari penjat.

**Comment by jpernia-fundaciobit** [comment]
S'han posat les cridades a ins un try/catch per mostrar l'error al log quan es produeixi.
