### ISSUE TITLE
Problema de Seguretat al consultar detall de Registres

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#495]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #481"

Al fer el plugin de Registre32 parametritzable, ens hem adonat que hi ha un forat de seguretat en aquest PLugin. Qualsevol podria elegir un numero de Registre Formatejat i accedir a ell sense problema.

(1) Revisar si realment existeix aquest problema: Es pot atacar a http://localhost:8080/carpetafront/#/moduls/registre32/p/GOIB-E-74/2021 amb un numeo de registre que no sigui nostre a veure com actua el sistema.

(2) En el cas de que en el punt (1) es mostri el  Detall de Registre, s'hauran d'afegir les comprobacions oportunes per no mostrar Detalls de Regsitres que no estiguin ssociats a l'usuari autenticat.

**Comment by jpernia-fundaciobit** [comment]
S'ha provat accedint a la url directa d'un detall de registre propi i funciona correctament.
Al intentar accedir a un registre d'un altre usuari, retorna un error de no existència de registre, com es veu a la captura següent:

![image](https://user-images.githubusercontent.com/17266896/118444237-2b9ac600-b6ed-11eb-87ba-1c00db1ba7dc.png)

Per tant, es tanca l'issue perquè no existeix aquest problema.
