### ISSUE TITLE
Canviar sistema de reprendre Tramitació Anònima

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#496]
Com ja sabeu, a la pàgina de presentació del front de Carpeta tenim un enllaç a reprendre una tramitació anònima (veure captura 1) . La programació i manteniment d'aquest codi és molt complicada ja que obre un diàleg, fa cridades REst i el pitjar de tot es que tenim funcionalitat específica de CAIb en el codi del Front (no dins algun Plugin).

    Vos he anant comentant que hi ha hagut novetats en els plugins: Plugins Públics (que no requereixen d'autenticació) i Plugins Parametritzables (Tots els plugins poden rebre un paràmetre i modificar el seu comportament inicial).

    Aplicant aquestes dues millores podriem simplificar aquesta lògica i fer-la simplement un enllaç cap a la parametrització d'un plugin public. Aquest plugin ja està fet i s'anomena "ReprendreTramitSistra" i emprant la següent ruta "http://localhost:8080/carpetafront/#/publicmoduls/reprendretramit/p/V4R4ENCO-NRHYMJT8-T8B7MBNK" ens obriria una pipella per continuar amb el tràmit (Veure captura 2)

Finalment eliminar la funcionalitat de gestió de tramitació anònima de dins TramitacioAnonimaController així com les depèndències de pom.xml del front.

![imagen](https://user-images.githubusercontent.com/17084256/118464177-dbc5fa00-b700-11eb-885c-cc52d4616d12.png)

![imagen](https://user-images.githubusercontent.com/17084256/118464194-e08aae00-b700-11eb-8cf4-488e0ef5e243.png)

**Comment by jagarcia-fundaciobit** [comment]
S'han fet les modificacions a la pàgina d'inici pública. S'ha de tenir en compte que és indispensable tenir configurat el plugin de reprendretramitaciosistra i es important saber la ruta del context actual que s'ha configurat al plugin. La ruta per defecte que s'ha configurat al plugin es "reprendretramit" i és el que s'ha tingut en compte alhora de ficar al javascript. 

Si es té configurada una ruta diferent a la configuració del plugin:

![imagen](https://user-images.githubusercontent.com/70194276/119122737-1f857000-ba2f-11eb-8028-e5fdcaa8f9f5.png)

S'ha de modificar el HTML del camp de Text HTML de login de la entitat amb la ruta correcta: 

![imagen](https://user-images.githubusercontent.com/70194276/119123040-75f2ae80-ba2f-11eb-9dba-6c263c639be4.png)
