### ISSUE TITLE
Document de Migració ha perdut el seu format

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#497]
El document de Migració ha perdut el seu format tal i com es pot observar a la captura.

Jo tenc LibreOffice 7.1.0.3 (x64)

![imagen](https://user-images.githubusercontent.com/17084256/118477939-952bcc00-b70f-11eb-959e-f83c8e8dd49d.png)

**Comment by jpernia-fundaciobit** [comment]
Afegit el logo de la conselleria (portada) i el logo GOIB (lateral de cada pàgina).
