### ISSUE TITLE
Definició Model de Dades

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#50]
Partint de l'experiència amb Regweb, i atenent l'anàlisi funcional #46, definir el model de dades de Carpeta.

**Comment by scalafat-dgtic** [comment]
Es modifiquen els documents de la carpeta /doc a l'estat actual del projecte.
Dins el document d'anàlisi i disseny, s'inclou l'anàlisi funcional i es referencia el model Entitat-Relació.

**Comment by mgonzalez-fundaciobit** [comment]
Pujat la implementació de classes del model de dades. 
commit 17a18616a1f98ca648c46286aaeed3b63ffdc904

**Comment by scalafat-dgtic** [comment]
Es puja la darrera versió del model de dades (v6)

**Comment by scalafat-dgtic** [comment]
S'han pujat els scripts SQL en Oracle per posar en marxa el projecte
