### ISSUE TITLE
Afegir TITOL i SUBTITOL a les Secions

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#500]
Depèn de "Millores en el Front #514"

Les Seccions no tenen ni TITOL ni SUBTITOL com es pot observar a la captura2. Afegir el títol i subtitol que apareix en el llistat d'Elements aquí on s'indica en la captura 2.

![imagen](https://user-images.githubusercontent.com/17084256/118769070-0ab6aa00-b880-11eb-957b-f6fa76c2279b.png)

![imagen](https://user-images.githubusercontent.com/17084256/118768937-df33bf80-b87f-11eb-81c5-53e4cfdbb493.png)

**Comment by jagarcia-fundaciobit** [comment]
Fet. S'ha afegit titol (camp nom) i subtitol (camp descripció) a les seccions.

![imagen](https://user-images.githubusercontent.com/70194276/120981123-a056a280-c777-11eb-9c8d-66090e1d8c32.png)
