### ISSUE TITLE
Manual d'Usuari ha d'incloure descripció dels Plugins

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#503]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #512"
Depèn de "Redacció i revisió dels manuals del projecte #177"

(1) En el Manual d'Usuari s'han d'incloure la descripció de tots els Plugins disponibles tal i com es fa en el manual de POrtafib. Veure pàgina 59 del manual https://github.com/GovernIB/portafib/blob/portafib-2.0/doc/Manual_de_Usuari_de_PortaFIB.odt 

(2) Cada Plugin en l'arrel conté un fitxer plugin.properties.sample que pareix que esta desactualitzat. Revisar-los tots. 

(3) Informar als programadors que canvis en les propietats del Plugin, significa que s'ha d'actualitzar:
            (3.1) Plugins de BBDD emprant scripts SQL
            (3.2) Manula d'Usuari
            (3.3) Fitxer plugin.properties.sample

**Comment by jpernia-fundaciobit** [comment]
Pujat el Manual d'usuari.
Queda pendent actualitzar els fitxers  plugin.properties.sample.

**Comment by jagarcia-fundaciobit** [comment]
Actualitzat el manual d'usuari amb la darrera configuració dels plugins de pinbal. 
Revisats tots els fitxers plugin.properties.sample.
