### ISSUE TITLE
Problema al triar una entitat inicial al front, després de canviar idioma

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#505]
Depèn de "Millores en el Front #479"

Com a Usuari del front
vull que poder canviar l'idioma a entitat.jsp
per a poder accedir al front de l'entitat que vull amb l'idioma triat

Si a entitat.jsp es canvia l'idioma abans de triar una entitat en concret, després no accedeix a l'entitat, es queda a carpetafront/entitat. Abans funcionava correctament.

**Comment by anadal-fundaciobit** [comment]
Solucionat. Ignorant el canvi d'idioma.
