### ISSUE TITLE
Consulta de Serveis PINBAL REST

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#508]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #512"
Depèn de "Obtenció i mostratge de dades del ciutadà #221"

S'ha de fer una consulta dels Serveis Pinbal que actualment s'ofereixen via REST per si hi hagues possibilitat d'incorporar-los a Carpeta com a PLugin.
Simó comenta que hi ha un servei PINBAL REST des de Projecte BASE. Revisar-lo per si es pot reaprofitar disn Carpeta.

**Comment by jagarcia-fundaciobit** [comment]
S'ha revisat com es fan les cridades REST al projecte base per adaptar-ho al projecte de Carpeta. Es crea la nova issue per fer la corresponent adaptació: "Adaptar la cridada al Client REST del plugin de pinbalpolicia #523"

@scalafat-dgtic, S'han revisat els altres serveis que es podrien implementar a Carpeta. Interessa implementar la consulta de "Obtener el justificante de estar al corriente de las obligaciones tributarias" ? Si es així, obrim nova issue per fer la corresponent integració amb aquest servei.
