### ISSUE TITLE
Eliminar fitxers descarregats d'altres webs

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#516]
Depèn de "Millores en el Front #514 "

Fer que els següents fitxers de inici.jsp es descarreguin del propi servidor i no de servidors externs.

![imagen](https://user-images.githubusercontent.com/17084256/120166697-29605d80-c1fd-11eb-9801-e3c528c7c0bf.png)

**Comment by jpernia-fundaciobit** [comment]
Fet!
