### ISSUE TITLE
Error en el plugin de Sistra emprant usuari representant 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#517]
Depèn de "Fer proves amb Certificats de Representant de Persona i d'Empresa #507"

Plugin de Sistra dóna un error quan es logueja un usuari amb certificat de representant. Pareix també que l'error no es pot mostrar.

![imagen](https://user-images.githubusercontent.com/17084256/120179431-dd1c1a00-c20a-11eb-8e09-f955750034d5.png)

**Comment by jagarcia-fundaciobit** [comment]
S'ha corregit l'error indicat a aquesta issue. 

A més, s'ha corregit un error derivat del canvi dels input type TEXT a DATE del cercador, error d'estils del cercador del plugin de regweb i que per defecte, quan entres al plugin de regweb, no es faci cap cridada a l'API per evitar cridades innecessaries al sistema de REGWEB.
