### ISSUE TITLE
Carregar al front una fulla d'estils associada a una entitat a través del back

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#536]
Depèn de "Millores en el Front #527"

Com a Administrador de l'aplicació
vull poder afegir una fulla d'estils al back
per a que es vegin els canvis al front

S'ha detectat que, encara que es pot carregar una fulla d'estils a una entitat a través del backoffice, aquesta no es carrega al front. Per això no es carreguen els seus estils.
S'ha de carregar al front.

**Comment by jagarcia-fundaciobit** [comment]
S'ha afegit al head del front, un enllaç a la pàgina d'estils CSS asociada a la entitat autenticada. La url que càrrega els estils és accesible des de: /carpetafront/webui/customcss/*[codiEntitat]*

En el cas de la entitat amb codi caib, la url és: http://localhost:8080/carpetafront/webui/customcss/caib
