### ISSUE TITLE
Revisió principis Comprensible i Perceptible - Accessibilitat

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#538]
Depèn de "Millores en el Front #527"

**Com a** Administrador de l'aplicació
**vull** adaptar el front
**per a** que sigui accessible en el principi "Comprensible i Perceptible"

S'han detectat algunes millores en quant al principi "Comprensible i Perceptible":

**COMPRENSIBLE**

3.3.1 Identificación de errores - En els formularis de /tramits i /registres

    Identificar camps obligatoris no completats i informar mitjançant text (sé que seran casos extremadament aïllats, però s'ha de tenir en compte), en el seu enviament
    Si les dades que s'introdueixen en els camps no tenen el format correcte, proporcionar descripcions textuals dels errors. Exemples:
        Si data inici > data fi
        si pos l'any 0 al camp de les dates se queda pensant infinitament (per ventura mostrar missatge quan alguna dada no sigui possible, p.ex: comprovar el rang dels anys 1900-2100 i evitar dies i mesos impossibles)
            s'ha de dir que el propi input ja filtra el 90% dels errors, però és possible trucar-ho o equivocar-se si es fa per teclat.
        excés de caràcters en el núm de registre

3.3.2 Etiquetas o instrucciones - Ens els formularis de /tramits i /registres

    Identificar camps de formulari que són obligatoris
    a /registres posar un placeholder al camp del número de registre?

**PERCEPTIBLE**

1.3.1 Información y relaciones

    a /mapaweb, els enllaços no han de ser h3s (parlat per telèfon)

1.3.4. Orientación

    A "les meves notificacions" el text surt de les capses
    Tot i que al principi 1.3.4 només parla d'orientació, mirant el "responsive", caldria revisar mides dels textos, alineacions i els espais en blanc. Per exemple:

![image](https://user-images.githubusercontent.com/17266896/125030142-e494d580-e08a-11eb-8c37-b3b6e7be63b6.png)

1.4.1 Uso del color

    El contrast del color entre els enllaços del footer respecte a l'altre text ha de ser superior a 3:1 (ara 2,3:1)
    El contrast del color entre els enllaços de la home sense autenticar (Cl@ve i Bustia d'atenció) no compleixen el contrast 3:1 respecte al text que el precedeix (ara, 1,2:1)
    El contrast del color entre els enllaços en el MODAL d'ajuda i la resta de text que el precedeix és de 1,3:1 enlloc de 3:1

1.4.3 Contraste (mínimo)

    La 'x' del modal d'error té un contrast de 2,6:1 respecte al color de background de l'alert.

1.4.11 Contraste en elementos no textuales

    El contrast del contorn de les capses de la HOME, seccions i plugins 'compostos' envers el background és de 1,3:1 enlloc de 3:1. Per exemple, gris (#808080)
    El mateix amb els inputs dels formularis 
    border-bottom del menú ràpid, canviar a gris, també.

1.4.13 Contenido en hover o focus

    /registres - El hover de l'extracte de la taula de registres podria ser visitable com hem fet en el detall de Registre amb l'Estat?

**Comment by jagarcia-fundaciobit** [comment]
S'ha afegit les validacions al formularis dels plugins de Sistra i Regweb que controlen les dates d'inici i fi (punt 3.3.1 Identificación de errores). així com un max-length de 25 caràcters al input de número de registre del plugin de regweb i un placeholder (punt 3.3.2 Etiquetas o instrucciones ).
