### ISSUE TITLE
Error al canviar entre plugins amb el Menú Ràpid del Front

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#539]
Depèn de "Millores en el Front #527"

**Com a** Usuari de l'aplicació
**vull** poder accedir a les diferents opcions del menú ràpid
**per a** navegar de forma correcta sense que apareguin errors

S'ha detectat un error recorrent al canviar entre opcions del menú ràpid del front.

Fent la revisió d'accessibilitat i sense tocar el frontal de manera insistent (aturar, mirar els principis d'accessibilitat amb 2 eines amb la pàgina "quieta"), quan es torna a pitjar sobre una de les opcions del menú ràpid (per exemple) apareix un error com aquest en pantalla i que no deixa fer res.

De vegades, inclús, no deixa ni pitjar el menú d'hamburguesa per tancar sessió. 

Si fos un tema de la sessió, segueix passant amb la propietat global a 120 minuts i, per segur que no ha passat tant de temps sense tocar la pàgina:

![image](https://user-images.githubusercontent.com/17266896/125030801-fb87f780-e08b-11eb-8698-3c58210bcc45.png)

![image](https://user-images.githubusercontent.com/17266896/125030817-02166f00-e08c-11eb-8fb5-521e7b8e8231.png)

**Comment by jagarcia-fundaciobit** [comment]
S'ha controlat a la cridada d'axios quan es produeix aquest error i es redirecciona a l'usuari a la pàgina home.
