### ISSUE TITLE
 Anexos confidenciales

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#544]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #528"

Correu de Eduardo Arrivi del 15 Jul de 2021 sobre les cridades a consultes de registres:

```
Buenas,

Unas consideraciones sobre los anexos confidenciales en la capa de WS.

Cuándo se invoquen los métodos obtenerAsientoRegistral, obtenerAsientoCiudadano de un asiento registral
 que contenga anexos confidenciales, se retornará la el AnexoWs pero con el campo confidencial a true.

Eso, en el caso de CARPETA, tendrá que haber una gestión específica ya que no contendrán el documento 
y denerían deshabilitar su descarga.

Cuándo un AnexoWs sea confidencial (anexoWs.getconfidencial() == true) se informarán los siguientes campos:

    anexoWs.getHash()
    anexoWs.getTamanoFichero()
    anexoWs.getNombreFicheroAnexado()


Saludos.
```

**Comment by jagarcia-fundaciobit** [comment]
Per obtenir el detall de registre a Carpeta, s'utilitza el mètode obtenerAsientoCiudadanoCarpeta que ens retorna el detall de registre i un llistat d'annexes de tipus FileInfoWs. 

Falta fer els canvis a aquesta classe per obtenir aquesta informació ja que ara per ara no la tenim disponible.

**Comment by jagarcia-fundaciobit** [comment]
Quan es troba un annexe marcat com a confidencial, no es permet la descàrrega i es mostra l'etiqueta de Confidencial en el seu lloc.

![imagen](https://user-images.githubusercontent.com/70194276/127475782-4bfe0f8e-22a9-4d26-ab89-8d8ab84b046a.png)
