### ISSUE TITLE
Revisió Responsive i principi Perceptible - Accessibilitat

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#548]
**Com a** Administrador de l'aplicació
**vull** revisar el disseny del front 
**per a** que es vegi bé a tablets i mòbils i revisar el principi de "Perceptible"

Revisar totes les pantalles del front perqué es vegin bé a dispositius mòbils. Posar especial èmfasi en millores del principi d'accessiblitat "Perceptible" que es descriu a continuació.

**PERCEPTIBLE**

1.3.4. Orientación

    A "les meves notificacions" el text surt de les capses
    Tot i que al principi 1.3.4 només parla d'orientació, mirant el "responsive", caldria revisar mides dels textos, alineacions i els espais en blanc. Per exemple:

![image](https://user-images.githubusercontent.com/17266896/125030142-e494d580-e08a-11eb-8c37-b3b6e7be63b6.png)

**Comment by jagarcia-fundaciobit** [comment]
Fets els canvis. He posat la tasca a To-Do per realitzar un repàs del responsive abans de tancar el sprint.

**Comment by jpernia-fundaciobit** [comment]
Revisada la part Responsive.
