### ISSUE TITLE
Error de tipus MIME en la descàrrega d'un fitxer CSS

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#549]
Depèn de PROJECT

Aquest és una captura de la Consola de Desenvolupament del navegador Firefox visualitzant el front de Carpeta. 

Revisar que està passant.

![imagen](https://user-images.githubusercontent.com/17084256/126114678-88f8608b-4862-4622-b22f-e9852c36d1cc.png)

**Comment by jagarcia-fundaciobit** [comment]
Solucionat.
