### ISSUE TITLE
Migrar tots els Plugins de Front d'HTML a ReactJS

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#554]
Per millorar l'eficiència i homogeneitzar els sistema de Plugins de Front, el millor es Migrar tots els Plugins de Front d'HTML a ReactJS.

Revisar tots els pLugins HTML i per cada un d'ells crear un ISSUE de migració a ReactJS

**Comment by jpernia-fundaciobit** [comment]
Fet!
