### ISSUE TITLE
Integració del Servei de consulta d'estar matriculat a centre educatiu

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#557]
Com a usuari
Vull poder acceder a la consulta d'estar matriculat a centre educatiu
Per tal d'obtenir aquesta informació

Consultar la definició del servei: 
https://www.caib.es/sites/interoperabilitat/ca/servei_propi_scmcedu-80465/

**Comment by jpernia-fundaciobit** [comment]
El plugin està creat en local. Ara mateix dóna error 500 al fer la petició i s'està mirant perquè fa això. Una vegada funcioni la connexió, s'haurà de fer una pantalla al front del plugin per introduir les dades necessàries per fer la petició.

**Comment by jpernia-fundaciobit** [comment]
No es pot tancar definitivament perquè s'han d'obtenir dades al front per fer la petició.
A més, no es pot provar el plugin al obtenir error 500.
Es passa al següent sprint.

**Comment by jpernia-fundaciobit** [comment]
Pendent de realitzar les proves una vegada funcioni l'entorn de Proves de Pinbal.

**Comment by jpernia-fundaciobit** [comment]
Està fet, menys l'opció on es posar un tutor i la data de naixement del titular, perqupe retorna error des de Pinbal, i també dóna el mateix error a través de la web.

**Comment by jpernia-fundaciobit** [comment]
Fet!
