### ISSUE TITLE
Error d'EL en les notificacions

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#568]
En entrar a les notificacions, corresponents al plugin de NOTIB, apareix el següent error:

![image](https://user-images.githubusercontent.com/44995350/131492524-539e96bb-0b63-41ee-b772-19f8e114e55b.png)

**Comment by scalafat-dgtic** [comment]
També passa a "Altres comunicacions". Entenc que és cosa del botó de Tornar

![image](https://user-images.githubusercontent.com/44995350/131493494-14d7e9ed-1173-481e-b348-0536a179bd80.png)

**Comment by jpernia-fundaciobit** [comment]
Ara mateix he pujat un error que donava a "Altres Comunicacions". 
A les opcions de NOTIB no hauria de donar.
He pujat tot el que s'ha modificat. 
En local tot funciona. Si qualque cosa no funciona, tornar a avisar.

**Comment by jpernia-fundaciobit** [comment]
Fet!!!
