### ISSUE TITLE
Unificar taules de Regweb32 i Sistra. Revisar paginació

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#575]
Com a usuari
Vull poder veure les taules dels plugins iguals
Per tal de tenir la mateixa vista

Posar la mateixa vista de taula de Sistra a Regweb32. A més, s'ha de revisar la paginació perquè no mostra els resultats com toca.

**Comment by jagarcia-fundaciobit** [comment]
Correcció del error a la páginació.

**Comment by jagarcia-fundaciobit** [comment]
Tanco la issue perquè la unificació la farem quan passem els plugins a React amb la tasca #554
