### ISSUE TITLE
Implantació d'APODERA a Carpeta Front 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#577]
Comentari de @atrobat-dgtic :

_Bones, lo de apodera li vaig comentar a n'en Salvador, ho ha de traslladar a sa jurista de sa OAE i s'ha de veure des de quin punt gestionam d'accés com apoderat. Va comentar s'opció de a loginib fer una capceta per entrar com apoderat de qualcú. Aquest es un tema que segurament ja fins es setembre no mos tornaran a dir res._

Si lo de Apodera per LoginIB es retrases  molt, s'hauria d'avaluar la possibilitat de implantar-ho directament a Carpeta. L'estudi ja està fet:  Estudi de @PODERA #522

**Comment by jpernia-fundaciobit** [comment]
Solucionat, era un problema d'uns canvis fets en local a la DGMAD de persistence.xml.

**Comment by jpernia-fundaciobit** [comment]
Fet!
