### ISSUE TITLE
Crear nous camps editables (Accessibilitat i Avís Legal) al backoffice pel rol Administrador d'Entitat

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#579]
Com a administrador d'entitat
Vull poder editar els camps Accessibilitat i Avís Legal de la meva entitat
Per tal de poder modificar el seu contingut

Afegir aquests dos camps al model i crear la seva gestió des del backoffice i que es mostri al frontoffice.

**Comment by jagarcia-fundaciobit** [comment]
Issue duplicada. Canvis fets a la issue #581.
