### ISSUE TITLE
Adaptar pàgina de detall de registre del front

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#58]
Depèn de "Millores en la UI del Front #246"

**Com a** desenvolupador de l'aplicació **vull** adaptar la pàgina de detall de registre del front de Carpeta 0.0.1 a React **per** utilitzar la nova tecnologia i estils

**Comment by mgonzalez-fundaciobit** [comment]
Revisar informació obligatoria que ha de venir de regweb3 i ve buida, com oficina, interessat. etc.

**Comment by mgonzalez-fundaciobit** [comment]
Revisant regweb3,  hi ha un conjunt de dades que regweb3 no envia. Actualment es mostren buides, s'hauria de veure si en un futur les enviaràn o si les podem llevar definitivament. Els camps són:
Oficina
Tipus de documentació
Idioma
Interessats.

**Comment by scalafat-dgtic** [comment]
- Indicar si és presencial o no
- L'enumeració dels annexos i interessats que comenci per 1
- El nom de l'interessat ha de sortir complet (nom i llinatges)
- El tipus de persona ha de sortir "Persona física" o "Persona jurídica" o la tipologia que toca, enlloc del valor actual.
- En els Annexos, ha d'aparèixer el Tipus Mime (si és PDF, txt...) i ha de preveure l'opció d'un botó de descàrrega de l'annex, quan això sigui possible

![imagen](https://user-images.githubusercontent.com/44995350/101617374-d73e3c80-3a10-11eb-893e-b2c7966461e9.png)

**Comment by mgonzalez-fundaciobit** [comment]
S'ha fet tot el que se demana, ara es treu directament el tipus mime, pero crec que a l'usuari li hem de posar més intuitiu.
Ara surt application/pdf i  seria millor que digués PDF tot sol.

**Comment by mgonzalez-fundaciobit** [comment]
Problemes mostrant el tipus mime dels annexes i mostrar el tipus mime més entendible per l'usuari.

**Comment by mgonzalez-fundaciobit** [comment]
Ara ja es mostren els tipus mime per a que ho entenguin millor els usuaris. He possat tots els tipus mime que poden venir de regweb3 i que són acceptats per SIR. Si en ve un que no hi és a la llista simplement no es mostra.

**Comment by mgonzalez-fundaciobit** [comment]
El justificant surt al llistat d'annexes i no al requadre de Justificant.
Veure imatge
![Image 31040680964](https://user-images.githubusercontent.com/17267873/105502458-c0546080-5cc5-11eb-8cbd-65f249b9ccdd.png)


S'ha de llevar del llistat i s'ha de mostrar al seu requadre.

**Comment by mgonzalez-fundaciobit** [comment]
Per resoldre aquest punt s'ha hagut de crear una nova propietat al plugin de regweb3. La propietat es la url del concvs d'on descarregar el justificant.
La propietat és: 
es.caib.carpeta.pluginsib.carpetafront.regweb3.concsv.url=https://dev.caib.es/concsv/view.xhtml?hash=
