### ISSUE TITLE
Actualitzar Plugins de UserInformation a la versió 3.0.0

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#584]
Actualment s'està utilitzant l'API de UserInformation 2.0.0. S'hauria d'actualitzar a la 3.0.0 preparada per JDK 1.8 i 11.

L'API 3.0.0 està pendent de provar-se a PRE (@acuevas-dgtic )

**Comment by fbosch-fundaciobit** [comment]
S'ha actualitzat la versió a la 3.0.0 i s'han solventat els conflictes amb les altres dependències.
