### ISSUE TITLE
No apareixen els camps informats des de Regweb Expone/Solicita

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#600]
Al front de Carpeta, al detall de registre del plugin de Regweb32 no es mostren els camps informats des de Regweb d'Expone/Solicita. A Carpeta 0.1 sí que surten.
S'han d'afegir.

![image](https://user-images.githubusercontent.com/17266896/137722082-a561725d-1337-48fd-9557-bc0fda687694.png)

**Comment by jagarcia-fundaciobit** [comment]
S'han afegit els camps al component de detall de registre.
