### ISSUE TITLE
Refactoritzar la paginació del plugin de Regweb32

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#610]
Adaptar la paginació del plugin de Regweb32 del front als canvis fets a Registre.

**Comment by jagarcia-fundaciobit** [comment]
S'ha actualitzat a la versió 2.3.4 de Regweb al pom.xml i s'han afegit els nous paràmetres de cerca al métode obtenerAsientosCiudadanoCarpeta.
