### ISSUE TITLE
Crear un apartat de FAQ visible al front i editable al backoffice

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#616]
Com a administrador
Vull poder consultar crear i editar unes FAQ al back
Per tal que el ciutadà les pugui consultar al front

**Comment by atrobat-dgtic** [comment]
El model a tenir com a referència per implementar aquesta faq seria aquest:

https://www.euskadi.eus/documentacion/guia-de-uso-de-mi-carpeta/web01-sede/es/

**Comment by jpernia-fundaciobit** [comment]
Fet!
