### ISSUE TITLE
Millora de la informació mostrada als logs d'Accessos al backoffice

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#619]
Com a administrador
Vull veure tota la informació possible als Accessos del backoffice
Per no tenir informació que no sigui útil

S'han trobat diverses coses:

**1- Error al llistar accessos de plugins que ja no existeixen a la BBDD.**

Dóna el següent error:

12:48:56,158 WARN  [es.caib.carpeta.back.controller.adminentitat.AccesAdminEntitatController] (default task-56) Al cridar al mapping per la clau '85' ha retornat un valor null.: java.lang.Exception
        at deployment.carpeta.ear.carpeta-back.war//org.fundaciobit.genapp.common.web.controller.CommonBaseController.fillValuesToGroupByItems(CommonBaseController.java:354)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.controller.webdb.AccesController.fillReferencesForList(AccesController.java:201)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.controller.webdb.AccesController.llistat(AccesController.java:166)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.controller.webdb.AccesController.llistatPaginat(AccesController.java:89)

**2- Al accedir al plugin Tramitació Anònima, es crea un log d'accés però sense Adreça IP ni data d'accés.**

![image](https://user-images.githubusercontent.com/17266896/142198405-90e9cbdc-a66b-4690-b986-63736e260d56.png)

**Comment by jpernia-fundaciobit** [comment]
El punt 2 està solventat.
El punt 1 s'ha demanat a la DGMAD què fer. Aquest problema passa quan es vol mostrar un log d'accés a un plugin que s'ha eliminat, per tant, no troba la traducció del nom del plugin. Per això dóna el "java.lang.Exception". S'han proposat vàries alternatives: - Mostrar l'identificador del plugin antic. - Mostrar un text de "Plugin eliminat". - Quan s'elimina un plugin, que s'esborrin els seus logs.

**Comment by jpernia-fundaciobit** [comment]
Per la resolució del punt 2, s'ha acordat que:
- Si s'esborra un plugin del rol de SuperAdministrador, s'esborraran tots els logs d'accessos d'aquest plugin de totes les entitats que el tenguin configurat.
- Si no es vol que el punt anterior passi, enlloc d'esborrar aquest pluguin, el que s'ha de fer és desactivar-lo.
- Si s'esborra o desactiva el plugin d'entitat referent a aquest plugin, no s'ha de fer res, perquè el plugin encara existeix i es poden mostrar les traduccions als logs d'accessos.

**Comment by anadal-fundaciobit** [comment]
Solucionat. També s'han afegit Logs i Accessos
