### ISSUE TITLE
Afegir filtre de dates al plugin de NOTIB (front)

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#649]
Poder afegir filtre de dates al formulari de cerques del plugin NOTIB. 
Està pendent d'estar disponible des de NOTIB: https://github.com/GovernIB/notib/issues/696

**Comment by scalafat-dgtic** [comment]
Ja es pot dur a terme. Els canvis necessaris ja estan pujats a NOTIB-PRO

**Comment by jpernia-fundaciobit** [comment]
Fet!

**Comment by jpernia-fundaciobit** [comment]
Es reobri per estudiar aquests casos:

A la primera, cercam només les notificacions en les dates assenyalades i a la segona ho cercam tot a les mateixes dates.
A la primera en surten només 3; a la segona i tercera captura se veu que tenim 6 notificacions i comunicacions (5 notificacions i 1 comunicació).

Fent el filtre correctament, a la primera captura haurien de sortir les 5 notificacions.

![Image 234981182537](https://user-images.githubusercontent.com/17266896/174269631-0b8ab506-c488-43f0-9092-4ce10dac7af1.png)

![Image 169651043840](https://user-images.githubusercontent.com/17266896/174269683-5725bb10-41ab-4b8c-97a8-5babaf246f81.png)

![Image 467921898004](https://user-images.githubusercontent.com/17266896/174269736-451b8651-4ee7-4223-ab7e-25eb9d523aad.png)

**Comment by jpernia-fundaciobit** [comment]
Fet!!

**Comment by jpernia-fundaciobit** [comment]
Fet!
