### ISSUE TITLE
Crear icona per l'App

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#668]
Crear la icona per la icona de l'App que apareixerà a les versions mòbils.

**Comment by jpernia-fundaciobit** [comment]
Es marca com a "Pendent de tercer" perquè s'han passat propostes a la DGMAD i s'està esperant a que es validi alguna o s'hagin de fer canvis sobre alguna de les propostes.

**Comment by anadal-fundaciobit** [comment]
Ja en té una.
