### ISSUE TITLE
Plugin SISTRA - Ocultació de tràmits antics

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#670]
Arran de les converses amb APB i OTAE i amb l'objectiu d'unificació de criteris amb la purga/persistència de tràmits de Sistra2, es sol·licita filtrar els tràmits de Sistra1 que tenguin més de 3 mesos (o 90 dies).

**Comment by jpernia-fundaciobit** [comment]
Fet!
