### ISSUE TITLE
Mostratge d'assentaments registrals del ciutadà

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#68]
A nivell funcional, es vol que el ciutadà pugui veure la seva llista d'assentaments registrals en el frontal. A més, prement sobre un dels seus assentaments registrals se li mostrarà un detall del mateix.

Implicaria, doncs:
- Fer ús de l'API de Regweb per obtenir els assentaments registrals del ciutadà
- Una vegada desenvolupats #57 i #58, mostrar aquesta informació obtinguda en el punt anterior. 

Funcionalitat similar a la ja existent a CARPETA 0.1
<hr/>

El mateix que s'ha fet pel plugin de SISTRA s'ha de fer per registre.

**Comment by scalafat-dgtic** [comment]
Sabent que #29 requereix un esforç per part de REGWEB3, estaria bé poder tenir-ho en el moment de desplegar CARPETA a producció (o abans amb CARPETA 0.1). Igual que la obtenció del justificant de registre.

En parlam

**Comment by mgonzalez-fundaciobit** [comment]
Acabat el detall del registre també.

**Comment by anadal-fundaciobit** [comment]
Pertany a Integració amb REGWEB3 #130

**Comment by mgonzalez-fundaciobit** [comment]
S'ha detectat que regweb3 no envia un conjunt de dades que són obligatories al detall del registre i s'ha hagut de controllar que si són buides no es mostrin, si no el detall donava un error.

**Comment by mgonzalez-fundaciobit** [comment]
Se tanca aquest i s'obir el #58
