### ISSUE TITLE
Plugin d'Apodera no gestiona corectament els errors

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#680]
Quan per exemple el certificat no es correcte, la ruta al certificat no es correcte o fa falta alguna propietat llavors llança un error no descriptiu com el que es mostra a la captura: Fer que l'error arribi al ciutada correctament.

![imagen](https://user-images.githubusercontent.com/17084256/172140375-5ec24620-5d55-4a56-ade4-042cf5dfbed3.png)

**Comment by jpernia-fundaciobit** [comment]
Fet! S'ha canviat a tots els components i plugins on mostrava el mateix error.
