### ISSUE TITLE
SWAGGER - Modificar les urls a l'hora de provar els mètodes d'API Externa

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#685]
Al Swagger de l'API Externa, si es vol provar el mètode de les estadístiques, en seleccionar "Try it out", es desplega un botó "Execute" on es posen urls de prova. En aquestes, no apareixen les urls de l'entorn, si no les de localhost

![image](https://user-images.githubusercontent.com/44995350/179738710-eb5d2587-4652-47fb-bb07-4988b6033c02.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat.
