### ISSUE TITLE
Actualitzar versió API externa de SISTRAMIT

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#687]
A la versió 1.3.2 de SISTRA2 s'han realitzat canvis sobre l'API externa de SISTRAMIT amb l'objectiu de que, en recuperar un tràmit de SISTRA2, en cas de que l'autenticació a CARPETA consti informació de representant, es pugui enviar a SISTRAMIT.

Segons Indra, aquests canvis no afecten a la versió actual de CARPETA però convé actualitzar-ho.

A la nova versió, en realitzar una cridada a l'API externa de SISTRAMIT, a la funció /ticketAcceso, aquesta permet enviar la informació de representant en els paràmetres de la cridada.

**Comment by anadal-fundaciobit** [comment]
Actualitzat. No ho he pogut provar ja que no tenc certificat amb usuri representant amb Tràmits
