### ISSUE TITLE
APODERA - Ocultar apartat tràmits

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#699]
Des de la OAE s'ha considerat millor ocultar l'apartat tràmits dins de cada apoderament, per evitar confusions.

![image](https://user-images.githubusercontent.com/44995350/192208353-c83d64ad-d596-4943-a65a-cd5a8591ecf1.png)

**Comment by fbosch-fundaciobit** [comment]
S'han fet els canvis de codi de front per ocultar la informació. Queda pendent testejar amb apoderaments que tinguin tràmits.

**Comment by scalafat-dgtic** [comment]
Pujats els canvis a DEV i testejat que no apareix. Tancam issue

Es mostra comparació entre v1.1.20 de DEV i v1.1.19 de PRE

![image](https://user-images.githubusercontent.com/44995350/201091505-1f2baa91-be3f-4744-a2b4-939c24acb4de.png)
