### ISSUE TITLE
Integració amb SISTRA1 dins de Back

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#70]
A nivell funcional, es vol que el ciutadà pugui veure els tràmits de SISTRA1 que estan inacabats.

Implica:
- Fer ús de l'API de SISTRA1 per obtenir els tràmits de SISTRA1 inacabats
- Una vegada desenvolupat #56, mostrar-los per pantalla i que el ciutadà els pugui reprendre.

Atès que hi ha un bug en la represa de tràmits a SISTRA1, queda pendent de que INDRA ho solucioni, abans de fer res.

Funcionalitat similar a CARPETA 0.1

**Comment by anadal-fundaciobit** [comment]
S'ha implementat dins BACK amb sistema de prova de plugin.
