### ISSUE TITLE
Actualització API NOTIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#706]
De NOTIB ja han pujat a DEV els canvis per a la visibilitat dels estats de les notificacions. Per si podeu embestir-ho en poder.

Aquí te deix captura de les respostes rebudes en swagger (v2 vs v1) i t'adjunt el document que ens va passar Limit

![imatge](https://user-images.githubusercontent.com/17084256/195514042-6d6abeab-5e94-49a4-92f1-b0d49d37d736.png)

[20220804_NOTIB_000_DGMADLOT2_v2 (1).pdf](https://github.com/GovernIB/carpeta/files/9771225/20220804_NOTIB_000_DGMADLOT2_v2.1.pdf)

**Comment by fbosch-fundaciobit** [comment]
S'ha actualizat la API de Notib a la V2:

![image](https://user-images.githubusercontent.com/40387703/200839259-20c06b43-efc0-46b2-9ddc-5369a4909988.png)


pom.xml del plugin de Notib
![image](https://user-images.githubusercontent.com/40387703/200839327-f43df2c2-3cbb-48d2-981b-341fe72681e1.png)
