### ISSUE TITLE
Pantalla de Apoderaments no indica quan no hi ha apoderaments

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#708]
Pantalla de Apoderaments no indica quan no hi ha apoderaments

![imatge](https://user-images.githubusercontent.com/17084256/196389501-0a25beb2-2414-4947-a29c-9b761eefcfc9.png)

En entorn Desktop no s'ha de veure la capçalera de la taula, i ha de sortir també el missatge de que no hi ha apoderaments.

![image](https://user-images.githubusercontent.com/40387703/196411617-4b891ba0-39c6-44bf-a0b0-95b964def56a.png)

**Comment by fbosch-fundaciobit** [comment]
Quan un usuari entra al plugin de Apodera, ja no es pinta la taula d'apoderaments, i en canvi apareix un missatge que informa de que no hi ha apoderaments:

![image](https://user-images.githubusercontent.com/40387703/196664757-bde107ca-d2e1-4751-bdac-1fb057ec2978.png)


![image](https://user-images.githubusercontent.com/40387703/196664844-648367d4-911d-43b3-a15f-581219373a0b.png)

**Comment by anadal-fundaciobit** [comment]
Provar amb elements en el llistat.

**Comment by fbosch-fundaciobit** [comment]
La consulta dels apoderaments quan intent mostrar la pantalla d'apoderaments amb un Usuari que si te apoderaments, dona un error de tiemout.

![image](https://user-images.githubusercontent.com/40387703/197141160-4e343458-8a25-4885-86e4-028394af45db.png)

![image](https://user-images.githubusercontent.com/40387703/197141205-60a063d2-f11f-47f4-9f4e-75367b5084aa.png)


S'esta investigant aquest error abans de tancar aquest Issue.

**Comment by fbosch-fundaciobit** [comment]
Ja apareixen els missatges de que no s'han trobat apoderaments correctament, i es pinten les taules d'apoderament correctament:

![image](https://user-images.githubusercontent.com/40387703/197491847-ef85b967-868b-47e7-995f-7576c9105ae6.png)

![image](https://user-images.githubusercontent.com/40387703/197491917-51247ea4-499f-49a4-9024-6c1570be9afc.png)

![image](https://user-images.githubusercontent.com/40387703/197492551-4c31de82-7043-43ae-a2f9-b02404b91816.png)

![image](https://user-images.githubusercontent.com/40387703/197492620-9cc3a46e-d709-4e5e-84e9-9180ab80f194.png)
