### ISSUE TITLE
Vista Mòbil del plugin "Els Meus Expedients"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#718]
Ve del PLugin  "Revisar Plugin "Els Meus Expedients" #717 "

Només es mostra la informació via taula i s'ha de mostrar tipus capsa per dispositius mòbils.

**Comment by fbosch-fundaciobit** [comment]
S'ha creat la vista mòbil del plugin els meus expedients:

![image](https://user-images.githubusercontent.com/40387703/203541113-778aa902-c6e8-4680-a99e-fe40fa9a333d.png)
