### ISSUE TITLE
Plugin de "Els meus Expedients": Aïllar en un Component la presentació de Dades en format Taula

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#720]
(1) Crear un Component (classe Javascript) que donat una ristra de títols i una matriu de valors les dibuixi en una Taula.  Aquest component es podria anomenar RenderTable

(2) El component RenderTable segons si és un Dispositiu d'Escriptori o un Dispositiu Mòbil cridarà al Component RenderTableDesktop o RenderTableMobile respectivament. El primer dibuixarà les dades en format '< table >' de HTML i el segon ho renderitzarà en format caixes (similar al Plugin d'Apodera)

**Comment by fbosch-fundaciobit** [comment]
S'han implementat els components genèrics RenderTable.js, RenderTableDesktop.js i RenderTableMobile.js, que es fan servir al plugin de Expedients per ara:

![image](https://user-images.githubusercontent.com/40387703/204478752-3518e285-1b7b-46b3-ad45-1a4541259d21.png)

![image](https://user-images.githubusercontent.com/40387703/204478913-05b52b98-cdcd-4136-b1fc-7694bca6a4f0.png)
