### ISSUE TITLE
Plugin elsMeusExpedients: poder afegir filtres de forma dinàmica

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#728]
NOTA: Actualitzar la versió del Plugin d'Arxiu CAIB.

El filtre sobre els Expedient d'arxiu ha de ser dinàmic i poder afegir filtres a les propietats seguint aquest esquema:
es.caib.carpeta.pluginsib.carpetafront.expedients.filtre.1.metadada=...
es.caib.carpeta.pluginsib.carpetafront.expedients.filtre.1.operacio=...
es.caib.carpeta.pluginsib.carpetafront.expedients.filtre.1.valor1=...
es.caib.carpeta.pluginsib.carpetafront.expedients.filtre.1.valor2=...
es.caib.carpeta.pluginsib.carpetafront.expedients.filtre.2.metadada=...
...

Els valors per  filtre.X.operacio  poden ser IGUAL,CONTE,	MENOR,	MAJOR,	ENTRE,	NO_IGUAL i	NO_CONTE, que són les mateixes de la classe  es.caib.plugins.arxiu.api.ConsultaOperacio

**Comment by fbosch-fundaciobit** [comment]
S'ha afegit el codi per llegir els filtres des de les propietats del plugin de ElsMeusExpedients:

![image](https://user-images.githubusercontent.com/40387703/207852913-9addb90a-6a53-49fd-a42a-65c0b23875cb.png)
