### ISSUE TITLE
Utilitzar react-device-detect en la classe TemplatePageCarpeta de carpetacommonreactlib

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#730]
Utilitzar la  libreria react-device-detect en la classe TemplatePageCarpeta.tsx de [carpeta]\carpeta-pluginsib\pluginsib-carpetafront\carpetacommonreactlib.

S'han de substituir les classes CSS  visioMobil i ocultarMobil i s'han d'utilitzar comandes de la llibreria react-device-detect .

**Comment by fbosch-fundaciobit** [comment]
S'han eliminat les classes css visioMobil i ocultarMobil, i s'ha introduit la lògica de react-device-detect:

![image](https://user-images.githubusercontent.com/40387703/211497747-f6173584-3cd5-4d3a-936d-fb1e212063cb.png)


![image](https://user-images.githubusercontent.com/40387703/211497832-1beff2d8-05f4-4867-810f-f24a7c0194bf.png)
