### ISSUE TITLE
Estudiar la possibilitat d'afegir filtres a Plugin de Els meus Expedients

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#739]
Estudiar la possibilitat d'afegir filtres a Plugin de Els meus Expedients com per exemple nom d'expedient, descripció d'expedient, dates, estat, ...

**Comment by fbosch-fundaciobit** [comment]
Es podrien afegir filtres per nom, l'estat de l'expedient i per data, ja sigui en format de un rang de dates, o un dia especific, per filtrar els expedients per la seva data de **obertura**.

L'estructura del codi quedaria amb una lògica que implementés un filtre similar a aquest:

![image](https://user-images.githubusercontent.com/40387703/217522185-64079ca2-886d-46b5-8cf4-fd03825e857e.png)

Visualment, es podria incloure els filtres de la mateixa manera en la que es troben al plugin de Regweb 3.2:

![image](https://user-images.githubusercontent.com/40387703/217522402-e0ffd8ab-e9c8-41d6-b784-f22dc13e7ceb.png)

Els estats disponibles dels expedients per els que es podrien filtrar segons la documentació de la API del GDIB:

![image](https://user-images.githubusercontent.com/40387703/217523378-4d724ec4-bf41-4da7-baa8-a24ac08942b7.png)
