### ISSUE TITLE
Reordenar Columnes de Els meus Expedients

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#740]
Fer canvies en les Columnes de Els meus Expedients i 

(1) no mostrar la columna  de Descripció.
(2) Reordenar columnes. D'esquerra a dreta:
    Data
    Nom expedient
    Nom procediment (eliminaria la descripció)
    Codi SIA
    Òrgan
    Estat
(3) Formatejar DATA amb el format dd-mm-aaaa hh:ss

**Comment by fbosch-fundaciobit** [comment]
S'han reordenat les columens i formatejat la data:

![image](https://user-images.githubusercontent.com/40387703/214288521-292f673e-380b-47a0-a5aa-a84491947769.png)
