### ISSUE TITLE
Reorganitzar component de paginació

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#741]
Reorganitzar component de paginació de carpeta\carpeta-pluginsib\pluginsib-carpetafront\carpetacommonreactlib.
(1) Afegir Tamany de paginació opcional al final a l'esquerra.
(2) S'ha de passar un punter a una funció per canviar la paginació
(3) En els opcions, s'ha de poder passar opcionalment les mides de paginació. Si no, es posaran per defecte els valors 5, 10, 25.

Es pot provar amb el Plugin de els Meus Expedients.

NO TOCAR PLUGIN DE REGWEB  !!!!!!!!
NO TOCAR BOTO DE CERCA !!!!!!!

![imatge](https://user-images.githubusercontent.com/17084256/214259617-7eb09e83-a03b-4fe8-ab34-1a3d9b3b7a65.png)

![imatge](https://user-images.githubusercontent.com/17084256/214259632-6f76ad88-0023-4770-b2d4-63aea5ed8a79.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha afegit el component de paginació a les taules genèriques.

**Comment by fbosch-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/40387703/216071133-95490b02-b821-4daa-b7c3-7096dfd7eee4.png)
