### ISSUE TITLE
Millorar missatges de paginació

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#744]
Millorar missatges de paginació:
(1) Missatge de la dreta eliminar la paraula elements del final (és repetitiva)
(2) De la caixa de elements per pàgina substituir "registres" per "elements"

![imatge](https://user-images.githubusercontent.com/17084256/216268162-93d07e53-b9cc-44d8-8bf9-0701cb146cb3.png)

**Comment by fbosch-fundaciobit** [comment]
S'han modifcat els literals:

![image](https://user-images.githubusercontent.com/40387703/216550344-2d1e6af9-bc3c-4e0c-ba75-a391c8610819.png)
