### ISSUE TITLE
Alinear correctament la paginació de carpetacommonreactlib

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#745]
Alinear correctament la paginació de carpetacommonreactlib, tant verticalment com horitzontalment:

(1) Alinear Verticalment: Eliminar el padding de 0.7em

![imatge](https://user-images.githubusercontent.com/17084256/216269004-9b889947-7b72-4c43-abc3-c7f6ab12e145.png)

(2) Alinear horitzontalment a la dreta quan no hi hagi desplegable elementsPerPàgina:

![imatge](https://user-images.githubusercontent.com/17084256/216269116-d3c8d7da-a5df-42fa-b74b-7a5aa4d75944.png)

**Comment by fbosch-fundaciobit** [comment]
S'han alineat els components:

![image](https://user-images.githubusercontent.com/40387703/216927950-c58f8abf-01b8-4938-b856-62fbc9bfa52c.png)
