### ISSUE TITLE
Paginació de carpetacommonreactlib no omple completament l'espai disponible

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#746]
Paginació de carpetacommonreactlib no omple completament l'espai disponible tal i com s'observa a la captura.

![imatge](https://user-images.githubusercontent.com/17084256/216289271-9297fdef-6ddb-4997-981c-192d5dd65dd7.png)

**Comment by fbosch-fundaciobit** [comment]
S'han emprat estils de bootstrap per fer el component de paginació mes responsive:

![image](https://user-images.githubusercontent.com/40387703/217239763-a5bf0a1a-c895-4f90-9a0a-041bdb65226d.png)

![image](https://user-images.githubusercontent.com/40387703/217239826-a8f37775-30c1-40c0-aeea-481eeb8e6ba3.png)

![image](https://user-images.githubusercontent.com/40387703/217239874-7c8e102d-cb02-42b2-ab17-84967ea5ff27.png)
