### ISSUE TITLE
Component de Paginació requereix obligatoriament el camp elementsByPage

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#747]
(1) Cercar un altre nom per elementsByPage, ja que es confon amb l'altra camp elementsPerPagina. Per exemple llistaElementsPerPagina

(2) Si de la classe TaulaPaginadaTesterProps de carpetacommonreactlibtest eliminam el camp elementsByPage llavors falla quan canviam de elementsPerPagina. En principi és un camp opcional.

NOTA: Per provar si funciona, anar a Expedients i eliminar el valor per defecte [5,10,25]

![imatge](https://user-images.githubusercontent.com/17084256/216293757-f0916757-ebdd-4f80-9bf4-37ebdbf24627.png)

![imatge](https://user-images.githubusercontent.com/17084256/216294645-fdfb5fd0-ff8d-46a2-b90c-d09aa669ceee.png)

**Comment by fbosch-fundaciobit** [comment]
El test ja s'executa correctament quan s'introdueix la variable de la llista del desplegable per seleccionar num elements per pagina com a "undefined":

![image](https://user-images.githubusercontent.com/40387703/218746803-0dcd62a8-f3bb-415a-bbac-f76b4c385fb1.png)
