### ISSUE TITLE
Plugin els Meus Expedients: Millorar dels Estats d'un Expedient

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#750]
En el Plugin dels Meus Expedients millorar dels Estats d'un Expedient:
(1) Afegir Traduccions
(2) Gestionar tots els possibles tipus d'Estat

![imatge](https://user-images.githubusercontent.com/17084256/217490924-1d0748e3-5e94-4e19-a78f-d6f12f1f2853.png)

![imatge](https://user-images.githubusercontent.com/17084256/217490952-6f58bcae-8f84-4af4-927e-86c9f8648ddb.png)

**Comment by fbosch-fundaciobit** [comment]
S'han mapejat els estats dels expedients amb els posibles estats que retorna la API, i s'han inclos les traduccions:

![image](https://user-images.githubusercontent.com/40387703/218041882-f8b9b2f7-36b5-46b0-9dcf-69365dfb86f9.png)
