### ISSUE TITLE
El desplegable de Elements per Pàgina sempre mostra 5 elements

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#752]
El desplegable de Elements per Pàgina sempre mostra 5 elements.

Després d'elegir 10 elements per pàgina, la consulta es fa bé, però el desplegable segueix mostrant 5 elements.

![imatge](https://user-images.githubusercontent.com/17084256/218051787-53882002-32c9-4659-97fd-23b57d609d9e.png)

![imatge](https://user-images.githubusercontent.com/17084256/218051820-f41b464f-5b9f-4cb8-8184-0e4ff84e3c5e.png)

**Comment by fbosch-fundaciobit** [comment]
El desplegable ja mostra el numero d'elements corresponent als elements que es mostren.

S'ha solventat amb l'issue:  Component de Paginació requereix obligatoriament el camp elementsByPage #747

![image](https://user-images.githubusercontent.com/40387703/218747205-81125a4b-eca7-4bfd-bee2-5bbd16833c11.png)
