### ISSUE TITLE
Afegir Filtres al Plugin de Els Meus Expedients

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#764]
Afegir Filtres al Plugin de Els Meus Expedients.
En la versió 1.1.21 es va fer l'estudi de " Estudiar la possibilitat d'afegir filtres a Plugin de Els meus Expedients #739 " on es va confirmar que es podrien usar filtres en l'API de GDIB (Arxiu CAIB).
Afegir aquests filtres a la part React i modificar la cridada de React al PLugin per l'obtencio d'Expedirent per a que accepti filtres.

**Comment by fbosch-fundaciobit** [comment]
S'han afegit filtres al plugin de ElsMeusExpedients en el mateix format que els filtres del plugin de Regweb:

![image](https://user-images.githubusercontent.com/40387703/225299326-9f3deb25-662b-414e-80e9-80dcc05bdab8.png)

**Comment by anadal-fundaciobit** [comment]
S'han de fer filtres com a filterLIst no com a un if despres de la consulta !!!!!!

**Comment by fbosch-fundaciobit** [comment]
S'han pujat els canvis per corregir el funcionament dels filtres. Ara els filtres s'inclouen a la petició de la API de Arxiu, de manera que unicament retorni les dades que s'han de mostrar.

La API d'arxiu no funciona al moment de commitar. Queda pendent testejar el correcte funcionament dels filtres.

**Comment by anadal-fundaciobit** [comment]
Solucionat Filtre de Nom d'Expedient.
Consulta a Limit pel tema de Filtre sobre data d'obertura d'expedient.

**Comment by anadal-fundaciobit** [comment]
Demanar a Toni Trobat com fer-ho.
