### ISSUE TITLE
Adaptar paginació dels llistat al nou sistema disponible dins GenApp

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#768]
Adaptar paginació dels llistat al nou sistema disponible dins GenApp . Les passes a seguir estan descrites en aquest issue: https://github.com/Fundacio-Bit/pinbaladmin/issues/111

**Comment by fbosch-fundaciobit** [comment]
S'ha adaptat la nova paginació a dins carpeta:

![2023-03-28_15h14_16](https://user-images.githubusercontent.com/40387703/228248366-fa15d7dd-ae76-4c7f-a70a-dadd948b1fc3.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha corregit la paginació del back, amb la nova versió de paginació disponible a Genapp i s'han eliminat els filtres de la pàgina de logs d'errors ja que no funcionaven correctament:

![2023-04-05_09h19_12](https://user-images.githubusercontent.com/40387703/230009604-b32ba40d-9697-476b-98f0-d1005b7805be.png)

![2023-04-05_09h19_21](https://user-images.githubusercontent.com/40387703/230009629-c4c1ff5e-ce67-4b14-a62f-8c32d7f38eca.png)
