### ISSUE TITLE
Estandaritzar Plugin de Pinbal Matricula i fer proves

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#771]
Estandaritzar Plugin de Pinbal Matricula:
     * Usar Components Comuns
     *  Revisar si sobren camps a STATE

**Comment by fbosch-fundaciobit** [comment]
S'ha revisat el codi, i no s'ha trobat cap altre element que es pugui substituir per elements comuns, ni cap atributs dins "state" que es pugui eliminar.
