### ISSUE TITLE
Millores per plugin de registres

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [GovernIB/carpeta#780]
Millores per el plugin de registres (Regweb):

-  Millorar el format de la columna data, que es mostri tot a una sola linea, que no hi hagui salts de linea a la data i hora que es pinten.

- Que el ratoli quan faci hover damunt els elements de la paginació i damunt les files, es converteixi al format de l'icone de seleccionar un botó "curor pointer".

**Comment by anadal-fundaciobit** [comment]
Solucionats els dos problemes.
