### ISSUE TITLE
La frase del numero d'elements d'un total fer-ho no-wrap

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#785]
La frase del numero d'elements d'un total fer-ho no-wrap, és a dir, que la frase es mantengui sense fer salt de línia. 

El problema i la solució està a les captures adjuntes:

NOTA 1: fer-ho també per elements per pàgina (ficar-ho dins d'un div)
NOTA 2: Provar de centrar les tres columnes a veure si queda millor (veure darrera captura)
![imatge](https://github.com/GovernIB/carpeta/assets/17084256/283d5851-7898-4f61-9134-b4af81a791a2)

![imatge](https://github.com/GovernIB/carpeta/assets/17084256/a16def9c-a256-4c9d-a8a5-17f455d43b71)

![imatge](https://github.com/GovernIB/carpeta/assets/17084256/529a3960-8517-44f1-84e1-52c4d56cef65)

**Comment by fbosch-fundaciobit** [comment]
El text ja no es divideix amb salts de linea:

![2023-06-05_08h36_56](https://github.com/GovernIB/carpeta/assets/40387703/72eb19ab-3baa-4d9a-83e8-f5c97a207ff5)
