### ISSUE TITLE
El calendari dels filtres es retalla (CarpetaFront)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#786]
Quan en els llistats no hi ha elements i aquest té un filtre amb dates, llavors el calendari es mostra retallat per la part de baix com s'observa en la primera captura.

En la segona captura es mostra la solució: en principi es posaria a pinyo fix o es triaria una opció més quirúrgica i s'afegiria un flag al component TemplateCarpetaPage per afegir o no el min-height: s'ha de comentar. 

![imatge](https://github.com/GovernIB/carpeta/assets/17084256/c074cb49-50b9-4083-82d1-8138850c41bd)

![imatge](https://github.com/GovernIB/carpeta/assets/17084256/4ab672cf-3f7e-41d8-ac0c-772c289a452b)

**Comment by fbosch-fundaciobit** [comment]
S'ha introduit una altura minima de 470px al div de contingut del contenidor principal de carpeta commons, de manera que hi no es retalli el calendari quan es desplega:

![image](https://github.com/GovernIB/carpeta/assets/40387703/0f4fcb1a-4a74-4919-ad87-633abd4debde)
