### ISSUE TITLE
Netejar Plugins HTML

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#787]
Ja no tenim Plugins HTML però de per tots han quedat restes de codi del plugins HTML:

(1) Eliminar la part HTML del plugin /carpeta-pluginsib-carpetafront-reprendretramitsistra: aquets plugin pareix que té un funcionament dual. S'ha d'eliminar:
    * Recursos html
    * Mètode mostrarForm() i constant SHOW_FORM_TRAMITID
    * ...
   
(2) De carpeta-pluginsib-carpetafront-api fer neteja de tot lo referent a plugins-html
    * De ICarpetaFrontPlugin eliminar el mètode isReactComponent();
    * En principi s'ha d'eliminar tot de  /carpeta-pluginsib-carpetafront-api/src/main/resources/webresourcecommon
    * De /carpeta-pluginsib-carpetafront-api/src/main/java/es/caib/carpeta/pluginsib/carpetafront/api/AbstractCarpetaFrontPlugin.java s'ha eliminar la constant WEBRESOURCECOMMON i tot el que estigui relacionat.

(3) Moure /carpeta-pluginsib-carpetafront-api/src/main/java/es/caib/carpeta/pluginsib/carpetafront/api/AbstractPinbalCarpetaFrontPlugin.java a un mòdul independent així com la dependència 
<dependency>
            <groupId>es.caib.pinbal</groupId>
            <artifactId>pinbal-client</artifactId>
            <version>1.4.26</version>
<dependency>

**Comment by fbosch-fundaciobit** [comment]
S'han eliminat tota la part "no react" i la lògica per gestionarla als plugins.

No s'ha extret el mòdul de AbstractPinbalCarpetaFrontPlugin, ja que és un mòdul intern, sempre s'haurà d'incloure, i no guanyam res per separar-lo a un mòdul independent.
