### ISSUE TITLE
Triangle invertit de desplegable passa a una altra linia

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#789]
Quan la pantalla es redueix, el triangle invertit denotant un desplegable llavors passa una línia abaix tal i com s'observa a la part dreta de la captura adjunta

COM SOLUCIONAR-HO: https://stackoverflow.com/questions/50958894/nav-dropdown-icon-jumping-to-new-line

![imatge](https://github.com/GovernIB/carpeta/assets/17084256/9e1aae52-c7a9-4828-ac0c-a4c29851475f)

**Comment by fbosch-fundaciobit** [comment]
S'ha provat a afegir l'estil "nowrap", però no ha funcionat:

![image](https://github.com/GovernIB/carpeta/assets/40387703/c8659fd8-f10e-4c7b-89e5-7ed416967630)


![image](https://github.com/GovernIB/carpeta/assets/40387703/a1e00f80-06e5-4b97-baed-af2b98ac6de0)

**Comment by fbosch-fundaciobit** [comment]
S'ha inclos l'estil  display: "inline-block"  perque apareguin els icones un devora l'altre sense salts e linea:

![2023-07-26_12h24_32](https://github.com/GovernIB/carpeta/assets/40387703/62307e99-b899-4659-a790-24d6d994bae3)
