### ISSUE TITLE
En detall de Registre ha d'aparèixer informació del Representant

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#791]
En detall de Registre, en l'apartat de Interessats ha d'aparèixer informació del Representant si n'hi ha.

**Comment by fbosch-fundaciobit** [comment]
S'han afegit les columnes de "Representant" i "Document Representant" de manera dinamica, perque apareguin quan un registre té representant, en el seguent format: 

![image](https://github.com/GovernIB/carpeta/assets/40387703/54cb1894-9826-41cb-8e1a-70dd5efba228)


![image](https://github.com/GovernIB/carpeta/assets/40387703/a703d671-9312-4b60-afc3-209a3a9ce4d2)
