### ISSUE TITLE
Crear plugin d'obtenció de certificats

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [GovernIB/carpeta#799]
Fent ús de la API de mock que hem creat a carpeta api-externa, crear el plugin que mostri els certificats.

**Comment by fbosch-fundaciobit** [comment]
La deserialització no funciona correctament en JBOSS. (Funciona correctament com a Standalone als tests). Posiblement per alguna incompatibilitat de dependencies.

**Comment by anadal-fundaciobit** [comment]
Solucionat.
