### ISSUE TITLE
No funciona l'accés per paràmetre a Detall de Registre

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#800]
No funciona l'accés per paràmetre a Detall de Registre

Exemple:

http://localhost:8080/carpetafront/#/modul/registres/p/R09JQkU0MDI4NTAvMjAyMw

on R09JQkU0MDI4NTAvMjAyMw és el Numero de Registre en B64.

Pareix ser que aquesta funcionalitat s'ha perdut ja que sempre va al llistat i no al detall del registre.

**Comment by fbosch-fundaciobit** [comment]
Ja es mostra el detall del regiustre quan es passa l'identificador del registre en base64 com a parámetre a la URL:

![2023-07-11_09h52_36](https://github.com/GovernIB/carpeta/assets/40387703/b6405cfc-f5ea-4cdf-b1d2-d64983b48887)
