### ISSUE TITLE
Obtenir mètriques de Google Analytics a Carpeta

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/carpeta#812]
Ens sol·liciten obtenir mètriques de Google Analytics per CARPETA per comprovar el comportament dels usuaris.

S'ha d'incorporar el següent en la capçalera de les pàgines que vulguem 'trackejar'.  

Ho posaria a totes les pàgines (al <head> comú) si se pot.  Per si pot ajudar: https://www.paradigmadigital.com/dev/anadir-google-analytics-web-desarrollada-react/ .

--------------------------------

Abajo está la etiqueta de Google de esta cuenta. Cópiela y péguela en el código de cada página de su sitio web, justo después del elemento <head>. No añada más de una etiqueta de Google a cada página.

PRE:

<script async src="https://www.googletagmanager.com/gtag/js?id=G-TM4RLMKYJG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-TM4RLMKYJG');
</script>

PRO:

<script async src="https://www.googletagmanager.com/gtag/js?id=G-567C74Q84W"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-567C74Q84W');
</script>
----------------------------------

**Comment by fbosch-fundaciobit** [comment]
S'ha inclos el nou script de Google Analitics.

Esta lligat a una nova entrada a l'arxiu carpeta.properties per definir la clau de Google segons si es tracta d'un desplegament a producció o pre-produccio.

La nova clau es troba definida al document de migració.
