### ISSUE TITLE
No es llancen les consultes als plugins de PINBAL

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/carpeta#813]
Quan accedeixes a un plugin de PINBAL a carpeta de producció no es carrega el plugin

![image](https://github.com/GovernIB/carpeta/assets/17315737/20cfa1c6-0fd6-4a02-86a2-d3181fc37bbe)

Passa a tots els plugins de pinbal excepte a la consulta d'estar al corrent de pagaments per contractació. Una vegada has accedit a aquesta consulta si vas a qualsevol dels altres plugins de PINBAL si que funciona la consulta.

**Comment by fbosch-fundaciobit** [comment]
S'ha solventat el problema de Javascript. Hi havia un conflicte amb la dependencia de carpeta-front de traduccions amb les dependencies de traduccions emprades als plugins.

Queda pendent solventar un problema amb la API de Pinbal. Actualment la versió antiga de la API dona problemes al plugin de dades de discapacitat, mentre que la nova versió de la API dona un error d'autenticació quan s'intenta accedir a qualsevol altre servei.

**Comment by fbosch-fundaciobit** [comment]
S'ha actualitzat la versió de la API de Pinbal a la darrera versió, i ja es llançen les consultes correctament.
