### ISSUE TITLE
Cada vegada que es descarrega el Justificant de regweb32 s'imprimeix al log

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#816]
Cada vegada que es descarrega el Justificant de regweb32 s'imprimeix al log.

S'ha de deixar de fer.

`12:36:43,279 INFO  [org.fundaciobit.pluginsib.carpetafront.regweb32.Regweb32CarpetaFrontPlugin] (default task-3) Generat: {"justificantData":"JVBERi0xLjQKJeLjz9MKMiAwIG9iago8PC9Db2xvclNwYWNlL0RldmljZVJHQi9TdWJ0eXBlL0ltYWdlL0hlaWdodCA0OC9GaWx0ZXIvRENURGVjb2RlL1R5cGUvWE9iamVjdC9XaWR0aCAyMDAvQml0c1BlckNvbXBvbmVudCA4L0xlbmd0aCA4MzU1Pj5zdHJlYW0K/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAwAMgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD+xT40f8FBf2afgR45vvh1438Sa9J4s0y3tZtUstD8Mapq1tppvIzdW8M18q21nPcSQkGSGyuL37If9EvDb3qz2q+Wn/grZ+x7/wBB3xwfTPgbU/8A47X4J/t8Dd+2N8fguW/4rcZCe+jaSf8AHPrzXyjJpOsQo0s2k6pDGmJHmm028jjT2nuPs34fqelfyDn3jdxjgc4zXAYLDZfOhgszxGGw7WFxE19XoV1Q15auknZ9O9vKHKSfwfhL/P8Aq78rf1M/8Pav2O/+g745/wDCF1T/AOP0f8Pav2O/+g745/8ACF1T/wCP1/KtRXjP6QPGydnR`

**Comment by fbosch-fundaciobit** [comment]
S'ha eliminat el codi que imprimeix el justificant
