### ISSUE TITLE
Menú Lateral en Mòbil i PC no surt bé.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#823]
Menú Lateral en Mòbil i PC no surt bé.

Veure imatges adjuntes.

![Screenshot_20230918-225507](https://github.com/GovernIB/carpeta/assets/17084256/cb8eadbe-302d-4a92-8e5b-dfa3bd7bac9b)

![imatge](https://github.com/GovernIB/carpeta/assets/17084256/edebf3bc-ce94-49fe-9727-702f2e84e0b7)

**Comment by fbosch-fundaciobit** [comment]
S'han arreglat els icones del menú de la barra lateral, tant en la versió desktop com mòbil:

![image](https://github.com/GovernIB/carpeta/assets/40387703/7e590786-cb91-4d85-a2bb-03e79df69e44)
