### ISSUE TITLE
 Falta traducció botó "carpeta_descargar"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#824]
Quan fas una cerca des de "Els meus trámits" i accedeixes al detall d'un trámit acabat... Carpeta et redirecciona al detall d'un registre.

Bé, no es carrega la etiqueta del botó de descarregar justificant. 

Si s'entra al detall del registre des de "Els meus registres", funciona correctament.

![vYTTlsylqGbZJH0K](https://github.com/GovernIB/carpeta/assets/17084256/faaeff0c-e660-414c-a382-103e1d835240)

![uJogvqJTgnkIg8WM](https://github.com/GovernIB/carpeta/assets/17084256/5baf0a02-6f7e-4322-87dd-8dd8883a8fae)

**Comment by fbosch-fundaciobit** [comment]
S'ha arreglat la traducció, i s'ha canviat la configuració per mostrar els tramits i registres de dev.caib.es:

![image](https://github.com/GovernIB/carpeta/assets/40387703/ceb2ed38-042b-4d12-bfff-2eefc2975559)
