### ISSUE TITLE
Actualitzar llibreria de notib-client a la llibreria notib-client-2

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [GovernIB/carpeta#834]
Actualment el plugin de notib empra la llibreria notib-client per interactuar amb l'API de Notib.

S'ha d'eliminar aquesta depenència, i substituirla per la de notib-client-2, que és la seguent al repositori de Maven:

<groupId>es.caib.notib</groupId>
    <artifactId>notib-client-2</artifactId>
    <version>2.0.1</version>

La URL a la nova API de notib també s'ha d'actualitzar.

**Comment by fbosch-fundaciobit** [comment]
A al espera de que Limit actualitzi el openapi.json per poder generar el client.

**Comment by fbosch-fundaciobit** [comment]
S'ha regenerat la API amb la nova versió del openapi.json. Encara hi ha errors al model.

Esperant a la segona revisió del openapi.json

**Comment by anadal-fundaciobit** [comment]
Solucionat !!!!
