### ISSUE TITLE
Provar PLugin de Certificats si segueix funcionant

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#847]
S'han fet canvis en l'API de Certificats. Comprovar que segueix funcionant el plugin de Certificats

**Comment by fbosch-fundaciobit** [comment]
La API segueix funcionant correctament, però s'ha obert un issue per un cas pendent. 

Els certificats amb URL però sense fitxer, no redirigeixen correctament a la URL de la resposta. S'ha proposat com a millora.
