### ISSUE TITLE
Generar carpeta-pluginsib-carpetafront-notib2client tal i com es generen els clients de API Interna o API Externa

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#849]
Generar carpeta-pluginsib-carpetafront-notib2client tal i com es generen els clients de API Interna o API Externa

**Comment by fbosch-fundaciobit** [comment]
S'ha modificat el plugin de generació del client de l'API al mateix de la API interna i externa de carpeta:

![image](https://github.com/GovernIB/carpeta/assets/40387703/9ae830a5-4e97-4024-841a-3ed4720ca0d2)
