### ISSUE TITLE
Creació dels mètodes CRUD dels EJBs 

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/carpeta#85]
Desenvolupar tots els mètodes CRUD dels EJBs de carpeta per a la funcionalitat del Backoffice.
En concret s'han d'implementar les següents classes i interficies que es subdivideixen en els següents blocs:

Bloc 1 #87 
Bloc 2 #88 
Bloc 3 #89 
Bloc 4 #90 

Aquesta tasca prové de #80.

**Comment by scalafat-dgtic** [comment]
Subtasques tancades.
Tancam tasca CAIB
