### ISSUE TITLE
Integrar front amb LOGINIB i pàgines inicials (autenticada i pública)

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#91]
**Com a** desenvolupador del Front **vull** tenir una integració de Carpeta amb LoginIB **per a** poder fer l'autenticació d'un usuari

Inclourà:
- Integració amb LOGINIB #92 
- Crear una vista de la pàgina inicial sense autenticar #93 
- Crear una vista de la pàgina inicial autenticada #94 
- Crear estructura per generar les vistes #95

**Comment by scalafat-dgtic** [comment]
Totes les subtasques que hi pengen estan tancades.
Tanc tasca CAIB
